@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x0004BEF4-0x0004D424
    .syntax unified

    .global EkrLvupFanMain
    .type EkrLvupFanMain, %function
    .thumb
    .thumb_func
EkrLvupFanMain:  @ 0x0804BEF4 (jp 0x0804C8AC, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x8DA0  @ ldrh r0, [r4, #0x2c]
    .hword 0x3001  @ adds r0, #1
    .hword 0x85A0  @ strh r0, [r4, #0x2c]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x2810  @ cmp r0, #0x10
    .hword 0xD10E  @ bne #0x20
    .hword 0x4C06  @ ldr r4, [pc, #0x18]
    .hword 0x2180  @ movs r1, #0x80
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFBBFF01B  @ bl #0x1b782
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2178  @ movs r1, #0x78
    .hword 0x2200  @ movs r2, #0
    .word 0xFC4AF01B  @ bl #0x1b898
    .hword 0xE00B  @ b #0x1a
    .hword 0x0000  @ movs r0, r0
    .hword 0x037B  @ lsls r3, r7, #0xd
    .hword 0x0000  @ movs r0, r0
    .hword 0x2874  @ cmp r0, #0x74
    .hword 0xD106  @ bne #0x10
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x0040  @ lsls r0, r0, #1
    .word 0xFB46F7B7  @ bl #0xfffb7690
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFBC1F7B8  @ bl #0xfffb8786
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_804C8F4
    .type sub_804C8F4, %function
    .thumb
    .thumb_func
sub_804C8F4:  @ 0x0804BF3C (jp 0x0804C8F4, score 0.8438)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0xB081  @ sub sp, #4
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C0F  @ adds r7, r1, #0
    .hword 0x2600  @ movs r6, #0
    .hword 0x1C3D  @ adds r5, r7, #0
    .hword 0x8820  @ ldrh r0, [r4]
    .hword 0x210F  @ movs r1, #0xf
    .hword 0x28FF  @ cmp r0, #0xff
    .hword 0xD000  @ beq #4
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x0148  @ lsls r0, r1, #5
    .hword 0x490B  @ ldr r1, [pc, #0x2c]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x2208  @ movs r2, #8
    .word 0xFB3CF074  @ bl #0x7467c
    .hword 0x3402  @ adds r4, #2
    .hword 0x3520  @ adds r5, #0x20
    .hword 0x3601  @ adds r6, #1
    .hword 0x2E0A  @ cmp r6, #0xa
    .hword 0xD9EE  @ bls #0xffffffe0
    .hword 0x2000  @ movs r0, #0
    .hword 0x9000  @ str r0, [sp]
    .hword 0x20C0  @ movs r0, #0xc0
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x1839  @ adds r1, r7, r0
    .hword 0x4A04  @ ldr r2, [pc, #0x10]
    .hword 0x4668  @ mov r0, sp
    .word 0xFB2EF074  @ bl #0x74660
    .hword 0xB001  @ add sp, #4
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x06BC  @ lsls r4, r7, #0x1a
    .hword 0x082C  @ lsrs r4, r5, #0x20
    .hword 0x0008  @ movs r0, r1
    .hword 0x0100  @ lsls r0, r0, #4

    .global sub_804C944
    .type sub_804C944, %function
    .thumb
    .thumb_func
sub_804C944:  @ 0x0804BF8C (jp 0x0804C944, score 0.8438)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x1406  @ asrs r6, r0, #0x10
    .hword 0x2001  @ movs r0, #1
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x4286  @ cmp r6, r0
    .hword 0xD105  @ bne #0xe
    .hword 0x200B  @ movs r0, #0xb
    .hword 0x8028  @ strh r0, [r5]
    .hword 0x200A  @ movs r0, #0xa
    .hword 0x8068  @ strh r0, [r5, #2]
    .hword 0x80A8  @ strh r0, [r5, #4]
    .hword 0xE021  @ b #0x46
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x2164  @ movs r1, #0x64
    .word 0xFB18F074  @ bl #0x74634
    .hword 0x8028  @ strh r0, [r5]
    .hword 0x8829  @ ldrh r1, [r5]
    .hword 0x2064  @ movs r0, #0x64
    .hword 0x1C0C  @ adds r4, r1, #0
    .hword 0x4344  @ muls r4, r0, r4
    .hword 0x1B34  @ subs r4, r6, r4
    .hword 0x0424  @ lsls r4, r4, #0x10
    .hword 0x1424  @ asrs r4, r4, #0x10
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x210A  @ movs r1, #0xa
    .word 0xFB0CF074  @ bl #0x7461c
    .hword 0x8068  @ strh r0, [r5, #2]
    .hword 0x8869  @ ldrh r1, [r5, #2]
    .hword 0x0088  @ lsls r0, r1, #2
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x1A24  @ subs r4, r4, r0
    .hword 0x80AC  @ strh r4, [r5, #4]
    .hword 0x8829  @ ldrh r1, [r5]
    .hword 0x8868  @ ldrh r0, [r5, #2]
    .hword 0x42C1  @ cmn r1, r0
    .hword 0xD101  @ bne #6
    .hword 0x200B  @ movs r0, #0xb
    .hword 0x8068  @ strh r0, [r5, #2]
    .hword 0x8828  @ ldrh r0, [r5]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD101  @ bne #6
    .hword 0x200B  @ movs r0, #0xb
    .hword 0x8028  @ strh r0, [r5]
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global NewEkrGauge
    .type NewEkrGauge, %function
    .thumb
    .thumb_func
NewEkrGauge:  @ 0x0804BFF4 (jp 0x0804C9AC, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x464F  @ mov r7, sb
    .hword 0x4646  @ mov r6, r8
    .hword 0xB4C0  @ push {r6, r7}
    .hword 0xB082  @ sub sp, #8
    .hword 0x4C10  @ ldr r4, [pc, #0x40]
    .hword 0x4810  @ ldr r0, [pc, #0x40]
    .hword 0x2101  @ movs r1, #1
    .word 0xFA4CF7B8  @ bl #0xfffb849c
    .hword 0x6020  @ str r0, [r4]
    .hword 0x2000  @ movs r0, #0
    .word 0xF98EF000  @ bl #0x320
    .word 0xF96CF000  @ bl #0x2dc
    .word 0xF9BEF000  @ bl #0x380
    .word 0xF9ACF000  @ bl #0x35c
    .hword 0x490A  @ ldr r1, [pc, #0x28]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E88  @ ldrsh r0, [r1, r2]
    .hword 0x2202  @ movs r2, #2
    .hword 0x5E89  @ ldrsh r1, [r1, r2]
    .word 0xF989F000  @ bl #0x316
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x2850  @ cmp r0, #0x50
    .hword 0xDD11  @ ble #0x26
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0x4907  @ ldr r1, [pc, #0x1c]
    .hword 0x2210  @ movs r2, #0x10
    .word 0xFACFF074  @ bl #0x745a2
    .hword 0xE015  @ b #0x2e
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x61B8  @ str r0, [r7, #0x18]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x0038  @ movs r0, r7
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0xE0B8  @ b #0x174
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x0A3C  @ lsrs r4, r7, #8
    .hword 0x082C  @ lsrs r4, r5, #0x20
    .hword 0x2BC0  @ cmp r3, #0xc0
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E80  @ ldrsh r0, [r0, r2]
    .hword 0x0140  @ lsls r0, r0, #5
    .hword 0x4909  @ ldr r1, [pc, #0x24]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4909  @ ldr r1, [pc, #0x24]
    .hword 0x2210  @ movs r2, #0x10
    .word 0xFAB8F074  @ bl #0x74574
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x2850  @ cmp r0, #0x50
    .hword 0xDD12  @ ble #0x28
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x4907  @ ldr r1, [pc, #0x1c]
    .hword 0x2210  @ movs r2, #0x10
    .word 0xFAAEF074  @ bl #0x74560
    .hword 0xE016  @ b #0x30
    .hword 0x0000  @ movs r0, r0
    .hword 0xE020  @ b #0x44
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x08BC  @ lsrs r4, r7, #2
    .hword 0x082C  @ lsrs r4, r5, #0x20
    .hword 0x2BC0  @ cmp r3, #0xc0
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE0B8  @ b #0x174
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x0A3C  @ lsrs r4, r7, #8
    .hword 0x082C  @ lsrs r4, r5, #0x20
    .hword 0x2BE0  @ cmp r3, #0xe0
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x4816  @ ldr r0, [pc, #0x58]
    .hword 0x2202  @ movs r2, #2
    .hword 0x5E80  @ ldrsh r0, [r0, r2]
    .hword 0x0140  @ lsls r0, r0, #5
    .hword 0x4915  @ ldr r1, [pc, #0x54]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4915  @ ldr r1, [pc, #0x54]
    .hword 0x2210  @ movs r2, #0x10
    .word 0xFA96F074  @ bl #0x74530
    .hword 0x4914  @ ldr r1, [pc, #0x50]
    .hword 0x4815  @ ldr r0, [pc, #0x54]
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x2001  @ movs r0, #1
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x4813  @ ldr r0, [pc, #0x4c]
    .hword 0x4914  @ ldr r1, [pc, #0x50]
    .word 0xFA96F074  @ bl #0x74530
    .hword 0x4813  @ ldr r0, [pc, #0x4c]
    .hword 0x4914  @ ldr r1, [pc, #0x50]
    .word 0xFA92F074  @ bl #0x74528
    .word 0xF986F7B9  @ bl #0xfffb9310
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD03F  @ beq #0x82
    .word 0xF982F7B9  @ bl #0xfffb9308
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD12B  @ bne #0x5a
    .hword 0x480F  @ ldr r0, [pc, #0x3c]
    .hword 0x4910  @ ldr r1, [pc, #0x40]
    .word 0xFA86F074  @ bl #0x74510
    .hword 0x480F  @ ldr r0, [pc, #0x3c]
    .hword 0x4910  @ ldr r1, [pc, #0x40]
    .word 0xFA82F074  @ bl #0x74508
    .hword 0x480F  @ ldr r0, [pc, #0x3c]
    .hword 0x4910  @ ldr r1, [pc, #0x40]
    .word 0xFA7EF074  @ bl #0x74500
    .hword 0xE02E  @ b #0x60
    .hword 0x0000  @ movs r0, r0
    .hword 0xE020  @ b #0x44
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x08BC  @ lsrs r4, r7, #2
    .hword 0x082C  @ lsrs r4, r5, #0x20
    .hword 0x2BE0  @ cmp r3, #0xe0
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE0C0  @ b #0x184
    .hword 0x0203  @ lsls r3, r0, #8
    .byte 0xFF
    .hword 0x00FF  @ lsls r7, r7, #3
    .hword 0x6400  @ str r0, [r0, #0x40]
    .hword 0x2C01  @ cmp r4, #1
    .hword 0x0008  @ movs r0, r1
    .hword 0x0138  @ lsls r0, r7, #4
    .hword 0x0406  @ lsls r6, r0, #0x10
    .hword 0x2C02  @ cmp r4, #2
    .hword 0x0008  @ movs r0, r1
    .hword 0x013C  @ lsls r4, r7, #4
    .word 0x2C04F406  @ and ip, r6, #0x84000
    .hword 0x2008  @ movs r0, #8
    .hword 0x0138  @ lsls r0, r7, #4
    .hword 0x3C06  @ subs r4, #6
    .hword 0x2C05  @ cmp r4, #5
    .hword 0xA008  @ adr r0, #0x20
    .hword 0x0138  @ lsls r0, r7, #4
    .hword 0x8806  @ ldrh r6, [r0]
    .hword 0x2C05  @ cmp r4, #5
    .hword 0x2008  @ movs r0, #8
    .hword 0x013C  @ lsls r4, r7, #4
    .hword 0xB906  @ cbnz r6, #4
    .hword 0x52F7  @ strh r7, [r6, r3]
    .hword 0x02F9  @ lsls r1, r7, #0xb
    .hword 0x0B28  @ lsrs r0, r5, #0xc
    .hword 0x51D1  @ str r1, [r2, r7]
    .hword 0x5248  @ strh r0, [r1, r1]
    .hword 0x7449  @ strb r1, [r1, #0x11]
    .hword 0x56F0  @ ldrsb r0, [r6, r3]
    .hword 0x51FA  @ str r2, [r7, r7]
    .hword 0x5248  @ strh r0, [r1, r1]
    .hword 0x7449  @ strb r1, [r1, #0x11]
    .hword 0x52F0  @ strh r0, [r6, r3]
    .hword 0x51FA  @ str r2, [r7, r7]
    .hword 0x5248  @ strh r0, [r1, r1]
    .hword 0x7449  @ strb r1, [r1, #0x11]
    .hword 0x4EF0  @ ldr r6, [pc, #0x3c0]
    .hword 0x51FA  @ str r2, [r7, r7]
    .hword 0x004E  @ lsls r6, r1, #1
    .hword 0x7021  @ strb r1, [r4]
    .hword 0x405E  @ eors r6, r3
    .hword 0x5001  @ str r1, [r0, r0]
    .hword 0x404D  @ eors r5, r1
    .hword 0x5019  @ str r1, [r3, r0]
    .hword 0x214C  @ movs r1, #0x4c
    .hword 0x081C  @ lsrs r4, r3, #0x20
    .hword 0x7422  @ strb r2, [r4, #0x10]
    .hword 0x37F0  @ adds r7, #0xf0
    .hword 0x02FA  @ lsls r2, r7, #0xb
    .hword 0xB022  @ add sp, #0x88
    .hword 0x405E  @ eors r6, r3
    .hword 0x4001  @ ands r1, r0
    .hword 0x2019  @ movs r0, #0x19
    .hword 0x2134  @ movs r1, #0x34
    .hword 0x081C  @ lsrs r4, r3, #0x20
    .hword 0x7422  @ strb r2, [r4, #0x10]
    .hword 0x2EF0  @ cmp r6, #0xf0
    .hword 0xB4FA  @ push {r1, r3, r4, r5, r6, r7}
    .hword 0x74F7  @ strb r7, [r6, #0x13]
    .hword 0x49FF  @ ldr r1, [pc, #0x3fc]
    .hword 0x004E  @ lsls r6, r1, #1
    .hword 0x7021  @ strb r1, [r4]
    .hword 0x495E  @ ldr r1, [pc, #0x178]
    .hword 0x394F  @ subs r1, #0x4f
    .byte 0x1C
    .word 0xFEFFF7FF  @ bl #0xfffffe02
    .hword 0x4D48  @ ldr r5, [pc, #0x120]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5EA8  @ ldrsh r0, [r5, r2]
    .hword 0x1DB9  @ adds r1, r7, #6
    .word 0xFEF9F7FF  @ bl #0xfffffdf6
    .hword 0x4C46  @ ldr r4, [pc, #0x118]
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E60  @ ldrsh r0, [r4, r1]
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x310C  @ adds r1, #0xc
    .word 0xFEF2F7FF  @ bl #0xfffffde8
    .hword 0x2202  @ movs r2, #2
    .hword 0x5EB0  @ ldrsh r0, [r6, r2]
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x3112  @ adds r1, #0x12
    .word 0xFEECF7FF  @ bl #0xfffffddc
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E68  @ ldrsh r0, [r5, r1]
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x3118  @ adds r1, #0x18
    .word 0xFEE6F7FF  @ bl #0xfffffdd0
    .hword 0x2202  @ movs r2, #2
    .hword 0x5EA0  @ ldrsh r0, [r4, r2]
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x311E  @ adds r1, #0x1e
    .word 0xFEE0F7FF  @ bl #0xfffffdc4
    .hword 0x2000  @ movs r0, #0
    .hword 0x9000  @ str r0, [sp]
    .hword 0x4939  @ ldr r1, [pc, #0xe4]
    .hword 0x4A3A  @ ldr r2, [pc, #0xe8]
    .hword 0x4668  @ mov r0, sp
    .word 0xF9FFF074  @ bl #0x74402
    .hword 0x2600  @ movs r6, #0
    .hword 0x46B9  @ mov sb, r7
    .hword 0x2500  @ movs r5, #0
    .hword 0x0073  @ lsls r3, r6, #1
    .hword 0x1C70  @ adds r0, r6, #1
    .hword 0x4680  @ mov r8, r0
    .hword 0x01F4  @ lsls r4, r6, #7
    .hword 0x1998  @ adds r0, r3, r6
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x4448  @ add r0, sb
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x0140  @ lsls r0, r0, #5
    .hword 0x4932  @ ldr r1, [pc, #0xc8]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4F2F  @ ldr r7, [pc, #0xbc]
    .hword 0x19E1  @ adds r1, r4, r7
    .hword 0x2210  @ movs r2, #0x10
    .hword 0x9301  @ str r3, [sp, #4]
    .word 0xF9ECF074  @ bl #0x743dc
    .hword 0x3420  @ adds r4, #0x20
    .hword 0x3501  @ adds r5, #1
    .hword 0x9B01  @ ldr r3, [sp, #4]
    .hword 0x2D02  @ cmp r5, #2
    .hword 0xD9EC  @ bls #0xffffffdc
    .hword 0x4646  @ mov r6, r8
    .hword 0x2E05  @ cmp r6, #5
    .hword 0xD9E4  @ bls #0xffffffcc
    .hword 0x492B  @ ldr r1, [pc, #0xac]
    .hword 0x24C0  @ movs r4, #0xc0
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x1C22  @ adds r2, r4, #0
    .word 0xFF31F7B6  @ bl #0xfffb6e66
    .hword 0x1938  @ adds r0, r7, r4
    .hword 0x4928  @ ldr r1, [pc, #0xa0]
    .hword 0x1C22  @ adds r2, r4, #0
    .word 0xFF2CF7B6  @ bl #0xfffb6e5c
    .word 0xFD78F7B8  @ bl #0xfffb8af4
    .hword 0x2000  @ movs r0, #0
    .hword 0x211D  @ movs r1, #0x1d
    .word 0xFDA2F7B8  @ bl #0xfffb8b48
    .hword 0x2000  @ movs r0, #0
    .hword 0x211E  @ movs r1, #0x1e
    .word 0xFD9EF7B8  @ bl #0xfffb8b40
    .hword 0x4822  @ ldr r0, [pc, #0x88]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x304A  @ adds r0, #0x4a
    .hword 0x8800  @ ldrh r0, [r0]
    .word 0xFAB4F7CB  @ bl #0xfffcb56c
    .hword 0x21EE  @ movs r1, #0xee
    .hword 0x0049  @ lsls r1, r1, #1
    .word 0xFE40F7B8  @ bl #0xfffb8c84
    .hword 0x481E  @ ldr r0, [pc, #0x78]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x304A  @ adds r0, #0x4a
    .hword 0x8800  @ ldrh r0, [r0]

    .incbin "rom/fe7eu.gba", 0x4C25C, 0x7C

    .global EndEkrGauge
    .type EndEkrGauge, %function
    .thumb
    .thumb_func
EndEkrGauge:  @ 0x0804C2D8 (jp 0x0804CC14, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x6800  @ ldr r0, [r0]
    .word 0xF957F7B8  @ bl #0xfffb82b2
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_0804CC28
    .type EkrGauge_0804CC28, %function
    .thumb
    .thumb_func
EkrGauge_0804CC28:  @ 0x0804C2EC (jp 0x0804CC28, score 1.0)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2000  @ movs r0, #0
    .hword 0x64C8  @ str r0, [r1, #0x4c]
    .hword 0x6508  @ str r0, [r1, #0x50]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_0804CC38
    .type EkrGauge_0804CC38, %function
    .thumb
    .thumb_func
EkrGauge_0804CC38:  @ 0x0804C2FC (jp 0x0804CC38, score 1.0)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .hword 0x64C8  @ str r0, [r1, #0x4c]
    .hword 0x6508  @ str r0, [r1, #0x50]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_0804CC48
    .type EkrGauge_0804CC48, %function
    .thumb
    .thumb_func
EkrGauge_0804CC48:  @ 0x0804C30C (jp 0x0804CC48, score 1.0)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .hword 0x64C8  @ str r0, [r1, #0x4c]
    .hword 0x4770  @ bx lr
    .hword 0x0000  @ movs r0, r0
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_0804CC58
    .type EkrGauge_0804CC58, %function
    .thumb
    .thumb_func
EkrGauge_0804CC58:  @ 0x0804C31C (jp 0x0804CC58, score 1.0)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .hword 0x6508  @ str r0, [r1, #0x50]
    .hword 0x4770  @ bx lr
    .hword 0x0000  @ movs r0, r0
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_0804CC68
    .type EkrGauge_0804CC68, %function
    .thumb
    .thumb_func
EkrGauge_0804CC68:  @ 0x0804C32C (jp 0x0804CC68, score 1.0)
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4902  @ ldr r1, [pc, #8]
    .hword 0x6809  @ ldr r1, [r1]
    .hword 0x0980  @ lsrs r0, r0, #6
    .hword 0x6448  @ str r0, [r1, #0x44]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_0804CC78
    .type EkrGauge_0804CC78, %function
    .thumb
    .thumb_func
EkrGauge_0804CC78:  @ 0x0804C33C (jp 0x0804CC78, score 1.0)
    .hword 0x4A03  @ ldr r2, [pc, #0xc]
    .hword 0x6812  @ ldr r2, [r2]
    .hword 0x2300  @ movs r3, #0
    .hword 0x8650  @ strh r0, [r2, #0x32]
    .hword 0x8751  @ strh r1, [r2, #0x3a]
    .hword 0x3229  @ adds r2, #0x29
    .hword 0x7013  @ strb r3, [r2]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_0804CC8C
    .type EkrGauge_0804CC8C, %function
    .thumb
    .thumb_func
EkrGauge_0804CC8C:  @ 0x0804C350 (jp 0x0804CC8C, score 1.0)
    .hword 0x4A03  @ ldr r2, [pc, #0xc]
    .hword 0x6812  @ ldr r2, [r2]
    .hword 0x8650  @ strh r0, [r2, #0x32]
    .hword 0x8751  @ strh r1, [r2, #0x3a]
    .hword 0x3229  @ adds r2, #0x29
    .hword 0x2001  @ movs r0, #1
    .hword 0x7010  @ strb r0, [r2]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_SetInitFlag
    .type EkrGauge_SetInitFlag, %function
    .thumb
    .thumb_func
EkrGauge_SetInitFlag:  @ 0x0804C364 (jp 0x0804CCA0, score 1.0)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x3029  @ adds r0, #0x29
    .hword 0x2101  @ movs r1, #1
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrGauge_ClrInitFlag
    .type EkrGauge_ClrInitFlag, %function
    .thumb
    .thumb_func
EkrGauge_ClrInitFlag:  @ 0x0804C374 (jp 0x0804CCB0, score 1.0)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x3029  @ adds r0, #0x29
    .hword 0x2100  @ movs r1, #0
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EnableEkrGauge
    .type EnableEkrGauge, %function
    .thumb
    .thumb_func
EnableEkrGauge:  @ 0x0804C384 (jp 0x0804CCC0, score 1.0)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x302A  @ adds r0, #0x2a
    .hword 0x2101  @ movs r1, #1
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global DisableEkrGauge
    .type DisableEkrGauge, %function
    .thumb
    .thumb_func
DisableEkrGauge:  @ 0x0804C394 (jp 0x0804CCD0, score 1.0)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x302A  @ adds r0, #0x2a
    .hword 0x2100  @ movs r1, #0
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .incbin "rom/fe7eu.gba", 0x4C3A4, 0x4C

    .global ekrGaugeMain
    .type ekrGaugeMain, %function
    .thumb
    .thumb_func
ekrGaugeMain:  @ 0x0804C3F0 (jp 0x0804CD2C, score 0.7188)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB0C6  @ sub sp, #0x118
    .hword 0x4682  @ mov sl, r0
    .hword 0x2000  @ movs r0, #0
    .hword 0x9036  @ str r0, [sp, #0xd8]
    .word 0xFD8DF7B4  @ bl #0xfffb4b1e
    .hword 0x08C0  @ lsrs r0, r0, #3
    .hword 0x2103  @ movs r1, #3
    .word 0xF8EBF074  @ bl #0x741da
    .hword 0x903A  @ str r0, [sp, #0xe8]
    .hword 0x4650  @ mov r0, sl
    .hword 0x302A  @ adds r0, #0x2a
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD100  @ bne #4
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x4650  @ mov r0, sl
    .hword 0x3029  @ adds r0, #0x29
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x9041  @ str r0, [sp, #0x104]
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD170  @ bne #0xe4
    .hword 0x4651  @ mov r1, sl
    .hword 0x8F48  @ ldrh r0, [r1, #0x3a]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x14C4  @ asrs r4, r0, #0x13
    .hword 0x0160  @ lsls r0, r4, #5
    .hword 0x22D0  @ movs r2, #0xd0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x1887  @ adds r7, r0, r2
    .hword 0x2F00  @ cmp r7, #0
    .hword 0xDA00  @ bge #4
    .hword 0x2700  @ movs r7, #0
    .hword 0x1DE6  @ adds r6, r4, #7
    .hword 0x2E07  @ cmp r6, #7
    .hword 0xDD00  @ ble #4
    .hword 0x2607  @ movs r6, #7
    .hword 0x2007  @ movs r0, #7
    .hword 0x1B80  @ subs r0, r0, r6
    .hword 0x0101  @ lsls r1, r0, #4
    .hword 0x1A09  @ subs r1, r1, r0
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x4689  @ mov sb, r1
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x2300  @ movs r3, #0
    .hword 0x5EC0  @ ldrsh r0, [r0, r3]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDB07  @ blt #0x12
    .hword 0x2802  @ cmp r0, #2
    .hword 0xDC05  @ bgt #0xe
    .hword 0x2400  @ movs r4, #0
    .hword 0x250F  @ movs r5, #0xf
    .hword 0x9537  @ str r5, [sp, #0xdc]
    .hword 0xE004  @ b #0xc
    .hword 0xE02C  @ b #0x5c
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x2008  @ movs r0, #8
    .hword 0x9037  @ str r0, [sp, #0xdc]
    .hword 0x2408  @ movs r4, #8
    .hword 0x493C  @ ldr r1, [pc, #0xf0]
    .hword 0x4688  @ mov r8, r1
    .hword 0x209F  @ movs r0, #0x9f
    .hword 0x9000  @ str r0, [sp]
    .hword 0x4640  @ mov r0, r8
    .hword 0x211E  @ movs r1, #0x1e
    .hword 0x2208  @ movs r2, #8
    .hword 0x2300  @ movs r3, #0
    .word 0xFAFBF01A  @ bl #0x1a5fa
    .hword 0x4652  @ mov r2, sl
    .hword 0x6CD0  @ ldr r0, [r2, #0x4c]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD11A  @ bne #0x38
    .hword 0x4836  @ ldr r0, [pc, #0xd8]
    .hword 0x4448  @ add r0, sb
    .hword 0x007D  @ lsls r5, r7, #1
    .hword 0x0061  @ lsls r1, r4, #1
    .hword 0x4A35  @ ldr r2, [pc, #0xd4]
    .hword 0x4442  @ add r2, r8
    .hword 0x1889  @ adds r1, r1, r2
    .hword 0x186D  @ adds r5, r5, r1
    .hword 0x0434  @ lsls r4, r6, #0x10
    .hword 0x0C24  @ lsrs r4, r4, #0x10
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x9100  @ str r1, [sp]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x220F  @ movs r2, #0xf
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFB70F01A  @ bl #0x1a6e4
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x9000  @ str r0, [sp]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x210F  @ movs r1, #0xf
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x2302  @ movs r3, #2
    .word 0xFAA0F01A  @ bl #0x1a544
    .hword 0x4653  @ mov r3, sl
    .hword 0x6D18  @ ldr r0, [r3, #0x50]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD11B  @ bne #0x3a
    .hword 0x4828  @ ldr r0, [pc, #0xa0]
    .hword 0x4448  @ add r0, sb
    .hword 0x007D  @ lsls r5, r7, #1
    .hword 0x9C37  @ ldr r4, [sp, #0xdc]
    .hword 0x0061  @ lsls r1, r4, #1
    .hword 0x4A25  @ ldr r2, [pc, #0x94]
    .hword 0x4442  @ add r2, r8
    .hword 0x1889  @ adds r1, r1, r2
    .hword 0x186D  @ adds r5, r5, r1
    .hword 0x0434  @ lsls r4, r6, #0x10
    .hword 0x0C24  @ lsrs r4, r4, #0x10
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x9100  @ str r1, [sp]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x2210  @ movs r2, #0x10
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFB50F01A  @ bl #0x1a6a4
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x9000  @ str r0, [sp]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x2303  @ movs r3, #3
    .word 0xFA80F01A  @ bl #0x1a504
    .hword 0x2001  @ movs r0, #1
    .word 0xFD7FF7B4  @ bl #0xfffb4b02
    .hword 0x4B1A  @ ldr r3, [pc, #0x68]
    .hword 0x481A  @ ldr r0, [pc, #0x68]
    .hword 0x2500  @ movs r5, #0
    .hword 0x5F5A  @ ldrsh r2, [r3, r5]
    .hword 0x8804  @ ldrh r4, [r0]
    .hword 0x2600  @ movs r6, #0
    .hword 0x5F81  @ ldrsh r1, [r0, r6]
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x428A  @ cmp r2, r1
    .hword 0xD001  @ beq #6
    .hword 0x2001  @ movs r0, #1
    .hword 0x9036  @ str r0, [sp, #0xd8]
    .hword 0x2202  @ movs r2, #2
    .hword 0x5E99  @ ldrsh r1, [r3, r2]
    .hword 0x886A  @ ldrh r2, [r5, #2]
    .hword 0x2602  @ movs r6, #2
    .hword 0x5FA8  @ ldrsh r0, [r5, r6]
    .hword 0x4281  @ cmp r1, r0
    .hword 0xD001  @ beq #6
    .hword 0x2001  @ movs r0, #1
    .hword 0x9036  @ str r0, [sp, #0xd8]
    .hword 0x801C  @ strh r4, [r3]
    .hword 0x805A  @ strh r2, [r3, #2]
    .hword 0x882F  @ ldrh r7, [r5]
    .hword 0x4810  @ ldr r0, [pc, #0x40]
    .hword 0x8806  @ ldrh r6, [r0]
    .hword 0x8869  @ ldrh r1, [r5, #2]
    .hword 0x4688  @ mov r8, r1
    .hword 0x8840  @ ldrh r0, [r0, #2]
    .hword 0x9035  @ str r0, [sp, #0xd4]
    .hword 0x480E  @ ldr r0, [pc, #0x38]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E80  @ ldrsh r0, [r0, r2]
    .hword 0x2803  @ cmp r0, #3
    .hword 0xD019  @ beq #0x36
    .hword 0x2803  @ cmp r0, #3
    .hword 0xDC27  @ bgt #0x52
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDB25  @ blt #0x4e
    .hword 0x4653  @ mov r3, sl
    .hword 0x2432  @ movs r4, #0x32
    .hword 0x5F1B  @ ldrsh r3, [r3, r4]
    .hword 0x9338  @ str r3, [sp, #0xe0]
    .hword 0xE025  @ b #0x4e
    .hword 0x0000  @ movs r0, r0
    .hword 0x2FA0  @ cmp r7, #0xa0
    .hword 0x0202  @ lsls r2, r0, #8
    .word 0x082BFEE0  @ cdp2 p8, #0xe, c0, c0, c11, #1
    .word 0xFFFFFCC0  @ stc2l p15, c15, [r0], {0xff}
    .word 0x082BFFB4  @ vtbl.8 d0, {d4}, d27
    .hword 0xE0C0  @ b #0x184
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0xE0B8  @ b #0x174
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0xE0BC  @ b #0x17c
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0xE02C  @ b #0x5c
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x4804  @ ldr r0, [pc, #0x10]
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD106  @ bne #0x10
    .hword 0x4652  @ mov r2, sl
    .hword 0x2332  @ movs r3, #0x32
    .hword 0x5ED0  @ ldrsh r0, [r2, r3]
    .hword 0x3038  @ adds r0, #0x38
    .hword 0xE009  @ b #0x16
    .hword 0xE010  @ b #0x24
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x4654  @ mov r4, sl
    .hword 0x2132  @ movs r1, #0x32
    .hword 0x5E60  @ ldrsh r0, [r4, r1]
    .hword 0xE002  @ b #8
    .hword 0x4652  @ mov r2, sl
    .hword 0x2332  @ movs r3, #0x32
    .hword 0x5ED0  @ ldrsh r0, [r2, r3]
    .hword 0x3838  @ subs r0, #0x38
    .hword 0x9038  @ str r0, [sp, #0xe0]
    .hword 0x9C41  @ ldr r4, [sp, #0x104]
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10A  @ bne #0x18
    .hword 0x4650  @ mov r0, sl
    .hword 0x213A  @ movs r1, #0x3a
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x9039  @ str r0, [sp, #0xe4]
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x9A39  @ ldr r2, [sp, #0xe4]
    .hword 0x4002  @ ands r2, r0
    .hword 0x9239  @ str r2, [sp, #0xe4]
    .hword 0xE005  @ b #0xe
    .word 0x0000FFF8  @ vrev64.32 d16, d0
    .hword 0x4653  @ mov r3, sl
    .hword 0x243A  @ movs r4, #0x3a
    .hword 0x5F1B  @ ldrsh r3, [r3, r4]
    .hword 0x9339  @ str r3, [sp, #0xe4]
    .hword 0x1C2C  @ adds r4, r5, #0
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E60  @ ldrsh r0, [r4, r1]
    .hword 0x210A  @ movs r1, #0xa
    .word 0xF800F074  @ bl #0x74004
    .hword 0xAB1A  @ add r3, sp, #0x68
    .hword 0x8018  @ strh r0, [r3]
    .hword 0x8819  @ ldrh r1, [r3]
    .hword 0x008A  @ lsls r2, r1, #2
    .hword 0x1852  @ adds r2, r2, r1
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x8821  @ ldrh r1, [r4]
    .hword 0x1A89  @ subs r1, r1, r2
    .hword 0x8059  @ strh r1, [r3, #2]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4699  @ mov sb, r3
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD101  @ bne #6
    .hword 0x200B  @ movs r0, #0xb
    .hword 0x8018  @ strh r0, [r3]
    .hword 0x2202  @ movs r2, #2
    .hword 0x5EA0  @ ldrsh r0, [r4, r2]
    .hword 0x210A  @ movs r1, #0xa
    .word 0xFFECF073  @ bl #0x73fdc
    .hword 0x464B  @ mov r3, sb
    .hword 0x8098  @ strh r0, [r3, #4]
    .hword 0x8899  @ ldrh r1, [r3, #4]
    .hword 0x008A  @ lsls r2, r1, #2
    .hword 0x1852  @ adds r2, r2, r1
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x8861  @ ldrh r1, [r4, #2]
    .hword 0x1A89  @ subs r1, r1, r2
    .hword 0x80D9  @ strh r1, [r3, #6]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD101  @ bne #6
    .hword 0x200B  @ movs r0, #0xb
    .hword 0x8098  @ strh r0, [r3, #4]
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E60  @ ldrsh r0, [r4, r1]
    .hword 0x2850  @ cmp r0, #0x50
    .hword 0xDD03  @ ble #0xa
    .hword 0x200C  @ movs r0, #0xc
    .hword 0x464A  @ mov r2, sb
    .hword 0x8010  @ strh r0, [r2]
    .hword 0x8050  @ strh r0, [r2, #2]
    .hword 0x2302  @ movs r3, #2
    .hword 0x5EE8  @ ldrsh r0, [r5, r3]
    .hword 0x2850  @ cmp r0, #0x50
    .hword 0xDD03  @ ble #0xa
    .hword 0x200C  @ movs r0, #0xc
    .hword 0x464C  @ mov r4, sb
    .hword 0x80A0  @ strh r0, [r4, #4]
    .hword 0x80E0  @ strh r0, [r4, #6]
    .hword 0x9D38  @ ldr r5, [sp, #0xe0]
    .hword 0x3509  @ adds r5, #9
    .hword 0x953C  @ str r5, [sp, #0xf0]
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x3091  @ adds r0, #0x91
    .hword 0x9044  @ str r0, [sp, #0x110]
    .hword 0x9938  @ ldr r1, [sp, #0xe0]
    .hword 0x3181  @ adds r1, #0x81
    .hword 0x9143  @ str r1, [sp, #0x10c]
    .hword 0x043A  @ lsls r2, r7, #0x10
    .hword 0x923D  @ str r2, [sp, #0xf4]
    .hword 0x0436  @ lsls r6, r6, #0x10
    .hword 0x963E  @ str r6, [sp, #0xf8]
    .hword 0x9B38  @ ldr r3, [sp, #0xe0]
    .hword 0x331D  @ adds r3, #0x1d
    .hword 0x9342  @ str r3, [sp, #0x108]
    .hword 0x4644  @ mov r4, r8
    .hword 0x0424  @ lsls r4, r4, #0x10
    .hword 0x943F  @ str r4, [sp, #0xfc]
    .hword 0x9D35  @ ldr r5, [sp, #0xd4]
    .hword 0x042D  @ lsls r5, r5, #0x10
    .hword 0x9540  @ str r5, [sp, #0x100]
    .hword 0x9E38  @ ldr r6, [sp, #0xe0]
    .hword 0x3695  @ adds r6, #0x95
    .hword 0x9645  @ str r6, [sp, #0x114]
    .hword 0x9836  @ ldr r0, [sp, #0xd8]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD12A  @ bne #0x58
    .hword 0xA834  @ add r0, sp, #0xd0
    .hword 0x2100  @ movs r1, #0
    .hword 0x6001  @ str r1, [r0]
    .hword 0x4922  @ ldr r1, [pc, #0x88]
    .hword 0x4A22  @ ldr r2, [pc, #0x88]
    .word 0xFFA7F073  @ bl #0x73f52
    .hword 0x2000  @ movs r0, #0
    .hword 0x1C41  @ adds r1, r0, #1
    .hword 0x4688  @ mov r8, r1
    .hword 0x0185  @ lsls r5, r0, #6
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x464A  @ mov r2, sb
    .hword 0x1884  @ adds r4, r0, r2
    .hword 0x2601  @ movs r6, #1
    .hword 0x8820  @ ldrh r0, [r4]
    .hword 0x0140  @ lsls r0, r0, #5
    .hword 0x491D  @ ldr r1, [pc, #0x74]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4F1A  @ ldr r7, [pc, #0x68]
    .hword 0x19E9  @ adds r1, r5, r7
    .hword 0x2210  @ movs r2, #0x10
    .word 0xFF98F073  @ bl #0x73f34
    .hword 0x3520  @ adds r5, #0x20
    .hword 0x3402  @ adds r4, #2
    .hword 0x3E01  @ subs r6, #1
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xDAF1  @ bge #0xffffffe6
    .hword 0x4640  @ mov r0, r8
    .hword 0x2801  @ cmp r0, #1
    .hword 0xDDE7  @ ble #0xffffffd2
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x2240  @ movs r2, #0x40
    .word 0xFCDFF7B6  @ bl #0xfffb69c2
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x3040  @ adds r0, #0x40
    .hword 0x4914  @ ldr r1, [pc, #0x50]
    .hword 0x2240  @ movs r2, #0x40
    .word 0xFCD9F7B6  @ bl #0xfffb69b6
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x2400  @ movs r4, #0
    .hword 0x4912  @ ldr r1, [pc, #0x48]
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x4653  @ mov r3, sl
    .hword 0x6C58  @ ldr r0, [r3, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0xAD3C  @ add r5, sp, #0xf0
    .hword 0x882D  @ ldrh r5, [r5]
    .hword 0x8045  @ strh r5, [r0, #2]
    .hword 0xAE44  @ add r6, sp, #0x110
    .hword 0x8836  @ ldrh r6, [r6]
    .hword 0x8086  @ strh r6, [r0, #4]
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .hword 0x2000  @ movs r0, #0
    .word 0xFEA9F000  @ bl #0xd56
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x1403  @ asrs r3, r0, #0x10
    .hword 0x2B01  @ cmp r3, #1
    .hword 0xD012  @ beq #0x28
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0xE023  @ b #0x4a
    .hword 0x0000  @ movs r0, r0
    .hword 0x6DC8  @ ldr r0, [r1, #0x5c]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x0020  @ movs r0, r4
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x02B4  @ lsls r4, r6, #0xa
    .hword 0x082C  @ lsrs r4, r5, #0x20
    .hword 0x39C0  @ subs r1, #0xc0
    .hword 0x0601  @ lsls r1, r0, #0x18
    .hword 0x3DC0  @ subs r5, #0xc0
    .hword 0x0601  @ lsls r1, r0, #0x18
    .hword 0x51CE  @ str r6, [r1, r7]
    .hword 0x0000  @ movs r0, r0
    .hword 0x6200  @ str r0, [r0, #0x20]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0xA91C  @ add r1, sp, #0x70
    .hword 0x9111  @ str r1, [sp, #0x44]
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x9009  @ str r0, [sp, #0x24]
    .hword 0xAA02  @ add r2, sp, #8
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x8840  @ ldrh r0, [r0, #2]
    .hword 0x3808  @ subs r0, #8
    .hword 0x8050  @ strh r0, [r2, #2]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x8880  @ ldrh r0, [r0, #4]
    .hword 0x3808  @ subs r0, #8
    .hword 0x8090  @ strh r0, [r2, #4]
    .hword 0x4815  @ ldr r0, [pc, #0x54]
    .hword 0x2280  @ movs r2, #0x80
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x9300  @ str r3, [sp]
    .hword 0x2380  @ movs r3, #0x80
    .word 0xFEDDF01A  @ bl #0x1adbe
    .hword 0x4651  @ mov r1, sl
    .hword 0x6CC8  @ ldr r0, [r1, #0x4c]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD102  @ bne #8
    .hword 0xA802  @ add r0, sp, #8
    .word 0xF828F7BA  @ bl #0xfffba054
    .hword 0x2400  @ movs r4, #0
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x490E  @ ldr r1, [pc, #0x38]
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x4653  @ mov r3, sl
    .hword 0x6C58  @ ldr r0, [r3, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0xAD43  @ add r5, sp, #0x10c
    .hword 0x882D  @ ldrh r5, [r5]
    .hword 0x8045  @ strh r5, [r0, #2]
    .hword 0xAE44  @ add r6, sp, #0x110
    .hword 0x8836  @ ldrh r6, [r6]
    .hword 0x8086  @ strh r6, [r0, #4]
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .hword 0x2001  @ movs r0, #1
    .word 0xFE61F000  @ bl #0xcc6
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x1403  @ asrs r3, r0, #0x10
    .hword 0x2B01  @ cmp r3, #1
    .hword 0xD008  @ beq #0x14
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0xE019  @ b #0x36
    .hword 0x0000  @ movs r0, r0
    .hword 0x6200  @ str r0, [r0, #0x20]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x61EE  @ str r6, [r5, #0x1c]
    .hword 0x0000  @ movs r0, r0
    .hword 0xA91C  @ add r1, sp, #0x70
    .hword 0x9111  @ str r1, [sp, #0x44]
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x9009  @ str r0, [sp, #0x24]
    .hword 0xAA02  @ add r2, sp, #8
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x8840  @ ldrh r0, [r0, #2]
    .hword 0x3808  @ subs r0, #8
    .hword 0x8050  @ strh r0, [r2, #2]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x8880  @ ldrh r0, [r0, #4]
    .hword 0x3808  @ subs r0, #8
    .hword 0x8090  @ strh r0, [r2, #4]
    .hword 0x4841  @ ldr r0, [pc, #0x104]
    .hword 0x2280  @ movs r2, #0x80
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x9300  @ str r3, [sp]
    .hword 0x2380  @ movs r3, #0x80
    .word 0xFE9FF01A  @ bl #0x1ad42
    .hword 0x4651  @ mov r1, sl
    .hword 0x6D08  @ ldr r0, [r1, #0x50]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD102  @ bne #8
    .hword 0xA802  @ add r0, sp, #8
    .word 0xFFEAF7B9  @ bl #0xfffb9fd8
    .hword 0x9A3D  @ ldr r2, [sp, #0xf4]
    .hword 0x4B3B  @ ldr r3, [pc, #0xec]
    .hword 0x18D1  @ adds r1, r2, r3
    .hword 0x9C3E  @ ldr r4, [sp, #0xf8]
    .hword 0x18E0  @ adds r0, r4, r3
    .hword 0x0C05  @ lsrs r5, r0, #0x10
    .hword 0x0C17  @ lsrs r7, r2, #0x10
    .hword 0x0C24  @ lsrs r4, r4, #0x10
    .hword 0x46A0  @ mov r8, r4
    .hword 0x0C0E  @ lsrs r6, r1, #0x10
    .hword 0x1409  @ asrs r1, r1, #0x10
    .hword 0x2928  @ cmp r1, #0x28
    .hword 0xDD00  @ ble #4
    .hword 0x2628  @ movs r6, #0x28
    .hword 0x0428  @ lsls r0, r5, #0x10
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x2828  @ cmp r0, #0x28
    .hword 0xDD00  @ ble #4

    .incbin "rom/fe7eu.gba", 0x4C800, 0x14

    .global sub_804D13C
    .type sub_804D13C, %function
    .thumb
    .thumb_func
sub_804D13C:  @ 0x0804C814 (jp 0x0804D13C, score 0.7812)
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x2828  @ cmp r0, #0x28
    .hword 0xDD00  @ ble #4
    .hword 0x2728  @ movs r7, #0x28
    .hword 0x4641  @ mov r1, r8
    .hword 0x0408  @ lsls r0, r1, #0x10
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x2828  @ cmp r0, #0x28
    .hword 0xDD01  @ ble #6
    .hword 0x2228  @ movs r2, #0x28
    .hword 0x4690  @ mov r8, r2
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x2300  @ movs r3, #0
    .hword 0x21B0  @ movs r1, #0xb0
    .hword 0x0209  @ lsls r1, r1, #8
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x4654  @ mov r4, sl
    .hword 0x6C60  @ ldr r0, [r4, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x9309  @ str r3, [sp, #0x24]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0xA942  @ add r1, sp, #0x108
    .hword 0x8809  @ ldrh r1, [r1]
    .hword 0x8041  @ strh r1, [r0, #2]
    .hword 0x4821  @ ldr r0, [pc, #0x84]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0x6CE2  @ ldr r2, [r4, #0x4c]
    .hword 0x4691  @ mov sb, r2
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD155  @ bne #0xae
    .hword 0x0428  @ lsls r0, r5, #0x10
    .hword 0x1402  @ asrs r2, r0, #0x10
    .hword 0xAC14  @ add r4, sp, #0x50
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD01D  @ beq #0x3e
    .hword 0x0431  @ lsls r1, r6, #0x10
    .hword 0x1409  @ asrs r1, r1, #0x10
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA80F01A  @ bl #0x1a504
    .hword 0x9B36  @ ldr r3, [sp, #0xd8]
    .hword 0x2B01  @ cmp r3, #1
    .hword 0xD103  @ bne #0xa
    .hword 0x4919  @ ldr r1, [pc, #0x64]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFB63F7FF  @ bl #0xfffff6ca
    .hword 0xA902  @ add r1, sp, #8
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x308E  @ adds r0, #0x8e
    .hword 0x8088  @ strh r0, [r1, #4]
    .hword 0x1C0A  @ adds r2, r1, #0
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8901  @ ldrh r1, [r0, #8]
    .hword 0x20FC  @ movs r0, #0xfc
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x4008  @ ands r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x8108  @ strh r0, [r1, #8]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x464E  @ mov r6, sb
    .hword 0x8186  @ strh r6, [r0, #0xc]
    .word 0xFF8BF7B9  @ bl #0xfffb9f1a
    .hword 0x0439  @ lsls r1, r7, #0x10
    .hword 0x1409  @ asrs r1, r1, #0x10
    .hword 0x4640  @ mov r0, r8
    .hword 0x0402  @ lsls r2, r0, #0x10
    .hword 0x1412  @ asrs r2, r2, #0x10
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA5FF01A  @ bl #0x1a4c2
    .hword 0x9936  @ ldr r1, [sp, #0xd8]
    .hword 0x2901  @ cmp r1, #1
    .hword 0xD103  @ bne #0xa
    .hword 0x4909  @ ldr r1, [pc, #0x24]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFB42F7FF  @ bl #0xfffff688
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD00F  @ beq #0x22
    .hword 0xA902  @ add r1, sp, #8
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x3095  @ adds r0, #0x95
    .hword 0x8088  @ strh r0, [r1, #4]
    .hword 0xE00E  @ b #0x20
    .hword 0x0000  @ movs r0, r0
    .hword 0x6200  @ str r0, [r0, #0x20]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x0000  @ movs r0, r0
    .word 0x61D0FFD8  @ vsra.u64 q11, q0, #0x28
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x6E48  @ ldr r0, [r1, #0x64]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7248  @ strb r0, [r1, #9]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0xA802  @ add r0, sp, #8
    .hword 0xAA44  @ add r2, sp, #0x110
    .hword 0x8812  @ ldrh r2, [r2]
    .hword 0x8082  @ strh r2, [r0, #4]
    .hword 0xAA02  @ add r2, sp, #8
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x8901  @ ldrh r1, [r0, #8]
    .hword 0x20FC  @ movs r0, #0xfc
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x4008  @ ands r0, r1
    .hword 0x2300  @ movs r3, #0
    .hword 0x2120  @ movs r1, #0x20
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x8183  @ strh r3, [r0, #0xc]
    .word 0xFF58F7B9  @ bl #0xfffb9eb4
    .hword 0x9B3F  @ ldr r3, [sp, #0xfc]
    .hword 0x4C3D  @ ldr r4, [pc, #0xf4]
    .hword 0x1919  @ adds r1, r3, r4
    .hword 0x9D40  @ ldr r5, [sp, #0x100]
    .hword 0x1928  @ adds r0, r5, r4
    .hword 0x0C05  @ lsrs r5, r0, #0x10
    .hword 0x0C1F  @ lsrs r7, r3, #0x10
    .hword 0x9E40  @ ldr r6, [sp, #0x100]
    .hword 0x0C36  @ lsrs r6, r6, #0x10
    .hword 0x46B0  @ mov r8, r6
    .hword 0x0C0E  @ lsrs r6, r1, #0x10
    .hword 0x1409  @ asrs r1, r1, #0x10
    .hword 0x2928  @ cmp r1, #0x28
    .hword 0xDD00  @ ble #4
    .hword 0x2628  @ movs r6, #0x28
    .hword 0x0428  @ lsls r0, r5, #0x10
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x2828  @ cmp r0, #0x28
    .hword 0xDD00  @ ble #4
    .hword 0x2528  @ movs r5, #0x28
    .hword 0x0430  @ lsls r0, r6, #0x10
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA00  @ bge #4
    .hword 0x2600  @ movs r6, #0
    .hword 0x0428  @ lsls r0, r5, #0x10
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA00  @ bge #4
    .hword 0x2500  @ movs r5, #0
    .hword 0x0438  @ lsls r0, r7, #0x10
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x2828  @ cmp r0, #0x28
    .hword 0xDD00  @ ble #4
    .hword 0x2728  @ movs r7, #0x28
    .hword 0x4641  @ mov r1, r8
    .hword 0x0408  @ lsls r0, r1, #0x10
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x2828  @ cmp r0, #0x28
    .hword 0xDD01  @ ble #6
    .hword 0x2228  @ movs r2, #0x28
    .hword 0x4690  @ mov r8, r2
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x2300  @ movs r3, #0
    .hword 0x4699  @ mov sb, r3
    .hword 0x21C0  @ movs r1, #0xc0
    .hword 0x0209  @ lsls r1, r1, #8
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x4654  @ mov r4, sl
    .hword 0x6C60  @ ldr r0, [r4, #0x44]
    .hword 0xAC3B  @ add r4, sp, #0xec
    .hword 0x8023  @ strh r3, [r4]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x4648  @ mov r0, sb
    .hword 0x9009  @ str r0, [sp, #0x24]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0xA945  @ add r1, sp, #0x114
    .hword 0x8809  @ ldrh r1, [r1]
    .hword 0x8041  @ strh r1, [r0, #2]
    .hword 0x4821  @ ldr r0, [pc, #0x84]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0x4652  @ mov r2, sl
    .hword 0x6D12  @ ldr r2, [r2, #0x50]
    .hword 0x4691  @ mov sb, r2
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD153  @ bne #0xaa
    .hword 0x0428  @ lsls r0, r5, #0x10
    .hword 0x1402  @ asrs r2, r0, #0x10
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0xAC14  @ add r4, sp, #0x50
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD01D  @ beq #0x3e
    .hword 0x0431  @ lsls r1, r6, #0x10
    .hword 0x1409  @ asrs r1, r1, #0x10
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF9E7F01A  @ bl #0x1a3d2
    .hword 0x9B36  @ ldr r3, [sp, #0xd8]
    .hword 0x2B01  @ cmp r3, #1
    .hword 0xD103  @ bne #0xa
    .hword 0x4917  @ ldr r1, [pc, #0x5c]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFACAF7FF  @ bl #0xfffff598
    .hword 0xA902  @ add r1, sp, #8
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x308E  @ adds r0, #0x8e
    .hword 0x8088  @ strh r0, [r1, #4]
    .hword 0x1C0A  @ adds r2, r1, #0
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8901  @ ldrh r1, [r0, #8]
    .hword 0x20FC  @ movs r0, #0xfc
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x4008  @ ands r0, r1
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x464E  @ mov r6, sb
    .hword 0x8186  @ strh r6, [r0, #0xc]
    .word 0xFEF2F7B9  @ bl #0xfffb9de8
    .hword 0x0439  @ lsls r1, r7, #0x10
    .hword 0x1409  @ asrs r1, r1, #0x10
    .hword 0x4640  @ mov r0, r8
    .hword 0x0402  @ lsls r2, r0, #0x10
    .hword 0x1412  @ asrs r2, r2, #0x10
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF9C6F01A  @ bl #0x1a390
    .hword 0x9936  @ ldr r1, [sp, #0xd8]
    .hword 0x2901  @ cmp r1, #1
    .hword 0xD103  @ bne #0xa
    .hword 0x4908  @ ldr r1, [pc, #0x20]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFAA9F7FF  @ bl #0xfffff556
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD00C  @ beq #0x1c
    .hword 0xA902  @ add r1, sp, #8
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x3095  @ adds r0, #0x95
    .hword 0x8088  @ strh r0, [r1, #4]
    .hword 0xE00B  @ b #0x1a
    .hword 0x0000  @ movs r0, r0
    .word 0x61D0FFD8  @ vsra.u64 q11, q0, #0x28
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x7048  @ strb r0, [r1, #1]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7448  @ strb r0, [r1, #0x11]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0xA802  @ add r0, sp, #8
    .hword 0xAA44  @ add r2, sp, #0x110
    .hword 0x8812  @ ldrh r2, [r2]
    .hword 0x8082  @ strh r2, [r0, #4]
    .hword 0xAA02  @ add r2, sp, #8
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x8901  @ ldrh r1, [r0, #8]
    .hword 0x20FC  @ movs r0, #0xfc
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x4008  @ ands r0, r1
    .hword 0x2300  @ movs r3, #0
    .hword 0x2130  @ movs r1, #0x30
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x8183  @ strh r3, [r0, #0xc]
    .word 0xFEC2F7B9  @ bl #0xfffb9d88
    .hword 0x9B36  @ ldr r3, [sp, #0xd8]
    .hword 0x2B01  @ cmp r3, #1
    .hword 0xD105  @ bne #0xe
    .hword 0x486B  @ ldr r0, [pc, #0x1ac]
    .hword 0x496B  @ ldr r1, [pc, #0x1ac]
    .hword 0x2280  @ movs r2, #0x80
    .hword 0x0112  @ lsls r2, r2, #4
    .word 0xFB23F7B6  @ bl #0xfffb664a
    .hword 0x4655  @ mov r5, sl
    .hword 0x6CEC  @ ldr r4, [r5, #0x4c]
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD129  @ bne #0x56
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0x4867  @ ldr r0, [pc, #0x19c]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x4967  @ ldr r1, [pc, #0x19c]
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x6C68  @ ldr r0, [r5, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x9838  @ ldr r0, [sp, #0xe0]
    .hword 0x300F  @ adds r0, #0xf
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x3070  @ adds r0, #0x70
    .hword 0x8088  @ strh r0, [r1, #4]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .word 0xFEA0F7B9  @ bl #0xfffb9d44
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0x485F  @ ldr r0, [pc, #0x17c]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x495E  @ ldr r1, [pc, #0x178]
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x6C68  @ ldr r0, [r5, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x9838  @ ldr r0, [sp, #0xe0]
    .hword 0x3065  @ adds r0, #0x65
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x3078  @ adds r0, #0x78
    .hword 0x8088  @ strh r0, [r1, #4]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .word 0xFE8BF7B9  @ bl #0xfffb9d1a
    .hword 0x4656  @ mov r6, sl
    .hword 0x6D34  @ ldr r4, [r6, #0x50]
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD129  @ bne #0x56
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0x4850  @ ldr r0, [pc, #0x140]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x4953  @ ldr r1, [pc, #0x14c]
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x6C70  @ ldr r0, [r6, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x9838  @ ldr r0, [sp, #0xe0]
    .hword 0x30D7  @ adds r0, #0xd7
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x3070  @ adds r0, #0x70
    .hword 0x8088  @ strh r0, [r1, #4]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .word 0xFE72F7B9  @ bl #0xfffb9ce8
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0x484B  @ ldr r0, [pc, #0x12c]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x494A  @ ldr r1, [pc, #0x128]
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x6C70  @ ldr r0, [r6, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x9838  @ ldr r0, [sp, #0xe0]
    .hword 0x3087  @ adds r0, #0x87
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x9839  @ ldr r0, [sp, #0xe4]
    .hword 0x3078  @ adds r0, #0x78
    .hword 0x8088  @ strh r0, [r1, #4]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .word 0xFE5DF7B9  @ bl #0xfffb9cbe
    .hword 0x4650  @ mov r0, sl
    .hword 0x6CC4  @ ldr r4, [r0, #0x4c]
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD131  @ bne #0x66
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0x4940  @ ldr r1, [pc, #0x100]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E88  @ ldrsh r0, [r1, r2]
    .hword 0x9D39  @ ldr r5, [sp, #0xe4]
    .hword 0x357A  @ adds r5, #0x7a
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD016  @ beq #0x30
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x9A3A  @ ldr r2, [sp, #0xe8]
    .word 0xFC46F7FF  @ bl #0xfffff890
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x21E5  @ movs r1, #0xe5
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x4656  @ mov r6, sl
    .hword 0x6C70  @ ldr r0, [r6, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x9838  @ ldr r0, [sp, #0xe0]
    .hword 0x3035  @ adds r0, #0x35
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8085  @ strh r5, [r0, #4]
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .word 0xFE3AF7B9  @ bl #0xfffb9c78
    .hword 0x4832  @ ldr r0, [pc, #0xc8]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x4932  @ ldr r1, [pc, #0xc8]
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x4653  @ mov r3, sl
    .hword 0x6C58  @ ldr r0, [r3, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x9838  @ ldr r0, [sp, #0xe0]
    .hword 0x302B  @ adds r0, #0x2b
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8085  @ strh r5, [r0, #4]
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .word 0xFE27F7B9  @ bl #0xfffb9c52
    .hword 0x4655  @ mov r5, sl
    .hword 0x6D2C  @ ldr r4, [r5, #0x50]
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD131  @ bne #0x66
    .hword 0x9409  @ str r4, [sp, #0x24]
    .hword 0x4925  @ ldr r1, [pc, #0x94]
    .hword 0x2602  @ movs r6, #2
    .hword 0x5F88  @ ldrsh r0, [r1, r6]
    .hword 0x9D39  @ ldr r5, [sp, #0xe4]
    .hword 0x357A  @ adds r5, #0x7a
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD016  @ beq #0x30
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x9A3A  @ ldr r2, [sp, #0xe8]
    .word 0xFC10F7FF  @ bl #0xfffff824
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x21E5  @ movs r1, #0xe5
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x4653  @ mov r3, sl
    .hword 0x6C58  @ ldr r0, [r3, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x9838  @ ldr r0, [sp, #0xe0]
    .hword 0x3084  @ adds r0, #0x84
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8085  @ strh r5, [r0, #4]
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .word 0xFE04F7B9  @ bl #0xfffb9c0c
    .hword 0x4817  @ ldr r0, [pc, #0x5c]
    .hword 0x9011  @ str r0, [sp, #0x44]
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x4918  @ ldr r1, [pc, #0x60]
    .hword 0x8101  @ strh r1, [r0, #8]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x4656  @ mov r6, sl
    .hword 0x6C70  @ ldr r0, [r6, #0x44]
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8110  @ strh r0, [r2, #8]
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x9838  @ ldr r0, [sp, #0xe0]
    .hword 0x307A  @ adds r0, #0x7a
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x8085  @ strh r5, [r0, #4]
    .hword 0x8184  @ strh r4, [r0, #0xc]
    .word 0xFDF1F7B9  @ bl #0xfffb9be6
    .hword 0xB046  @ add sp, #0x118
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x6E48  @ ldr r0, [r1, #0x64]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x3000  @ adds r0, #0
    .hword 0x0601  @ lsls r1, r0, #0x18
    .hword 0x6218  @ str r0, [r3, #0x20]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x51D0  @ str r0, [r2, r7]
    .hword 0x0000  @ movs r0, r0
    .hword 0x6248  @ str r0, [r1, #0x24]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x51C0  @ str r0, [r0, r7]
    .hword 0x0000  @ movs r0, r0
    .hword 0x61F0  @ str r0, [r6, #0x1c]
    .hword 0x0000  @ movs r0, r0
    .hword 0x6284  @ str r4, [r0, #0x28]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x61C0  @ str r0, [r0, #0x1c]
    .hword 0x0000  @ movs r0, r0
    .hword 0xE0E0  @ b #0x1c4
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x62C0  @ str r0, [r0, #0x2c]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0xD1DC  @ bne #0xffffffbc
    .hword 0x0000  @ movs r0, r0
    .hword 0xE1DE  @ b #0x3c0
    .hword 0x0000  @ movs r0, r0

    .global NewEkrDispUP
    .type NewEkrDispUP, %function
    .thumb
    .thumb_func
NewEkrDispUP:  @ 0x0804CC14 (jp 0x0804D540, score 0.7895)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4C09  @ ldr r4, [pc, #0x24]
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x2105  @ movs r1, #5
    .word 0xFC40F7B7  @ bl #0xfffb7884
    .hword 0x6020  @ str r0, [r4]
    .hword 0x2000  @ movs r0, #0
    .hword 0x2100  @ movs r1, #0
    .word 0xF837F000  @ bl #0x72
    .word 0xF815F000  @ bl #0x2e
    .word 0xF85FF000  @ bl #0xc2
    .word 0xF84DF000  @ bl #0x9e
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x6368  @ str r0, [r5, #0x34]
    .hword 0x08C9  @ lsrs r1, r1, #3

    .global EndEkrDispUP
    .type EndEkrDispUP, %function
    .thumb
    .thumb_func
EndEkrDispUP:  @ 0x0804CC44 (jp 0x0804D570, score 0.7778)
    .hword 0xB500  @ push {lr}
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x6800  @ ldr r0, [r0]
    .word 0xFCA1F7B7  @ bl #0xfffb7946
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrDispUP_0804D584
    .type EkrDispUP_0804D584, %function
    .thumb
    .thumb_func
EkrDispUP_0804D584:  @ 0x0804CC58 (jp 0x0804D584, score 0.75)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2000  @ movs r0, #0
    .hword 0x64C8  @ str r0, [r1, #0x4c]
    .hword 0x6508  @ str r0, [r1, #0x50]
    .hword 0x4770  @ bx lr
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrDispUP_0804D594
    .type EkrDispUP_0804D594, %function
    .thumb
    .thumb_func
EkrDispUP_0804D594:  @ 0x0804CC68 (jp 0x0804D594, score 0.75)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .hword 0x64C8  @ str r0, [r1, #0x4c]
    .hword 0x6508  @ str r0, [r1, #0x50]
    .hword 0x4770  @ bx lr
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrDispUP_0804D5A4
    .type EkrDispUP_0804D5A4, %function
    .thumb
    .thumb_func
EkrDispUP_0804D5A4:  @ 0x0804CC78 (jp 0x0804D5A4, score 0.75)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .hword 0x64C8  @ str r0, [r1, #0x4c]
    .hword 0x4770  @ bx lr
    .hword 0x0000  @ movs r0, r0
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrDispUP_0804D5B4
    .type EkrDispUP_0804D5B4, %function
    .thumb
    .thumb_func
EkrDispUP_0804D5B4:  @ 0x0804CC88 (jp 0x0804D5B4, score 0.75)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .hword 0x6508  @ str r0, [r1, #0x50]
    .hword 0x4770  @ bx lr
    .hword 0x0000  @ movs r0, r0
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrDispUP_SetPositionUnsync
    .type EkrDispUP_SetPositionUnsync, %function
    .thumb
    .thumb_func
EkrDispUP_SetPositionUnsync:  @ 0x0804CC98 (jp 0x0804D5C4, score 0.8)
    .hword 0x4A03  @ ldr r2, [pc, #0xc]
    .hword 0x6812  @ ldr r2, [r2]
    .hword 0x2300  @ movs r3, #0
    .hword 0x8650  @ strh r0, [r2, #0x32]
    .hword 0x8751  @ strh r1, [r2, #0x3a]
    .hword 0x3229  @ adds r2, #0x29
    .hword 0x7013  @ strb r3, [r2]
    .hword 0x4770  @ bx lr
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global EkrDispUP_SetPositionSync
    .type EkrDispUP_SetPositionSync, %function
    .thumb
    .thumb_func
EkrDispUP_SetPositionSync:  @ 0x0804CCAC (jp 0x0804D5D8, score 0.8)
    .hword 0x4A03  @ ldr r2, [pc, #0xc]
    .hword 0x6812  @ ldr r2, [r2]
    .hword 0x8650  @ strh r0, [r2, #0x32]
    .hword 0x8751  @ strh r1, [r2, #0x3a]
    .hword 0x3229  @ adds r2, #0x29
    .hword 0x2001  @ movs r0, #1
    .hword 0x7010  @ strb r0, [r2]
    .hword 0x4770  @ bx lr
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global SyncEkrDispUP
    .type SyncEkrDispUP, %function
    .thumb
    .thumb_func
SyncEkrDispUP:  @ 0x0804CCC0 (jp 0x0804D5EC, score 0.75)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x3029  @ adds r0, #0x29
    .hword 0x2101  @ movs r1, #1
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global UnsyncEkrDispUP
    .type UnsyncEkrDispUP, %function
    .thumb
    .thumb_func
UnsyncEkrDispUP:  @ 0x0804CCD0 (jp 0x0804D5FC, score 0.75)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x3029  @ adds r0, #0x29
    .hword 0x2100  @ movs r1, #0
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global AsyncEkrDispUP
    .type AsyncEkrDispUP, %function
    .thumb
    .thumb_func
AsyncEkrDispUP:  @ 0x0804CCE0 (jp 0x0804D60C, score 0.75)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x302A  @ adds r0, #0x2a
    .hword 0x2101  @ movs r1, #1
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global UnAsyncEkrDispUP
    .type UnAsyncEkrDispUP, %function
    .thumb
    .thumb_func
UnAsyncEkrDispUP:  @ 0x0804CCF0 (jp 0x0804D61C, score 0.75)
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x302A  @ adds r0, #0x2a
    .hword 0x2100  @ movs r1, #0
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x006C  @ lsls r4, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global ekrDispUPMain
    .type ekrDispUPMain, %function
    .thumb
    .thumb_func
ekrDispUPMain:  @ 0x0804CD00 (jp 0x0804D62C, score 0.7812)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB082  @ sub sp, #8
    .hword 0x1C07  @ adds r7, r0, #0
    .hword 0x302A  @ adds r0, #0x2a
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD06C  @ beq #0xdc
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x3029  @ adds r0, #0x29
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD167  @ bne #0xd2
    .hword 0x8F78  @ ldrh r0, [r7, #0x3a]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x14C0  @ asrs r0, r0, #0x13
    .hword 0x0141  @ lsls r1, r0, #5
    .hword 0x4688  @ mov r8, r1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDA01  @ bge #6
    .hword 0x2200  @ movs r2, #0
    .hword 0x4690  @ mov r8, r2
    .hword 0x1DC6  @ adds r6, r0, #7
    .hword 0x2E06  @ cmp r6, #6
    .hword 0xDD00  @ ble #4
    .hword 0x2606  @ movs r6, #6
    .hword 0x2006  @ movs r0, #6
    .hword 0x1B80  @ subs r0, r0, r6
    .hword 0x0101  @ lsls r1, r0, #4
    .hword 0x1A09  @ subs r1, r1, r0
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x468A  @ mov sl, r1
    .hword 0x4804  @ ldr r0, [pc, #0x10]
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDB05  @ blt #0xe
    .hword 0x2802  @ cmp r0, #2
    .hword 0xDC03  @ bgt #0xa
    .hword 0x2400  @ movs r4, #0
    .hword 0xE002  @ b #8
    .hword 0xE02C  @ b #0x5c
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x240F  @ movs r4, #0xf
    .hword 0x4A28  @ ldr r2, [pc, #0xa0]
    .hword 0x4691  @ mov sb, r2
    .hword 0x209F  @ movs r0, #0x9f
    .hword 0x9000  @ str r0, [sp]
    .hword 0x4648  @ mov r0, sb
    .hword 0x211E  @ movs r1, #0x1e
    .hword 0x2207  @ movs r2, #7
    .hword 0x2300  @ movs r3, #0
    .word 0xFE85F019  @ bl #0x19d0e
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xDD39  @ ble #0x76
    .hword 0x6CF8  @ ldr r0, [r7, #0x4c]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD119  @ bne #0x36
    .hword 0x4821  @ ldr r0, [pc, #0x84]
    .hword 0x4450  @ add r0, sl
    .hword 0x4641  @ mov r1, r8
    .hword 0x004D  @ lsls r5, r1, #1
    .hword 0x0061  @ lsls r1, r4, #1
    .hword 0x4449  @ add r1, sb
    .hword 0x186D  @ adds r5, r5, r1
    .hword 0x0434  @ lsls r4, r6, #0x10
    .hword 0x0C24  @ lsrs r4, r4, #0x10
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x9100  @ str r1, [sp]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x220F  @ movs r2, #0xf
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFEFAF019  @ bl #0x19df8
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x9000  @ str r0, [sp]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x210F  @ movs r1, #0xf
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x2302  @ movs r3, #2
    .word 0xFE2AF019  @ bl #0x19c58
    .hword 0x6D38  @ ldr r0, [r7, #0x50]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD119  @ bne #0x36
    .hword 0x4814  @ ldr r0, [pc, #0x50]
    .hword 0x4450  @ add r0, sl
    .hword 0x4642  @ mov r2, r8
    .hword 0x0055  @ lsls r5, r2, #1
    .hword 0x220F  @ movs r2, #0xf
    .hword 0x0051  @ lsls r1, r2, #1
    .hword 0x4449  @ add r1, sb
    .hword 0x186D  @ adds r5, r5, r1
    .hword 0x0434  @ lsls r4, r6, #0x10
    .hword 0x0C24  @ lsrs r4, r4, #0x10
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x9100  @ str r1, [sp]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFEDDF019  @ bl #0x19dbe
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x9000  @ str r0, [sp]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x210F  @ movs r1, #0xf
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x2303  @ movs r3, #3
    .word 0xFE0DF019  @ bl #0x19c1e
    .hword 0x2001  @ movs r0, #1
    .word 0xF90CF7B4  @ bl #0xfffb421c
    .hword 0xB002  @ add sp, #8
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x2C60  @ cmp r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8
    .word 0x082BFD78  @ ldc2l p8, c0, [r8, #-0xac]!
    .word 0x082BFE2C  @ cdp2 p8, #2, c0, c12, c11, #1

    .global sub_804D738
    .type sub_804D738, %function
    .thumb
    .thumb_func
sub_804D738:  @ 0x0804CE0C (jp 0x0804D738, score 0.8438)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0xB084  @ sub sp, #0x10
    .hword 0x4C3B  @ ldr r4, [pc, #0xec]
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x2208  @ movs r2, #8
    .hword 0x4252  @ rsbs r2, r2, #0
    .hword 0x4002  @ ands r2, r0
    .hword 0x7860  @ ldrb r0, [r4, #1]
    .hword 0x2501  @ movs r5, #1
    .hword 0x4328  @ orrs r0, r5
    .hword 0x2602  @ movs r6, #2
    .hword 0x4330  @ orrs r0, r6
    .hword 0x2104  @ movs r1, #4
    .hword 0x4308  @ orrs r0, r1
    .hword 0x2108  @ movs r1, #8
    .hword 0x4308  @ orrs r0, r1
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7060  @ strb r0, [r4, #1]
    .hword 0x2041  @ movs r0, #0x41
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x4002  @ ands r2, r0
    .hword 0x7022  @ strb r2, [r4]
    .hword 0x2000  @ movs r0, #0
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xFFAAF7B4  @ bl #0xfffb4f58
    .hword 0x2001  @ movs r0, #1
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xFFA5F7B4  @ bl #0xfffb4f4e
    .hword 0x2002  @ movs r0, #2
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xFFA0F7B4  @ bl #0xfffb4f44
    .hword 0x2000  @ movs r0, #0
    .hword 0x2100  @ movs r1, #0
    .word 0xFAF0F7B4  @ bl #0xfffb45e4
    .hword 0x2001  @ movs r0, #1
    .hword 0x2100  @ movs r1, #0
    .word 0xFAECF7B4  @ bl #0xfffb45dc
    .hword 0x2002  @ movs r0, #2
    .hword 0x2100  @ movs r1, #0
    .word 0xFAE8F7B4  @ bl #0xfffb45d4
    .hword 0x2180  @ movs r1, #0x80
    .hword 0x0209  @ lsls r1, r1, #8
    .hword 0x2003  @ movs r0, #3
    .word 0xFAE3F7B4  @ bl #0xfffb45ca
    .hword 0x21C0  @ movs r1, #0xc0
    .hword 0x01C9  @ lsls r1, r1, #7
    .hword 0x2000  @ movs r0, #0
    .word 0xFB00F7B4  @ bl #0xfffb4604
    .hword 0x21D0  @ movs r1, #0xd0
    .hword 0x01C9  @ lsls r1, r1, #7
    .hword 0x2001  @ movs r0, #1
    .word 0xFAFBF7B4  @ bl #0xfffb45fa
    .hword 0x21E0  @ movs r1, #0xe0
    .hword 0x01C9  @ lsls r1, r1, #7
    .hword 0x2002  @ movs r0, #2
    .word 0xFAF6F7B4  @ bl #0xfffb45f0
    .hword 0x21F0  @ movs r1, #0xf0
    .hword 0x01C9  @ lsls r1, r1, #7
    .hword 0x2003  @ movs r0, #3
    .word 0xFAF1F7B4  @ bl #0xfffb45e6
    .hword 0x7B22  @ ldrb r2, [r4, #0xc]
    .hword 0x2104  @ movs r1, #4
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x4010  @ ands r0, r2
    .hword 0x7320  @ strb r0, [r4, #0xc]
    .hword 0x7C22  @ ldrb r2, [r4, #0x10]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x4010  @ ands r0, r2
    .hword 0x4328  @ orrs r0, r5
    .hword 0x7420  @ strb r0, [r4, #0x10]
    .hword 0x7D20  @ ldrb r0, [r4, #0x14]
    .hword 0x4001  @ ands r1, r0
    .hword 0x4331  @ orrs r1, r6
    .hword 0x7521  @ strb r1, [r4, #0x14]
    .hword 0x7E20  @ ldrb r0, [r4, #0x18]
    .hword 0x2103  @ movs r1, #3
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7620  @ strb r0, [r4, #0x18]
    .hword 0x2400  @ movs r4, #0
    .hword 0x9400  @ str r4, [sp]
    .hword 0x490D  @ ldr r1, [pc, #0x34]
    .hword 0x4D0E  @ ldr r5, [pc, #0x38]
    .hword 0x4668  @ mov r0, sp
    .hword 0x1C2A  @ adds r2, r5, #0
    .word 0xFB80F073  @ bl #0x73704
    .hword 0x9401  @ str r4, [sp, #4]
    .hword 0xA801  @ add r0, sp, #4
    .hword 0x490B  @ ldr r1, [pc, #0x2c]
    .hword 0x1C2A  @ adds r2, r5, #0
    .word 0xFB7AF073  @ bl #0x736f8
    .hword 0x9402  @ str r4, [sp, #8]
    .hword 0xA802  @ add r0, sp, #8
    .hword 0x4E09  @ ldr r6, [pc, #0x24]
    .hword 0x1C31  @ adds r1, r6, #0
    .hword 0x1C2A  @ adds r2, r5, #0
    .word 0xFB73F073  @ bl #0x736ea
    .word 0xFAC1F008  @ bl #0x8586
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10C  @ bne #0x1c
    .word 0xF835F000  @ bl #0x6e
    .hword 0xE00F  @ b #0x22
    .hword 0x2870  @ cmp r0, #0x70
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x2C60  @ cmp r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x3460  @ adds r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x3C60  @ subs r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x9403  @ str r4, [sp, #0xc]
    .hword 0xA803  @ add r0, sp, #0xc
    .hword 0x1C31  @ adds r1, r6, #0
    .hword 0x1C2A  @ adds r2, r5, #0
    .word 0xFB5CF073  @ bl #0x736bc
    .word 0xF8B0F000  @ bl #0x164
    .word 0xF8A0F7B4  @ bl #0xfffb4144
    .hword 0x2001  @ movs r0, #1
    .word 0xF86DF7B4  @ bl #0xfffb40de
    .hword 0x2002  @ movs r0, #2
    .word 0xF86AF7B4  @ bl #0xfffb40d8
    .hword 0x2004  @ movs r0, #4
    .word 0xF867F7B4  @ bl #0xfffb40d2
    .hword 0x4B0A  @ ldr r3, [pc, #0x28]
    .hword 0x1C1A  @ adds r2, r3, #0
    .hword 0x323C  @ adds r2, #0x3c
    .hword 0x7811  @ ldrb r1, [r2]
    .hword 0x203F  @ movs r0, #0x3f
    .hword 0x4008  @ ands r0, r1
    .hword 0x7010  @ strb r0, [r2]
    .hword 0x1C19  @ adds r1, r3, #0
    .hword 0x3144  @ adds r1, #0x44
    .hword 0x2200  @ movs r2, #0
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x3045  @ adds r0, #0x45
    .hword 0x7002  @ strb r2, [r0]
    .hword 0x3001  @ adds r0, #1
    .hword 0x7002  @ strb r2, [r0]
    .hword 0xB004  @ add sp, #0x10
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x2870  @ cmp r0, #0x70
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global sub_804D894
    .type sub_804D894, %function
    .thumb
    .thumb_func
sub_804D894:  @ 0x0804CF68 (jp 0x0804D894, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4647  @ mov r7, r8
    .hword 0xB480  @ push {r7}
    .hword 0x4C0E  @ ldr r4, [pc, #0x38]
    .hword 0x4A0E  @ ldr r2, [pc, #0x38]
    .hword 0x2000  @ movs r0, #0
    .hword 0x5E11  @ ldrsh r1, [r2, r0]
    .hword 0x0048  @ lsls r0, r1, #1
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x00C0  @ lsls r0, r0, #3
    .hword 0x4B0C  @ ldr r3, [pc, #0x30]
    .hword 0x18C5  @ adds r5, r0, r3
    .hword 0x2602  @ movs r6, #2
    .hword 0x5F91  @ ldrsh r1, [r2, r6]
    .hword 0x0048  @ lsls r0, r1, #1
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x00C0  @ lsls r0, r0, #3
    .hword 0x18C3  @ adds r3, r0, r3
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x2700  @ movs r7, #0
    .hword 0x5FC1  @ ldrsh r1, [r0, r7]
    .hword 0x4690  @ mov r8, r2
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x2903  @ cmp r1, #3
    .hword 0xDC10  @ bgt #0x24
    .hword 0x2901  @ cmp r1, #1
    .hword 0xDA20  @ bge #0x44
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD010  @ beq #0x24
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0xE025  @ b #0x4e
    .hword 0x0000  @ movs r0, r0
    .byte 0xD0
    .hword 0x01FA  @ lsls r2, r7, #7
    .hword 0x2802  @ cmp r0, #2
    .hword 0x03E0  @ lsls r0, r4, #0xf
    .hword 0x0802  @ lsrs r2, r0, #0x20
    .byte 0x00
    .hword 0x08FC  @ lsrs r4, r7, #3
    .hword 0xE02C  @ b #0x5c
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x45C8  @ cmp r8, sb
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x4F06  @ ldr r7, [pc, #0x18]
    .hword 0x46BC  @ mov ip, r7
    .hword 0x2904  @ cmp r1, #4
    .hword 0xD117  @ bne #0x32
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x4904  @ ldr r1, [pc, #0x10]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x2780  @ movs r7, #0x80
    .hword 0x017F  @ lsls r7, r7, #5
    .hword 0x19CA  @ adds r2, r1, r7
    .hword 0x6042  @ str r2, [r0, #4]
    .hword 0x468C  @ mov ip, r1
    .hword 0xE00E  @ b #0x20
    .hword 0x0000  @ movs r0, r0
    .hword 0x45C8  @ cmp r8, sb
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x003C  @ movs r4, r7
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x4820  @ ldr r0, [pc, #0x80]
    .hword 0x4921  @ ldr r1, [pc, #0x84]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x2780  @ movs r7, #0x80
    .hword 0x017F  @ lsls r7, r7, #5
    .hword 0x19CA  @ adds r2, r1, r7
    .hword 0x6042  @ str r2, [r0, #4]
    .hword 0x481F  @ ldr r0, [pc, #0x7c]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4684  @ mov ip, r0
    .hword 0x481E  @ ldr r0, [pc, #0x78]
    .hword 0x7D40  @ ldrb r0, [r0, #0x15]
    .hword 0x481E  @ ldr r0, [pc, #0x78]
    .hword 0x6929  @ ldr r1, [r5, #0x10]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x6919  @ ldr r1, [r3, #0x10]
    .hword 0x6041  @ str r1, [r0, #4]
    .hword 0x4A1D  @ ldr r2, [pc, #0x74]
    .hword 0x491D  @ ldr r1, [pc, #0x74]
    .hword 0x2300  @ movs r3, #0
    .hword 0x5EF0  @ ldrsh r0, [r6, r3]
    .hword 0x00C0  @ lsls r0, r0, #3
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x6010  @ str r0, [r2]
    .hword 0x2700  @ movs r7, #0
    .hword 0x5FF0  @ ldrsh r0, [r6, r7]
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x3001  @ adds r0, #1
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x6050  @ str r0, [r2, #4]
    .hword 0x4641  @ mov r1, r8
    .hword 0x8808  @ ldrh r0, [r1]
    .hword 0x2200  @ movs r2, #0
    .hword 0x8020  @ strh r0, [r4]
    .hword 0x2004  @ movs r0, #4
    .hword 0x8060  @ strh r0, [r4, #2]
    .hword 0x21A0  @ movs r1, #0xa0
    .hword 0x0089  @ lsls r1, r1, #2
    .hword 0x80A1  @ strh r1, [r4, #4]
    .hword 0x4643  @ mov r3, r8
    .hword 0x8858  @ ldrh r0, [r3, #2]
    .hword 0x80E0  @ strh r0, [r4, #6]
    .hword 0x2005  @ movs r0, #5
    .hword 0x8120  @ strh r0, [r4, #8]
    .hword 0x8161  @ strh r1, [r4, #0xa]
    .hword 0x8830  @ ldrh r0, [r6]
    .hword 0x81A0  @ strh r0, [r4, #0xc]
    .hword 0x2002  @ movs r0, #2
    .hword 0x81E0  @ strh r0, [r4, #0xe]
    .hword 0x61E2  @ str r2, [r4, #0x1c]
    .hword 0x4666  @ mov r6, ip
    .hword 0x6226  @ str r6, [r4, #0x20]
    .hword 0x480C  @ ldr r0, [pc, #0x30]
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x8220  @ strh r0, [r4, #0x10]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFF2FF007  @ bl #0x7e62
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x003C  @ movs r4, r7
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x4DC8  @ ldr r5, [pc, #0x320]
    .hword 0x0201  @ lsls r1, r0, #8
    .word 0xFFFFF800  @ strb pc, [r0, #0xff]!
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x004C  @ lsls r4, r1, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x0044  @ lsls r4, r0, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x6A58  @ ldr r0, [r3, #0x24]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0xE00E  @ b #0x20
    .hword 0x0203  @ lsls r3, r0, #8

    .global EfxPrepareScreenFx
    .type EfxPrepareScreenFx, %function
    .thumb
    .thumb_func
EfxPrepareScreenFx:  @ 0x0804D084 (jp 0x0804D9B0, score 0.9375)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0xB082  @ sub sp, #8
    .hword 0x4C0E  @ ldr r4, [pc, #0x38]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2140  @ movs r1, #0x40
    .hword 0x2220  @ movs r2, #0x20
    .word 0xFFFEF7B3  @ bl #0xfffb4000
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2160  @ movs r1, #0x60
    .hword 0x2220  @ movs r2, #0x20
    .word 0xFFF9F7B3  @ bl #0xfffb3ff6
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x490A  @ ldr r1, [pc, #0x28]
    .hword 0x22A0  @ movs r2, #0xa0
    .hword 0x2302  @ movs r3, #2
    .word 0xF9B7F7B8  @ bl #0xfffb8372
    .word 0xFD2BF7B8  @ bl #0xfffb8a5a
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x4908  @ ldr r1, [pc, #0x20]
    .word 0xFA9DF073  @ bl #0x7353e
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10F  @ bne #0x22
    .hword 0x4D06  @ ldr r5, [pc, #0x18]
    .hword 0xE014  @ b #0x2c
    .hword 0x14D4  @ asrs r4, r2, #0x13
    .hword 0x080D  @ lsrs r5, r1, #0x20
    .hword 0x7648  @ strb r0, [r1, #0x19]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x0600  @ lsls r0, r0, #0x18
    .byte 0xF8
    .hword 0x2BF9  @ cmp r3, #0xf9
    .hword 0x0008  @ movs r0, r1
    .hword 0x0010  @ movs r0, r2
    .hword 0x1006  @ asrs r6, r0, #0x20
    .hword 0x03E0  @ lsls r0, r4, #0xf
    .hword 0x5402  @ strb r2, [r0, r0]
    .hword 0xC961  @ ldm r1!, {r0, r5, r6}
    .hword 0x1108  @ asrs r0, r1, #4
    .hword 0x0048  @ lsls r0, r1, #1
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0xC588  @ stm r5!, {r3, r7}
    .hword 0x06F7  @ lsls r7, r6, #0x1b
    .hword 0x05FF  @ lsls r7, r7, #0x17
    .hword 0x0F1C  @ lsrs r4, r3, #0x1c
    .hword 0x204C  @ movs r0, #0x4c
    .hword 0x061C  @ lsls r4, r3, #0x18
    .byte 0x21
    .word 0xF9E2F7B8  @ bl #0xfffb83c8
    .hword 0x2030  @ movs r0, #0x30
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFAF8F7B8  @ bl #0xfffb85f4
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA56F7B8  @ bl #0xfffb84b0
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x490A  @ ldr r1, [pc, #0x28]
    .word 0xFA70F073  @ bl #0x734e4
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFB26F7B8  @ bl #0xfffb8650
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10E  @ bne #0x20
    .hword 0x4D06  @ ldr r5, [pc, #0x18]
    .hword 0xE013  @ b #0x2a
    .hword 0x0000  @ movs r0, r0
    .hword 0xE094  @ b #0x12c
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x7660  @ strb r0, [r4, #0x19]
    .hword 0x0201  @ lsls r1, r0, #8
    .byte 0x00
    .hword 0x2BFC  @ cmp r3, #0xfc
    .hword 0x0008  @ movs r0, r1
    .hword 0x0014  @ movs r4, r2
    .hword 0x1006  @ asrs r6, r0, #0x20
    .hword 0x03E0  @ lsls r0, r4, #0xf
    .hword 0x5402  @ strb r2, [r0, r0]
    .hword 0xC961  @ ldm r1!, {r0, r5, r6}
    .hword 0x1108  @ asrs r0, r1, #4
    .hword 0x0048  @ lsls r0, r1, #1
    .hword 0x4A68  @ ldr r2, [pc, #0x1a0]
    .hword 0x0030  @ movs r0, r6
    .hword 0xCA88  @ ldm r2!, {r3, r7}
    .byte 0xF7
    .byte 0xF6
    .hword 0x05F9  @ lsls r1, r7, #0x17
    .hword 0x0F1C  @ lsrs r4, r3, #0x1c
    .hword 0x204C  @ movs r0, #0x4c
    .hword 0x071C  @ lsls r4, r3, #0x1c
    .byte 0x21
    .word 0xF9B2F7B8  @ bl #0xfffb8368
    .hword 0x2038  @ movs r0, #0x38
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFAC8F7B8  @ bl #0xfffb8594
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA26F7B8  @ bl #0xfffb8450
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x490A  @ ldr r1, [pc, #0x28]
    .word 0xFA40F073  @ bl #0x73484
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFAF6F7B8  @ bl #0xfffb85f0
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10E  @ bne #0x20
    .hword 0x4D06  @ ldr r5, [pc, #0x18]
    .hword 0xE013  @ b #0x2a
    .hword 0x0000  @ movs r0, r0
    .hword 0xE094  @ b #0x12c
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x7670  @ strb r0, [r6, #0x19]
    .hword 0x0201  @ lsls r1, r0, #8
    .word 0x082BFC50  @ mrrc2 p8, #2, r0, r0, c11
    .hword 0x1580  @ asrs r0, r0, #0x16
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0xE010  @ b #0x24
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x6154  @ str r4, [r2, #0x14]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x4811  @ ldr r0, [pc, #0x44]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x8800  @ ldrh r0, [r0]
    .word 0xFEA6F7C5  @ bl #0xfffc5d50
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x4C0F  @ ldr r4, [pc, #0x3c]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2106  @ movs r1, #6
    .word 0xF982F7B8  @ bl #0xfffb8308
    .hword 0x2030  @ movs r0, #0x30
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFA98F7B8  @ bl #0xfffb8534
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF9F6F7B8  @ bl #0xfffb83f0
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x490A  @ ldr r1, [pc, #0x28]
    .word 0xFA10F073  @ bl #0x73424
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFAC6F7B8  @ bl #0xfffb8590
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10E  @ bne #0x20
    .hword 0x4D06  @ ldr r5, [pc, #0x18]
    .hword 0xE013  @ b #0x2a
    .hword 0x0000  @ movs r0, r0
    .hword 0xE098  @ b #0x134
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x7678  @ strb r0, [r7, #0x19]
    .hword 0x0201  @ lsls r1, r0, #8
    .word 0x082BFCBC  @ ldc2 p8, c0, [ip], #0xac
    .hword 0x1740  @ asrs r0, r0, #0x1d
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0xE010  @ b #0x24
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x6154  @ str r4, [r2, #0x14]
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0x4830  @ ldr r0, [pc, #0xc0]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x304A  @ adds r0, #0x4a
    .hword 0x8800  @ ldrh r0, [r0]
    .word 0xF996F7CA  @ bl #0xfffca330
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x4C2E  @ ldr r4, [pc, #0xb8]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2107  @ movs r1, #7
    .word 0xF952F7B8  @ bl #0xfffb82a8
    .hword 0x2038  @ movs r0, #0x38
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFA68F7B8  @ bl #0xfffb84d4
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF9C6F7B8  @ bl #0xfffb8390
    .hword 0x4828  @ ldr r0, [pc, #0xa0]
    .hword 0x4929  @ ldr r1, [pc, #0xa4]
    .word 0xF9E0F073  @ bl #0x733c4
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFA96F7B8  @ bl #0xfffb8530
    .hword 0x4C26  @ ldr r4, [pc, #0x98]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x219F  @ movs r1, #0x9f
    .word 0xFAEDF7B4  @ bl #0xfffb45de
    .hword 0x4825  @ ldr r0, [pc, #0x94]
    .hword 0x1C26  @ adds r6, r4, #0
    .hword 0x363C  @ adds r6, #0x3c
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x9100  @ str r1, [sp]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x1C31  @ adds r1, r6, #0
    .hword 0x2202  @ movs r2, #2
    .hword 0x2314  @ movs r3, #0x14
    .word 0xFC9DF019  @ bl #0x1993e
    .hword 0x343E  @ adds r4, #0x3e
    .hword 0x2580  @ movs r5, #0x80
    .hword 0x9500  @ str r5, [sp]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2101  @ movs r1, #1
    .hword 0x2214  @ movs r2, #0x14
    .hword 0x2302  @ movs r3, #2
    .word 0xFBCCF019  @ bl #0x1979c
    .hword 0x9500  @ str r5, [sp]
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x2101  @ movs r1, #1
    .hword 0x2214  @ movs r2, #0x14
    .hword 0x2303  @ movs r3, #3
    .word 0xFBC5F019  @ bl #0x1978e
    .hword 0x2001  @ movs r0, #1
    .word 0xFEC4F7B3  @ bl #0xfffb3d8c
    .hword 0x4E16  @ ldr r6, [pc, #0x58]
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E70  @ ldrsh r0, [r6, r1]
    .hword 0x0140  @ lsls r0, r0, #5
    .hword 0x4D15  @ ldr r5, [pc, #0x54]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x4C15  @ ldr r4, [pc, #0x54]
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x2208  @ movs r2, #8
    .word 0xF9A1F073  @ bl #0x73346
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E70  @ ldrsh r0, [r6, r1]
    .hword 0x0140  @ lsls r0, r0, #5
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x3420  @ adds r4, #0x20
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x2208  @ movs r2, #8
    .word 0xF998F073  @ bl #0x73334
    .word 0xFEDEF7B3  @ bl #0xfffb3dc0
    .hword 0x490E  @ ldr r1, [pc, #0x38]
    .hword 0x2000  @ movs r0, #0
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xFD6EF7B4  @ bl #0xfffb4ae0
    .hword 0xB002  @ add sp, #8
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xE098  @ b #0x134
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x7668  @ strb r0, [r5, #0x19]
    .hword 0x0201  @ lsls r1, r0, #8
    .word 0x082BFD0C  @ stc2 p8, c0, [ip, #-0xac]
    .hword 0x18C0  @ adds r0, r0, r3
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2C60  @ cmp r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x0094  @ lsls r4, r2, #2
    .hword 0x082C  @ lsrs r4, r5, #0x20
    .hword 0xE020  @ b #0x44
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x00E4  @ lsls r4, r4, #3
    .hword 0x082C  @ lsrs r4, r5, #0x20
    .hword 0x28A0  @ cmp r0, #0xa0
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x0038  @ movs r0, r7
    .hword 0x0200  @ lsls r0, r0, #8

    .incbin "rom/fe7eu.gba", 0x4D2EC, 0x90

    .global EkrEfxStatusClear
    .type EkrEfxStatusClear, %function
    .thumb
    .thumb_func
EkrEfxStatusClear:  @ 0x0804D37C (jp 0x0804DCA8, score 1.0)
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x2000  @ movs r0, #0
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4916  @ ldr r1, [pc, #0x58]
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x4915  @ ldr r1, [pc, #0x54]
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x4915  @ ldr r1, [pc, #0x54]
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x4914  @ ldr r1, [pc, #0x50]
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x8048  @ strh r0, [r1, #2]
    .hword 0x4914  @ ldr r1, [pc, #0x50]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x6048  @ str r0, [r1, #4]
    .hword 0x4913  @ ldr r1, [pc, #0x4c]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4913  @ ldr r1, [pc, #0x4c]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4770  @ bx lr
    .hword 0x0000  @ movs r0, r0
    .hword 0x7728  @ strb r0, [r5, #0x1c]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x772C  @ strb r4, [r5, #0x1c]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7730  @ strb r0, [r6, #0x1c]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7738  @ strb r0, [r7, #0x1c]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x773C  @ strb r4, [r7, #0x1c]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7740  @ strb r0, [r0, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7748  @ strb r0, [r1, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x774C  @ strb r4, [r1, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7750  @ strb r0, [r2, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7754  @ strb r4, [r2, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7758  @ strb r0, [r3, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x775C  @ strb r4, [r3, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7760  @ strb r0, [r4, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7764  @ strb r4, [r4, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7768  @ strb r0, [r5, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7780  @ strb r0, [r0, #0x1e]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x776C  @ strb r4, [r5, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x7778  @ strb r0, [r7, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x777C  @ strb r4, [r7, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8

