@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x00050868-0x00050980
    .syntax unified

    .global SetupBanim
    .type SetupBanim, %function
    .thumb
    .thumb_func
SetupBanim:  @ 0x08050868 (jp 0x08051170, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xF9F3F001  @ bl #0x13ea
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global BeginAnimsOnBattleAnimations
    .type BeginAnimsOnBattleAnimations, %function
    .thumb
    .thumb_func
BeginAnimsOnBattleAnimations:  @ 0x08050878 (jp 0x08051180, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFDFDF004  @ bl #0x4bfe
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD102  @ bne #8
    .word 0xFE39F004  @ bl #0x4c76
    .hword 0xE01F  @ b #0x42
    .word 0xFFAAF01A  @ bl #0x1af58
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD102  @ bne #8
    .word 0xFFB6F01A  @ bl #0x1af70
    .hword 0xE018  @ b #0x34
    .word 0xFB45F7FA  @ bl #0xffffa68e
    .word 0xFECBF7B5  @ bl #0xfffb5d9a
    .word 0xFD25F7FC  @ bl #0xffffca4e
    .hword 0x490A  @ ldr r1, [pc, #0x28]
    .hword 0x6008  @ str r0, [r1]
    .word 0xF86BF000  @ bl #0xda
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x2100  @ movs r1, #0
    .hword 0x6001  @ str r1, [r0]
    .hword 0x6041  @ str r1, [r0, #4]
    .hword 0x6081  @ str r1, [r0, #8]
    .hword 0x60C1  @ str r1, [r0, #0xc]
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x6041  @ str r1, [r0, #4]
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .word 0xF881F7B1  @ bl #0xfffb1106
    .hword 0x2000  @ movs r0, #0
    .word 0xFB2CF7B2  @ bl #0xfffb265c
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x7744  @ strb r4, [r0, #0x1d]
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x0000  @ movs r0, r0
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x0010  @ movs r0, r2
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x090D  @ lsrs r5, r1, #4
    .hword 0x0805  @ lsrs r5, r0, #0x20

    .incbin "rom/fe7eu.gba", 0x508DC, 0x30

    .global sub_8051214
    .type sub_8051214, %function
    .thumb
    .thumb_func
sub_8051214:  @ 0x0805090C (jp 0x08051214, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4818  @ ldr r0, [pc, #0x60]
    .hword 0x6800  @ ldr r0, [r0]
    .word 0xF95FF7B1  @ bl #0xfffb12c2
    .word 0xF8E5F7B6  @ bl #0xfffb61ce
    .hword 0x4C16  @ ldr r4, [pc, #0x58]
    .hword 0x6860  @ ldr r0, [r4, #4]
    .word 0xFEC3F7B3  @ bl #0xfffb3d8a
    .word 0xFE55F7C4  @ bl #0xfffc4cae
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD102  @ bne #8
    .hword 0x68A0  @ ldr r0, [r4, #8]
    .word 0xFEBBF7B3  @ bl #0xfffb3d7a
    .hword 0x68E0  @ ldr r0, [r4, #0xc]
    .word 0xFEB8F7B3  @ bl #0xfffb3d74
    .hword 0x6960  @ ldr r0, [r4, #0x14]
    .word 0xFEB5F7B3  @ bl #0xfffb3d6e
    .hword 0x2000  @ movs r0, #0
    .word 0xF92AF7B6  @ bl #0xfffb6258
    .hword 0x6920  @ ldr r0, [r4, #0x10]
    .word 0xFEAFF7B3  @ bl #0xfffb3d62
    .word 0xFE37F7B5  @ bl #0xfffb5c72
    .word 0xFD23F002  @ bl #0x2a4a
    .hword 0x200D  @ movs r0, #0xd
    .word 0xF920F7B6  @ bl #0xfffb6244
    .hword 0x4907  @ ldr r1, [pc, #0x1c]
    .hword 0x2001  @ movs r0, #1
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x80C8  @ strh r0, [r1, #6]
    .word 0xFE68F06F  @ bl #0x6fcd4
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .word 0x08C7EFDC  @ vmul.i16 d16, d28, d7[0]
    .hword 0x6A30  @ ldr r0, [r6, #0x20]
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xBBB8  @ cbnz r0, #0x72
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x0006  @ movs r6, r0
    .hword 0x0400  @ lsls r0, r0, #0x10

