@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x000B60F8-0x000B6630
    .syntax unified

    .global sub_80B6450
    .type sub_80B6450, %function
    .thumb
    .thumb_func
sub_80B6450:  @ 0x080B60F8 (jp 0x080B6450, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xF8A1F74E  @ bl #0xfff4e146
    .word 0xFC91F7FF  @ bl #0xfffff926
    .hword 0x2000  @ movs r0, #0
    .word 0xFCC2F7FD  @ bl #0xffffd988
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_80B6464
    .type sub_80B6464, %function
    .thumb
    .thumb_func
sub_80B6464:  @ 0x080B610C (jp 0x080B6464, score 0.8182)
    .hword 0xB500  @ push {lr}
    .hword 0x4804  @ ldr r0, [pc, #0x10]
    .word 0xFAD6F74E  @ bl #0xfff4e5b0
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x7550  @ strb r0, [r2, #0x15]
    .hword 0x08DE  @ lsrs r6, r3, #3

    .incbin "rom/fe7eu.gba", 0xB6124, 0x104

    .global sub_80B6580
    .type sub_80B6580, %function
    .thumb
    .thumb_func
sub_80B6580:  @ 0x080B6228 (jp 0x080B6580, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4647  @ mov r7, r8
    .hword 0xB480  @ push {r7}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0C  @ adds r4, r1, #0
    .hword 0x1C16  @ adds r6, r2, #0
    .hword 0x4698  @ mov r8, r3
    .hword 0x9F06  @ ldr r7, [sp, #0x18]
    .hword 0x0624  @ lsls r4, r4, #0x18
    .hword 0x0E24  @ lsrs r4, r4, #0x18
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .word 0xFA3FF74E  @ bl #0xfff4e482
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .word 0xF92BF74E  @ bl #0xfff4e25a
    .hword 0x62C5  @ str r5, [r0, #0x2c]
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x3130  @ adds r1, #0x30
    .hword 0x700C  @ strb r4, [r1]
    .hword 0x6346  @ str r6, [r0, #0x34]
    .hword 0x4641  @ mov r1, r8
    .hword 0x6401  @ str r1, [r0, #0x40]
    .hword 0x6387  @ str r7, [r0, #0x38]
    .hword 0x9907  @ ldr r1, [sp, #0x1c]
    .hword 0x63C1  @ str r1, [r0, #0x3c]
    .hword 0x9908  @ ldr r1, [sp, #0x20]
    .hword 0x6441  @ str r1, [r0, #0x44]
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x7550  @ strb r0, [r2, #0x15]
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x7610  @ strb r0, [r2, #0x18]
    .hword 0x08DE  @ lsrs r6, r3, #3

    .global sub_80B65CC
    .type sub_80B65CC, %function
    .thumb
    .thumb_func
sub_80B65CC:  @ 0x080B6274 (jp 0x080B65CC, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x6B30  @ ldr r0, [r6, #0x30]
    .hword 0x0140  @ lsls r0, r0, #5
    .hword 0x4920  @ ldr r1, [pc, #0x80]
    .hword 0x1845  @ adds r5, r0, r1
    .hword 0x1C34  @ adds r4, r6, #0
    .hword 0x3434  @ adds r4, #0x34
    .hword 0x6AF0  @ ldr r0, [r6, #0x2c]
    .hword 0x3001  @ adds r0, #1
    .hword 0x62F0  @ str r0, [r6, #0x2c]
    .hword 0x211F  @ movs r1, #0x1f
    .hword 0x4689  @ mov sb, r1
    .hword 0x2120  @ movs r1, #0x20
    .hword 0x1A0B  @ subs r3, r1, r0
    .hword 0x22F8  @ movs r2, #0xf8
    .hword 0x0092  @ lsls r2, r2, #2
    .hword 0x4690  @ mov r8, r2
    .hword 0x27F8  @ movs r7, #0xf8
    .hword 0x01FF  @ lsls r7, r7, #7
    .hword 0x46BC  @ mov ip, r7
    .hword 0x200E  @ movs r0, #0xe
    .hword 0x4682  @ mov sl, r0
    .hword 0x8822  @ ldrh r2, [r4]
    .hword 0x201F  @ movs r0, #0x1f
    .hword 0x4010  @ ands r0, r2
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4359  @ muls r1, r3, r1
    .hword 0x1149  @ asrs r1, r1, #5
    .hword 0x464F  @ mov r7, sb
    .hword 0x4039  @ ands r1, r7
    .hword 0x4640  @ mov r0, r8
    .hword 0x4010  @ ands r0, r2
    .hword 0x4358  @ muls r0, r3, r0
    .hword 0x1140  @ asrs r0, r0, #5
    .hword 0x4647  @ mov r7, r8
    .hword 0x4038  @ ands r0, r7
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x4660  @ mov r0, ip
    .hword 0x4010  @ ands r0, r2
    .hword 0x4358  @ muls r0, r3, r0
    .hword 0x1140  @ asrs r0, r0, #5
    .hword 0x4662  @ mov r2, ip
    .hword 0x4010  @ ands r0, r2
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x8029  @ strh r1, [r5]
    .hword 0x3402  @ adds r4, #2
    .hword 0x3502  @ adds r5, #2
    .hword 0x2701  @ movs r7, #1
    .hword 0x427F  @ rsbs r7, r7, #0
    .hword 0x44BA  @ add sl, r7
    .hword 0x4650  @ mov r0, sl
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDAE0  @ bge #0xffffffc4
    .word 0xFEBEF74A  @ bl #0xfff4ad80
    .hword 0x6AF0  @ ldr r0, [r6, #0x2c]
    .hword 0x2820  @ cmp r0, #0x20
    .hword 0xD102  @ bne #8
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xF9E0F74E  @ bl #0xfff4e3c4
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x2862  @ cmp r0, #0x62
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_80B6664
    .type sub_80B6664, %function
    .thumb
    .thumb_func
sub_80B6664:  @ 0x080B630C (jp 0x080B6664, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x4811  @ ldr r0, [pc, #0x44]
    .word 0xF9D5F74E  @ bl #0xfff4e3ae
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4810  @ ldr r0, [pc, #0x40]
    .word 0xF8C1F74E  @ bl #0xfff4e186
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x201F  @ movs r0, #0x1f
    .hword 0x4004  @ ands r4, r0
    .hword 0x632C  @ str r4, [r5, #0x30]
    .hword 0x2000  @ movs r0, #0
    .hword 0x62E8  @ str r0, [r5, #0x2c]
    .hword 0x480D  @ ldr r0, [pc, #0x34]
    .hword 0x21E0  @ movs r1, #0xe0
    .hword 0x0089  @ lsls r1, r1, #2
    .hword 0x2280  @ movs r2, #0x80
    .word 0xFEADF74A  @ bl #0xfff4ad5e
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x0164  @ lsls r4, r4, #5
    .hword 0x1824  @ adds r4, r4, r0
    .hword 0x3402  @ adds r4, #2
    .hword 0x3534  @ adds r5, #0x34
    .hword 0x210E  @ movs r1, #0xe
    .hword 0x8820  @ ldrh r0, [r4]
    .hword 0x8028  @ strh r0, [r5]
    .hword 0x3402  @ adds r4, #2
    .hword 0x3502  @ adds r5, #2
    .hword 0x3901  @ subs r1, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDAF8  @ bge #0xfffffff4
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x7550  @ strb r0, [r2, #0x15]
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x7628  @ strb r0, [r5, #0x18]
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x13F4  @ asrs r4, r6, #0xf
    .hword 0x080D  @ lsrs r5, r1, #0x20
    .hword 0x2860  @ cmp r0, #0x60
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_80B66C0
    .type sub_80B66C0, %function
    .thumb
    .thumb_func
sub_80B66C0:  @ 0x080B6368 (jp 0x080B66C0, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x6B30  @ ldr r0, [r6, #0x30]
    .hword 0x0140  @ lsls r0, r0, #5
    .hword 0x491F  @ ldr r1, [pc, #0x7c]
    .hword 0x1845  @ adds r5, r0, r1
    .hword 0x1C34  @ adds r4, r6, #0
    .hword 0x3434  @ adds r4, #0x34
    .hword 0x6AF0  @ ldr r0, [r6, #0x2c]
    .hword 0x3001  @ adds r0, #1
    .hword 0x62F0  @ str r0, [r6, #0x2c]
    .hword 0x211F  @ movs r1, #0x1f
    .hword 0x4689  @ mov sb, r1
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x22F8  @ movs r2, #0xf8
    .hword 0x0092  @ lsls r2, r2, #2
    .hword 0x4690  @ mov r8, r2
    .hword 0x27F8  @ movs r7, #0xf8
    .hword 0x01FF  @ lsls r7, r7, #7
    .hword 0x46BC  @ mov ip, r7
    .hword 0x200E  @ movs r0, #0xe
    .hword 0x4682  @ mov sl, r0
    .hword 0x8822  @ ldrh r2, [r4]
    .hword 0x201F  @ movs r0, #0x1f
    .hword 0x4010  @ ands r0, r2
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4359  @ muls r1, r3, r1
    .hword 0x1149  @ asrs r1, r1, #5
    .hword 0x464F  @ mov r7, sb
    .hword 0x4039  @ ands r1, r7
    .hword 0x4640  @ mov r0, r8
    .hword 0x4010  @ ands r0, r2
    .hword 0x4358  @ muls r0, r3, r0
    .hword 0x1140  @ asrs r0, r0, #5
    .hword 0x4647  @ mov r7, r8
    .hword 0x4038  @ ands r0, r7
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x4660  @ mov r0, ip
    .hword 0x4010  @ ands r0, r2
    .hword 0x4358  @ muls r0, r3, r0
    .hword 0x1140  @ asrs r0, r0, #5
    .hword 0x4662  @ mov r2, ip
    .hword 0x4010  @ ands r0, r2
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x8029  @ strh r1, [r5]
    .hword 0x3402  @ adds r4, #2
    .hword 0x3502  @ adds r5, #2
    .hword 0x2701  @ movs r7, #1
    .hword 0x427F  @ rsbs r7, r7, #0
    .hword 0x44BA  @ add sl, r7
    .hword 0x4650  @ mov r0, sl
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDAE0  @ bge #0xffffffc4
    .word 0xFE45F74A  @ bl #0xfff4ac8e
    .hword 0x6AF0  @ ldr r0, [r6, #0x2c]
    .hword 0x2820  @ cmp r0, #0x20
    .hword 0xD102  @ bne #8
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xF967F74E  @ bl #0xfff4e2d2
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x2862  @ cmp r0, #0x62
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_80B6754
    .type sub_80B6754, %function
    .thumb
    .thumb_func
sub_80B6754:  @ 0x080B63FC (jp 0x080B6754, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x4811  @ ldr r0, [pc, #0x44]
    .word 0xF95DF74E  @ bl #0xfff4e2be
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4810  @ ldr r0, [pc, #0x40]
    .word 0xF849F74E  @ bl #0xfff4e096
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x201F  @ movs r0, #0x1f
    .hword 0x4004  @ ands r4, r0
    .hword 0x632C  @ str r4, [r5, #0x30]
    .hword 0x2000  @ movs r0, #0
    .hword 0x62E8  @ str r0, [r5, #0x2c]
    .hword 0x480D  @ ldr r0, [pc, #0x34]
    .hword 0x21E0  @ movs r1, #0xe0
    .hword 0x0089  @ lsls r1, r1, #2
    .hword 0x2280  @ movs r2, #0x80
    .word 0xFE35F74A  @ bl #0xfff4ac6e
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x0164  @ lsls r4, r4, #5
    .hword 0x1824  @ adds r4, r4, r0
    .hword 0x3402  @ adds r4, #2
    .hword 0x3534  @ adds r5, #0x34
    .hword 0x210E  @ movs r1, #0xe
    .hword 0x8820  @ ldrh r0, [r4]
    .hword 0x8028  @ strh r0, [r5]
    .hword 0x3402  @ adds r4, #2
    .hword 0x3502  @ adds r5, #2
    .hword 0x3901  @ subs r1, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDAF8  @ bge #0xfffffff4
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x7550  @ strb r0, [r2, #0x15]
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x7640  @ strb r0, [r0, #0x19]
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x13F4  @ asrs r4, r6, #0xf
    .hword 0x080D  @ lsrs r5, r1, #0x20
    .hword 0x2860  @ cmp r0, #0x60
    .hword 0x0202  @ lsls r2, r0, #8

    .incbin "rom/fe7eu.gba", 0xB6458, 0xF0

    .global sub_80B68A4
    .type sub_80B68A4, %function
    .thumb
    .thumb_func
sub_80B68A4:  @ 0x080B6548 (jp 0x080B68A4, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x1C07  @ adds r7, r0, #0
    .hword 0x2018  @ movs r0, #0x18
    .hword 0x6AFC  @ ldr r4, [r7, #0x2c]
    .hword 0x3401  @ adds r4, #1
    .hword 0x62FC  @ str r4, [r7, #0x2c]
    .hword 0x4360  @ muls r0, r4, r0
    .hword 0x4360  @ muls r0, r4, r0
    .hword 0x25E1  @ movs r5, #0xe1
    .hword 0x012D  @ lsls r5, r5, #4
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xF979F00A  @ bl #0xa2f6
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x0120  @ lsls r0, r4, #4
    .hword 0x4360  @ muls r0, r4, r0
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xF973F00A  @ bl #0xa2ea
    .hword 0x2410  @ movs r4, #0x10
    .hword 0x1A24  @ subs r4, r4, r0
    .hword 0x6B38  @ ldr r0, [r7, #0x30]
    .hword 0x4A11  @ ldr r2, [pc, #0x44]
    .hword 0x2304  @ movs r3, #4
    .hword 0x5ED1  @ ldrsh r1, [r2, r3]
    .hword 0x1A40  @ subs r0, r0, r1
    .hword 0x6B79  @ ldr r1, [r7, #0x34]
    .hword 0x3901  @ subs r1, #1
    .hword 0x2306  @ movs r3, #6
    .hword 0x5ED2  @ ldrsh r2, [r2, r3]
    .hword 0x1A89  @ subs r1, r1, r2
    .hword 0x1C32  @ adds r2, r6, #0
    .word 0xF8CCF7C1  @ bl #0xfffc119c
    .hword 0x4B0C  @ ldr r3, [pc, #0x30]
    .hword 0x1C1A  @ adds r2, r3, #0
    .hword 0x323C  @ adds r2, #0x3c
    .hword 0x7811  @ ldrb r1, [r2]
    .hword 0x203F  @ movs r0, #0x3f
    .hword 0x4008  @ ands r0, r1
    .hword 0x2180  @ movs r1, #0x80
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7010  @ strb r0, [r2]
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x3044  @ adds r0, #0x44
    .hword 0x2100  @ movs r1, #0
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x3001  @ adds r0, #1
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x3001  @ adds r0, #1
    .hword 0x7004  @ strb r4, [r0]
    .hword 0x6AF8  @ ldr r0, [r7, #0x2c]
    .hword 0x283C  @ cmp r0, #0x3c
    .hword 0xDB00  @ blt #4
    .hword 0x62F9  @ str r1, [r7, #0x2c]
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x2870  @ cmp r0, #0x70
    .hword 0x0300  @ lsls r0, r0, #0xc

    .incbin "rom/fe7eu.gba", 0xB65C4, 0x44

    .global sub_80B6964
    .type sub_80B6964, %function
    .thumb
    .thumb_func
sub_80B6964:  @ 0x080B6608 (jp 0x080B6964, score 0.7778)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x4C06  @ ldr r4, [pc, #0x18]
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .word 0xF855F74E  @ bl #0xfff4e0ae
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFF41F74D  @ bl #0xfff4de86
    .hword 0x6305  @ str r5, [r0, #0x30]
    .hword 0x6346  @ str r6, [r0, #0x34]
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x7658  @ strb r0, [r3, #0x19]
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x7550  @ strb r0, [r2, #0x15]
    .hword 0x08DE  @ lsrs r6, r3, #3

