@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x0001B60C-0x0001C59C
    .syntax unified

    .global sub_801B5C4
    .type sub_801B5C4, %function
    .thumb
    .thumb_func
sub_801B5C4:  @ 0x0801B60C (jp 0x0801B5C4, score 0.8636)
    .hword 0xB510  @ push {r4, lr}
    .hword 0xB082  @ sub sp, #8
    .word 0xFC86F7E5  @ bl #0xfffe5910
    .hword 0x466A  @ mov r2, sp
    .hword 0x3202  @ adds r2, #2
    .hword 0xAC01  @ add r4, sp, #4
    .hword 0x4669  @ mov r1, sp
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFCB5F7E5  @ bl #0xfffe596e
    .hword 0x8821  @ ldrh r1, [r4]
    .hword 0x2001  @ movs r0, #1
    .hword 0x4008  @ ands r0, r1
    .hword 0x2103  @ movs r1, #3
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD100  @ bne #4
    .hword 0x2102  @ movs r1, #2
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xB002  @ add sp, #8
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_801B5F4
    .type sub_801B5F4, %function
    .thumb
    .thumb_func
sub_801B5F4:  @ 0x0801B63C (jp 0x0801B5F4, score 0.8636)
    .hword 0xB510  @ push {r4, lr}
    .hword 0xB082  @ sub sp, #8
    .word 0xFC6EF7E5  @ bl #0xfffe58e0
    .hword 0x466A  @ mov r2, sp
    .hword 0x3202  @ adds r2, #2
    .hword 0xAC01  @ add r4, sp, #4
    .hword 0x4669  @ mov r1, sp
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFC9DF7E5  @ bl #0xfffe593e
    .hword 0x8821  @ ldrh r1, [r4]
    .hword 0x2001  @ movs r0, #1
    .hword 0x4008  @ ands r0, r1
    .hword 0x2103  @ movs r1, #3
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x2102  @ movs r1, #2
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xB002  @ add sp, #8
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x1B66C, 0x2C

    .global sub_801B650
    .type sub_801B650, %function
    .thumb
    .thumb_func
sub_801B650:  @ 0x0801B698 (jp 0x0801B650, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2010  @ movs r0, #0x10
    .word 0xFB60F7E6  @ bl #0xfffe66c4
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .incbin "rom/fe7eu.gba", 0x1B6A4, 0x4

    .global sub_801B660
    .type sub_801B660, %function
    .thumb
    .thumb_func
sub_801B660:  @ 0x0801B6A8 (jp 0x0801B660, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x4646  @ mov r6, r8
    .hword 0xB440  @ push {r6}
    .hword 0xB083  @ sub sp, #0xc
    .hword 0x6AC1  @ ldr r1, [r0, #0x2c]
    .hword 0x4688  @ mov r8, r1
    .hword 0x6B04  @ ldr r4, [r0, #0x30]
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x3152  @ adds r1, #0x52
    .hword 0x880D  @ ldrh r5, [r1]
    .hword 0x6D46  @ ldr r6, [r0, #0x54]
    .hword 0xA801  @ add r0, sp, #4
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFEFBF7E9  @ bl #0xfffe9dfa
    .hword 0xA801  @ add r0, sp, #4
    .hword 0x1C31  @ adds r1, r6, #0
    .word 0xF84BF7EA  @ bl #0xfffea09a
    .hword 0x3502  @ adds r5, #2
    .hword 0x2000  @ movs r0, #0
    .hword 0x9000  @ str r0, [sp]
    .hword 0x4640  @ mov r0, r8
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x1C2A  @ adds r2, r5, #0
    .hword 0x2304  @ movs r3, #4
    .word 0xF9C0F02E  @ bl #0x2e384
    .hword 0x3401  @ adds r4, #1
    .hword 0x0164  @ lsls r4, r4, #5
    .hword 0x3401  @ adds r4, #1
    .hword 0x4444  @ add r4, r8
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x1824  @ adds r4, r4, r0
    .hword 0xA801  @ add r0, sp, #4
    .hword 0x1C21  @ adds r1, r4, #0
    .word 0xFF6DF7E9  @ bl #0xfffe9ede
    .hword 0x2003  @ movs r0, #3
    .word 0xFC86F7E5  @ bl #0xfffe5910
    .hword 0xB003  @ add sp, #0xc
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x2C60  @ cmp r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_801B6C4
    .type sub_801B6C4, %function
    .thumb
    .thumb_func
sub_801B6C4:  @ 0x0801B70C (jp 0x0801B6C4, score 0.913)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x4646  @ mov r6, r8
    .hword 0xB440  @ push {r6}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x4690  @ mov r8, r2
    .hword 0x1C1C  @ adds r4, r3, #0
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x2103  @ movs r1, #3
    .word 0xFEBFF7E8  @ bl #0xfffe8d82
    .hword 0x62C5  @ str r5, [r0, #0x2c]
    .hword 0x6306  @ str r6, [r0, #0x30]
    .hword 0x6544  @ str r4, [r0, #0x54]
    .hword 0x3052  @ adds r0, #0x52
    .hword 0x4641  @ mov r1, r8
    .hword 0x8001  @ strh r1, [r0]
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .word 0x08C8EB70  @ sbcs.w r8, r0, r8, lsl #3

    .global sub_801B6F4
    .type sub_801B6F4, %function
    .thumb
    .thumb_func
sub_801B6F4:  @ 0x0801B73C (jp 0x0801B6F4, score 0.8571)
    .hword 0xB500  @ push {lr}
    .word 0xFD2FF02E  @ bl #0x2ea62
    .word 0xFB3BF02E  @ bl #0x2e67a
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .word 0xFC50F02E  @ bl #0x2e8a4
    .hword 0x2002  @ movs r0, #2
    .hword 0x2100  @ movs r1, #0
    .word 0xFBF0F7E9  @ bl #0xfffe97e4
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x1148  @ asrs r0, r1, #5
    .hword 0x08C9  @ lsrs r1, r1, #3

    .global sub_801B718
    .type sub_801B718, %function
    .thumb
    .thumb_func
sub_801B718:  @ 0x0801B760 (jp 0x0801B718, score 0.75)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C0A  @ adds r2, r1, #0
    .hword 0x4B1E  @ ldr r3, [pc, #0x78]
    .hword 0x6818  @ ldr r0, [r3]
    .hword 0x88C1  @ ldrh r1, [r0, #6]
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD004  @ beq #0xc
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x313C  @ adds r1, #0x3c
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x3001  @ adds r0, #1
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x6818  @ ldr r0, [r3]
    .hword 0x88C1  @ ldrh r1, [r0, #6]
    .hword 0x2020  @ movs r0, #0x20
    .hword 0x4008  @ ands r0, r1
    .hword 0x1C15  @ adds r5, r2, #0
    .hword 0x353C  @ adds r5, #0x3c
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD002  @ beq #8
    .hword 0x7828  @ ldrb r0, [r5]
    .hword 0x3801  @ subs r0, #1
    .hword 0x7028  @ strb r0, [r5]
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2842  @ cmp r0, #0x42
    .hword 0xDD01  @ ble #6
    .hword 0x2042  @ movs r0, #0x42
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA01  @ bge #6
    .hword 0x2000  @ movs r0, #0
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x6818  @ ldr r0, [r3]
    .hword 0x88C1  @ ldrh r1, [r0, #6]
    .hword 0x2030  @ movs r0, #0x30
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00F  @ beq #0x22
    .hword 0x4C0A  @ ldr r4, [pc, #0x28]
    .hword 0x490B  @ ldr r1, [pc, #0x2c]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFBF5F7E9  @ bl #0xfffe97ee
    .hword 0x2000  @ movs r0, #0
    .hword 0x5628  @ ldrsb r0, [r5, r0]
    .word 0xF9E5F016  @ bl #0x163ce
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFBEDF7E9  @ bl #0xfffe97de
    .hword 0x2001  @ movs r0, #1
    .word 0xFC18F7E5  @ bl #0xfffe5834
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .word 0x08C7EFDC  @ vmul.i16 d16, d28, d7[0]
    .hword 0x2D2E  @ cmp r5, #0x2e
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x4580  @ cmp r8, r0
    .hword 0x082B  @ lsrs r3, r5, #0x20

    .global sub_801B7A4
    .type sub_801B7A4, %function
    .thumb
    .thumb_func
sub_801B7A4:  @ 0x0801B7EC (jp 0x0801B7A4, score 0.8667)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C0C  @ adds r4, r1, #0
    .word 0xF8CCF013  @ bl #0x1319c
    .hword 0x4905  @ ldr r1, [pc, #0x14]
    .hword 0x343C  @ adds r4, #0x3c
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x7388  @ strb r0, [r1, #0xe]
    .word 0xF8D8F013  @ bl #0x131b4
    .word 0xFB0EF7F7  @ bl #0xffff7620
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_801B7C8
    .type sub_801B7C8, %function
    .thumb
    .thumb_func
sub_801B7C8:  @ 0x0801B810 (jp 0x0801B7C8, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C0D  @ adds r5, r1, #0
    .word 0xFD4CF08F  @ bl #0x8fa9c
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C2E  @ adds r6, r5, #0
    .hword 0x363C  @ adds r6, #0x3c
    .hword 0x2000  @ movs r0, #0
    .hword 0x7030  @ strb r0, [r6]
    .word 0xFE61F7E7  @ bl #0xfffe7cc6
    .hword 0x2100  @ movs r1, #0
    .hword 0x42A1  @ cmp r1, r4
    .hword 0xDA0B  @ bge #0x1a
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD101  @ bne #6
    .hword 0x7031  @ strb r1, [r6]
    .hword 0xE007  @ b #0x12
    .hword 0x3101  @ adds r1, #1
    .hword 0x42A1  @ cmp r1, r4
    .hword 0xDA04  @ bge #0xc
    .hword 0x4288  @ cmp r0, r1
    .hword 0xD1FA  @ bne #0xfffffff8
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x303C  @ adds r0, #0x3c
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x1C2C  @ adds r4, r5, #0
    .hword 0x3434  @ adds r4, #0x34
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFE6DF7E9  @ bl #0xfffe9cde
    .hword 0x4910  @ ldr r1, [pc, #0x40]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x303C  @ adds r0, #0x3c
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x310C  @ adds r1, #0xc
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6800  @ ldr r0, [r0]
    .word 0xFB49F7F7  @ bl #0xffff7696
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xF975F7EA  @ bl #0xfffea2ee
    .hword 0x202C  @ movs r0, #0x2c
    .hword 0x5E29  @ ldrsh r1, [r5, r0]
    .hword 0x0149  @ lsls r1, r1, #5
    .hword 0x222A  @ movs r2, #0x2a
    .hword 0x5EA8  @ ldrsh r0, [r5, r2]
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x4804  @ ldr r0, [pc, #0x10]
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFEA3F7E9  @ bl #0xfffe9d4a
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x4944  @ ldr r1, [pc, #0x110]
    .hword 0x08DE  @ lsrs r6, r3, #3

    .incbin "rom/fe7eu.gba", 0x1B894, 0xBC

    .global sub_801B8FC
    .type sub_801B8FC, %function
    .thumb
    .thumb_func
sub_801B8FC:  @ 0x0801B950 (jp 0x0801B8FC, score 0.8125)
    .hword 0xB500  @ push {lr}
    .hword 0x4A0A  @ ldr r2, [pc, #0x28]
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x4282  @ cmp r2, r0
    .hword 0xD116  @ bne #0x30
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x3041  @ adds r0, #0x41
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0780  @ lsls r0, r0, #0x1e
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDB1C  @ blt #0x3c
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x303C  @ adds r0, #0x3c
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x8800  @ ldrh r0, [r0]
    .word 0xFBF3F0A3  @ bl #0xa37ea
    .hword 0xE011  @ b #0x26
    .hword 0x4944  @ ldr r1, [pc, #0x110]
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x4F94  @ ldr r7, [pc, #0x250]
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x303C  @ adds r0, #0x3c
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x2101  @ movs r1, #1
    .hword 0x2200  @ movs r2, #0
    .word 0xFF8CF7E7  @ bl #0xfffe7f1c
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_801B954
    .type sub_801B954, %function
    .thumb
    .thumb_func
sub_801B954:  @ 0x0801B9A8 (jp 0x0801B954, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFBF9F02E  @ bl #0x2e7f6
    .hword 0x2000  @ movs r0, #0
    .word 0xFA6AF7EB  @ bl #0xfffeb4d8
    .word 0xFA02F02E  @ bl #0x2e408
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x1B9C0, 0x154

    .global sub_801BAB4
    .type sub_801BAB4, %function
    .thumb
    .thumb_func
sub_801BAB4:  @ 0x0801BB14 (jp 0x0801BAB4, score 0.8125)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x480E  @ ldr r0, [pc, #0x38]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x8901  @ ldrh r1, [r0, #8]
    .hword 0x2031  @ movs r0, #0x31
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD044  @ beq #0x8c
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .word 0xFDC9F7E8  @ bl #0xfffe8b96
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x6DA0  @ ldr r0, [r4, #0x58]
    .hword 0x3001  @ adds r0, #1
    .hword 0x65A0  @ str r0, [r4, #0x58]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x1C31  @ adds r1, r6, #0
    .word 0xFFA7F7FF  @ bl #0xffffff52
    .hword 0x6DA0  @ ldr r0, [r4, #0x58]
    .hword 0x2107  @ movs r1, #7
    .word 0xFED3F0A4  @ bl #0xa4daa
    .hword 0x2806  @ cmp r0, #6
    .hword 0xD833  @ bhi #0x6a
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4903  @ ldr r1, [pc, #0xc]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x4687  @ mov pc, r0
    .word 0x08C7EFDC  @ vmul.i16 d16, d28, d7[0]
    .word 0x08C8EB68  @ sbc.w r8, r8, r8, lsl #3
    .hword 0xBB60  @ cbnz r0, #0x5c
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0xBB7C  @ cbnz r4, #0x62
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0xBB84  @ cbnz r4, #0x64
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0xBB8C  @ cbnz r4, #0x66
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0xBB94  @ cbnz r4, #0x68
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0xBB9C  @ cbnz r4, #0x6a
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0xBBA4  @ cbnz r4, #0x6c
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0xBBAC  @ cbnz r4, #0x6e
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0x2000  @ movs r0, #0
    .word 0xFC87F012  @ bl #0x12912
    .hword 0xE016  @ b #0x30
    .hword 0x2006  @ movs r0, #6
    .word 0xFC83F012  @ bl #0x1290a
    .hword 0xE012  @ b #0x28
    .hword 0x2001  @ movs r0, #1
    .word 0xFC7FF012  @ bl #0x12902
    .hword 0xE00E  @ b #0x20
    .hword 0x2002  @ movs r0, #2
    .word 0xFC7BF012  @ bl #0x128fa
    .hword 0xE00A  @ b #0x18
    .hword 0x2004  @ movs r0, #4
    .word 0xFC77F012  @ bl #0x128f2
    .hword 0xE006  @ b #0x10
    .hword 0x2003  @ movs r0, #3
    .word 0xFC73F012  @ bl #0x128ea
    .hword 0xE002  @ b #8
    .hword 0x2005  @ movs r0, #5
    .word 0xFC6FF012  @ bl #0x128e2
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x1BBBC, 0x74

    .global sub_801BBC4
    .type sub_801BBC4, %function
    .thumb
    .thumb_func
sub_801BBC4:  @ 0x0801BC30 (jp 0x0801BBC4, score 0.7188)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0xB099  @ sub sp, #0x64
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x1C0F  @ adds r7, r1, #0
    .hword 0x4C1D  @ ldr r4, [pc, #0x74]
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x88C1  @ ldrh r1, [r0, #6]
    .hword 0x2030  @ movs r0, #0x30
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD042  @ beq #0x88
    .word 0xFD67F084  @ bl #0x84ad2
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x88C1  @ ldrh r1, [r0, #6]
    .hword 0x2020  @ movs r0, #0x20
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD002  @ beq #8
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDB00  @ blt #4
    .hword 0x3D01  @ subs r5, #1
    .hword 0x4814  @ ldr r0, [pc, #0x50]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x88C1  @ ldrh r1, [r0, #6]
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD002  @ beq #8
    .hword 0x2D0B  @ cmp r5, #0xb
    .hword 0xDC00  @ bgt #4
    .hword 0x3501  @ adds r5, #1
    .hword 0x4668  @ mov r0, sp
    .word 0xFDE2F082  @ bl #0x82bc8
    .hword 0xA905  @ add r1, sp, #0x14
    .hword 0x2200  @ movs r2, #0
    .hword 0x4668  @ mov r0, sp
    .hword 0x301F  @ adds r0, #0x1f
    .hword 0x7002  @ strb r2, [r0]
    .hword 0x3801  @ subs r0, #1
    .hword 0x4288  @ cmp r0, r1
    .hword 0xDAFB  @ bge #0xfffffffa
    .hword 0x2400  @ movs r4, #0
    .hword 0x42AC  @ cmp r4, r5
    .hword 0xDA06  @ bge #0x10
    .hword 0x3401  @ adds r4, #1
    .hword 0x4668  @ mov r0, sp
    .hword 0x1C21  @ adds r1, r4, #0
    .word 0xFD50F084  @ bl #0x84aa4
    .hword 0x42AC  @ cmp r4, r5
    .hword 0xDBF8  @ blt #0xfffffff4
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD109  @ bne #0x16
    .hword 0x466A  @ mov r2, sp
    .hword 0x7B91  @ ldrb r1, [r2, #0xe]
    .hword 0x2002  @ movs r0, #2
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x4008  @ ands r0, r1
    .hword 0x7390  @ strb r0, [r2, #0xe]
    .hword 0xE007  @ b #0x12
    .hword 0x0000  @ movs r0, r0
    .word 0x08C7EFDC  @ vmul.i16 d16, d28, d7[0]
    .hword 0x4668  @ mov r0, sp
    .hword 0x7B81  @ ldrb r1, [r0, #0xe]
    .hword 0x2201  @ movs r2, #1
    .hword 0x4311  @ orrs r1, r2
    .hword 0x7381  @ strb r1, [r0, #0xe]
    .hword 0x4668  @ mov r0, sp
    .word 0xFDFCF082  @ bl #0x82bfc
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .word 0xFF7AF7FF  @ bl #0xfffffef8
    .hword 0x2000  @ movs r0, #0
    .hword 0xB019  @ add sp, #0x64
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC02  @ pop {r1}

    .incbin "rom/fe7eu.gba", 0x1BCD4, 0x8

    .global sub_801BC6C
    .type sub_801BC6C, %function
    .thumb
    .thumb_func
sub_801BC6C:  @ 0x0801BCDC (jp 0x0801BC6C, score 0.8)
    .hword 0xB500  @ push {lr}
    .word 0xF86DF02E  @ bl #0x2e0de
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .word 0xF982F02E  @ bl #0x2e308
    .hword 0x2007  @ movs r0, #7
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x10B8  @ asrs r0, r7, #2
    .hword 0x08C9  @ lsrs r1, r1, #3

    .incbin "rom/fe7eu.gba", 0x1BCF4, 0x2C

    .global sub_801BCB0
    .type sub_801BCB0, %function
    .thumb
    .thumb_func
sub_801BCB0:  @ 0x0801BD20 (jp 0x0801BCB0, score 0.8667)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4C07  @ ldr r4, [pc, #0x1c]
    .hword 0x2000  @ movs r0, #0
    .word 0xFF35F015  @ bl #0x15e6e
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF93DF7E9  @ bl #0xfffe927e
    .hword 0x2001  @ movs r0, #1
    .word 0xF968F7E5  @ bl #0xfffe52d4
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x2D2E  @ cmp r5, #0x2e
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_801BCD4
    .type sub_801BCD4, %function
    .thumb
    .thumb_func
sub_801BCD4:  @ 0x0801BD44 (jp 0x0801BCD4, score 0.875)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4813  @ ldr r0, [pc, #0x4c]
    .word 0xFE3CF7E5  @ bl #0xfffe5c7c
    .hword 0x4812  @ ldr r0, [pc, #0x48]
    .word 0xFD8FF7E5  @ bl #0xfffe5b22
    .word 0xFDF7F012  @ bl #0x12bf2
    .hword 0x2002  @ movs r0, #2
    .hword 0x2100  @ movs r1, #0
    .word 0xF8EBF7E9  @ bl #0xfffe91da
    .hword 0x480F  @ ldr r0, [pc, #0x3c]
    .word 0xF9F6F7EE  @ bl #0xfffee3f0
    .hword 0x480E  @ ldr r0, [pc, #0x38]
    .word 0xF941F02E  @ bl #0x2e286
    .hword 0x4C0E  @ ldr r4, [pc, #0x38]
    .hword 0x7922  @ ldrb r2, [r4, #4]
    .hword 0x2140  @ movs r1, #0x40
    .hword 0x4311  @ orrs r1, r2
    .hword 0x7121  @ strb r1, [r4, #4]
    .hword 0x490C  @ ldr r1, [pc, #0x30]
    .hword 0x2201  @ movs r2, #1
    .hword 0x4252  @ rsbs r2, r2, #0
    .word 0xFD6FF063  @ bl #0x63ae2
    .hword 0x7921  @ ldrb r1, [r4, #4]
    .hword 0x20BF  @ movs r0, #0xbf
    .hword 0x4008  @ ands r0, r1
    .hword 0x7120  @ strb r0, [r4, #4]
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .word 0xFECEF7E4  @ bl #0xfffe4da0
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x5545  @ strb r5, [r0, r5]
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0x54F5  @ strb r5, [r6, r3]
    .hword 0x0801  @ lsrs r1, r0, #0x20
    .hword 0x45B0  @ cmp r8, r6
    .hword 0x082B  @ lsrs r3, r5, #0x20
    .hword 0x1100  @ asrs r0, r0, #4
    .hword 0x08C9  @ lsrs r1, r1, #3
    .hword 0xBBB8  @ cbnz r0, #0x72
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xB000  @ add sp, #0
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x3CA0  @ subs r4, #0xa0
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_801BD40
    .type sub_801BD40, %function
    .thumb
    .thumb_func
sub_801BD40:  @ 0x0801BDB0 (jp 0x0801BD40, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0xB085  @ sub sp, #0x14
    .hword 0x6C40  @ ldr r0, [r0, #0x44]
    .hword 0x303C  @ adds r0, #0x3c
    .hword 0x2100  @ movs r1, #0
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .word 0xF923F7E5  @ bl #0xfffe524a
    .hword 0xA801  @ add r0, sp, #4
    .hword 0x2103  @ movs r1, #3
    .word 0xFE3DF082  @ bl #0x82c7e
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD106  @ bne #0x10
    .hword 0x9804  @ ldr r0, [sp, #0x10]
    .hword 0x0C01  @ lsrs r1, r0, #0x10
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x21FF  @ movs r1, #0xff
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00F  @ beq #0x22
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x21B7  @ movs r1, #0xb7
    .hword 0x2220  @ movs r2, #0x20
    .hword 0x2350  @ movs r3, #0x50
    .word 0xFFBEF7EA  @ bl #0xfffeaf80
    .hword 0x2081  @ movs r0, #0x81
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2001  @ movs r0, #1
    .hword 0x21B6  @ movs r1, #0xb6
    .hword 0xE00E  @ b #0x20
    .hword 0x0103  @ lsls r3, r0, #4
    .hword 0x0000  @ movs r0, r0
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x21B4  @ movs r1, #0xb4
    .hword 0x2220  @ movs r2, #0x20
    .hword 0x2350  @ movs r3, #0x50
    .word 0xFFAEF7EA  @ bl #0xfffeaf60
    .hword 0x2081  @ movs r0, #0x81
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2001  @ movs r0, #1
    .hword 0x21B2  @ movs r1, #0xb2
    .hword 0x22D0  @ movs r2, #0xd0
    .hword 0x2350  @ movs r3, #0x50
    .word 0xFFA5F7EA  @ bl #0xfffeaf4e
    .hword 0x2000  @ movs r0, #0
    .hword 0xB005  @ add sp, #0x14
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x0103  @ lsls r3, r0, #4
    .hword 0x0000  @ movs r0, r0

    .global sub_801BDC0
    .type sub_801BDC0, %function
    .thumb
    .thumb_func
sub_801BDC0:  @ 0x0801BE30 (jp 0x0801BDC0, score 0.7742)
    .hword 0xB500  @ push {lr}
    .hword 0x2000  @ movs r0, #0
    .word 0xF828F7EB  @ bl #0xfffeb054
    .hword 0x2001  @ movs r0, #1
    .word 0xF825F7EB  @ bl #0xfffeb04e
    .hword 0x4A0B  @ ldr r2, [pc, #0x2c]
    .hword 0x7851  @ ldrb r1, [r2, #1]
    .hword 0x2002  @ movs r0, #2
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x4008  @ ands r0, r1
    .hword 0x2103  @ movs r1, #3
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x4008  @ ands r0, r1
    .hword 0x3902  @ subs r1, #2
    .hword 0x4008  @ ands r0, r1
    .hword 0x3904  @ subs r1, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x3908  @ subs r1, #8
    .hword 0x4008  @ ands r0, r1
    .hword 0x7050  @ strb r0, [r2, #1]
    .hword 0x4904  @ ldr r1, [pc, #0x10]
    .hword 0x2000  @ movs r0, #0
    .hword 0x8008  @ strh r0, [r1]
    .word 0xF901F7E5  @ bl #0xfffe5206
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x2870  @ cmp r0, #0x70
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x2860  @ cmp r0, #0x60
    .hword 0x0202  @ lsls r2, r0, #8

    .incbin "rom/fe7eu.gba", 0x1BE74, 0x18C

    .global sub_801BF90
    .type sub_801BF90, %function
    .thumb
    .thumb_func
sub_801BF90:  @ 0x0801C000 (jp 0x0801BF90, score 0.7778)
    .hword 0xB500  @ push {lr}
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .word 0xFFF2F02D  @ bl #0x2dfe8
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x1124  @ asrs r4, r4, #4
    .hword 0x08C9  @ lsrs r1, r1, #3

    .global sub_801BFA4
    .type sub_801BFA4, %function
    .thumb
    .thumb_func
sub_801BFA4:  @ 0x0801C014 (jp 0x0801BFA4, score 0.7778)
    .hword 0xB500  @ push {lr}
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .word 0xFFE8F02D  @ bl #0x2dfd4
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x10DC  @ asrs r4, r3, #3
    .hword 0x08C9  @ lsrs r1, r1, #3

    .global sub_801BFB8
    .type sub_801BFB8, %function
    .thumb
    .thumb_func
sub_801BFB8:  @ 0x0801C028 (jp 0x0801BFB8, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2003  @ movs r0, #3
    .word 0xF8EEF089  @ bl #0x891e0
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x1C038, 0x4

    .global sub_801BFCC
    .type sub_801BFCC, %function
    .thumb
    .thumb_func
sub_801BFCC:  @ 0x0801C03C (jp 0x0801BFCC, score 0.8462)
    .hword 0xB500  @ push {lr}
    .hword 0x313D  @ adds r1, #0x3d
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD104  @ bne #0xc
    .hword 0x2004  @ movs r0, #4
    .word 0xFA00F085  @ bl #0x85404
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xE000  @ b #4
    .hword 0x2008  @ movs r0, #8
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_801BFE8
    .type sub_801BFE8, %function
    .thumb
    .thumb_func
sub_801BFE8:  @ 0x0801C058 (jp 0x0801BFE8, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2004  @ movs r0, #4
    .word 0xFB38F085  @ bl #0x85674
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2102  @ movs r1, #2
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_801C000
    .type sub_801C000, %function
    .thumb
    .thumb_func
sub_801C000:  @ 0x0801C070 (jp 0x0801C000, score 0.8)
    .hword 0xB500  @ push {lr}
    .hword 0x313D  @ adds r1, #0x3d
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD001  @ beq #6
    .hword 0x2008  @ movs r0, #8
    .hword 0xE00C  @ b #0x1c
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .word 0xFB1EF7E8  @ bl #0xfffe8640
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD001  @ beq #6
    .word 0xFC80F012  @ bl #0x12904
    .hword 0x2004  @ movs r0, #4
    .word 0xFA89F085  @ bl #0x85516
    .word 0xFED7F7F6  @ bl #0xffff6db2
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0xE324  @ b #0x64c
    .hword 0x08C8  @ lsrs r0, r1, #3

    .global sub_801C030
    .type sub_801C030, %function
    .thumb
    .thumb_func
sub_801C030:  @ 0x0801C0A0 (jp 0x0801C030, score 0.7895)
    .hword 0xB500  @ push {lr}
    .hword 0x313D  @ adds r1, #0x3d
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD001  @ beq #6
    .hword 0x2008  @ movs r0, #8
    .hword 0xE009  @ b #0x16
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .word 0xFB06F7E8  @ bl #0xfffe8610
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD001  @ beq #6
    .word 0xFC68F012  @ bl #0x128d4
    .word 0xFED4F7F6  @ bl #0xffff6dac
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0xE324  @ b #0x64c
    .hword 0x08C8  @ lsrs r0, r1, #3

    .global sub_801C05C
    .type sub_801C05C, %function
    .thumb
    .thumb_func
sub_801C05C:  @ 0x0801C0CC (jp 0x0801C05C, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2003  @ movs r0, #3
    .word 0xFAFEF085  @ bl #0x85600
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2102  @ movs r1, #2
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .incbin "rom/fe7eu.gba", 0x1C0E4, 0xFC

    .global sub_801C164
    .type sub_801C164, %function
    .thumb
    .thumb_func
sub_801C164:  @ 0x0801C1E0 (jp 0x0801C164, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFDDBF7F6  @ bl #0xffff6bba
    .hword 0x2007  @ movs r0, #7
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_801C170
    .type sub_801C170, %function
    .thumb
    .thumb_func
sub_801C170:  @ 0x0801C1EC (jp 0x0801C170, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x20C0  @ movs r0, #0xc0
    .hword 0x0080  @ lsls r0, r0, #2
    .word 0xFDAFF7E6  @ bl #0xfffe6b62
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_801C180
    .type sub_801C180, %function
    .thumb
    .thumb_func
sub_801C180:  @ 0x0801C1FC (jp 0x0801C180, score 0.875)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0xB083  @ sub sp, #0xc
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0x4669  @ mov r1, sp
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0xC81C  @ ldm r0!, {r2, r3, r4}
    .hword 0xC11C  @ stm r1!, {r2, r3, r4}
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x303C  @ adds r0, #0x3c
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD009  @ beq #0x16
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x3043  @ adds r0, #0x43
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0740  @ lsls r0, r0, #0x1d
    .hword 0xE008  @ b #0x14
    .hword 0x0000  @ movs r0, r0
    .hword 0x45BC  @ cmp ip, r7
    .hword 0x082B  @ lsrs r3, r5, #0x20
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x4819  @ ldr r0, [pc, #0x64]
    .hword 0x3042  @ adds r0, #0x42
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x05C0  @ lsls r0, r0, #0x17
    .hword 0x0F86  @ lsrs r6, r0, #0x1e
    .hword 0x1C2C  @ adds r4, r5, #0
    .hword 0x3434  @ adds r4, #0x34
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF974F7E9  @ bl #0xfffe92ec
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x303C  @ adds r0, #0x3c
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x4B13  @ ldr r3, [pc, #0x4c]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x4B12  @ ldr r3, [pc, #0x48]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2108  @ movs r1, #8
    .hword 0x2200  @ movs r2, #0
    .word 0xFC80F7E9  @ bl #0xfffe9904
    .hword 0x00B0  @ lsls r0, r6, #2
    .hword 0x4468  @ add r0, sp, r0
    .hword 0x6800  @ ldr r0, [r0]
    .word 0xFE49F7F6  @ bl #0xffff6c96
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2120  @ movs r1, #0x20
    .hword 0x2202  @ movs r2, #2
    .word 0xFC75F7E9  @ bl #0xfffe98ee
    .hword 0x202C  @ movs r0, #0x2c
    .hword 0x5E29  @ ldrsh r1, [r5, r0]
    .hword 0x0149  @ lsls r1, r1, #5
    .hword 0x222A  @ movs r2, #0x2a
    .hword 0x5EA8  @ ldrsh r0, [r5, r2]
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF9A3F7E9  @ bl #0xfffe934a
    .hword 0x2000  @ movs r0, #0
    .hword 0xB003  @ add sp, #0xc
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x45CC  @ cmp ip, sb
    .hword 0x082B  @ lsrs r3, r5, #0x20
    .hword 0x45C8  @ cmp r8, sb
    .hword 0x082B  @ lsrs r3, r5, #0x20

    .incbin "rom/fe7eu.gba", 0x1C2A0, 0xB8

    .global sub_801C2D8
    .type sub_801C2D8, %function
    .thumb
    .thumb_func
sub_801C2D8:  @ 0x0801C358 (jp 0x0801C2D8, score 0.8182)
    .hword 0xB500  @ push {lr}
    .word 0xFD61F7F6  @ bl #0xffff6ac6
    .hword 0x4804  @ ldr r0, [pc, #0x10]
    .word 0xF9AEF7E8  @ bl #0xfffe8360
    .hword 0x210F  @ movs r1, #0xf
    .word 0xF9EFF7E8  @ bl #0xfffe83e2
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0xDCD0  @ bgt #0xffffffa4
    .hword 0x08C8  @ lsrs r0, r1, #3

    .incbin "rom/fe7eu.gba", 0x1C374, 0x11C

    .global sub_801C43C
    .type sub_801C43C, %function
    .thumb
    .thumb_func
sub_801C43C:  @ 0x0801C490 (jp 0x0801C43C, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x4931  @ ldr r1, [pc, #0xc4]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x88C2  @ ldrh r2, [r0, #6]
    .hword 0x20CD  @ movs r0, #0xcd
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4010  @ ands r0, r2
    .hword 0x1C0C  @ adds r4, r1, #0
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD068  @ beq #0xd4
    .hword 0x2020  @ movs r0, #0x20
    .hword 0x4010  @ ands r0, r2
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD011  @ beq #0x26
    .hword 0x4B2B  @ ldr r3, [pc, #0xac]
    .hword 0x8D9A  @ ldrh r2, [r3, #0x2c]
    .hword 0x04D0  @ lsls r0, r2, #0x13
    .hword 0x0DC0  @ lsrs r0, r0, #0x17
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDD0B  @ ble #0x1a
    .hword 0x1E41  @ subs r1, r0, #1
    .hword 0x29FF  @ cmp r1, #0xff
    .hword 0xDD00  @ ble #4
    .hword 0x21FF  @ movs r1, #0xff
    .hword 0x4F27  @ ldr r7, [pc, #0x9c]
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x4001  @ ands r1, r0
    .hword 0x0109  @ lsls r1, r1, #4
    .hword 0x4826  @ ldr r0, [pc, #0x98]
    .hword 0x4010  @ ands r0, r2
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8598  @ strh r0, [r3, #0x2c]
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x88C1  @ ldrh r1, [r0, #6]
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00F  @ beq #0x22
    .hword 0x4B1F  @ ldr r3, [pc, #0x7c]
    .hword 0x8D9A  @ ldrh r2, [r3, #0x2c]
    .hword 0x04D0  @ lsls r0, r2, #0x13
    .hword 0x0DC0  @ lsrs r0, r0, #0x17
    .hword 0x1C41  @ adds r1, r0, #1
    .hword 0x29FF  @ cmp r1, #0xff
    .hword 0xDD00  @ ble #4
    .hword 0x21FF  @ movs r1, #0xff
    .hword 0x4F1C  @ ldr r7, [pc, #0x70]
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x4001  @ ands r1, r0
    .hword 0x0109  @ lsls r1, r1, #4
    .hword 0x481B  @ ldr r0, [pc, #0x6c]
    .hword 0x4010  @ ands r0, r2
    .hword 0x4308  @ orrs r0, r1
    .hword 0x8598  @ strh r0, [r3, #0x2c]
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x88C1  @ ldrh r1, [r0, #6]
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD006  @ beq #0x10
    .hword 0x4814  @ ldr r0, [pc, #0x50]
    .hword 0x302B  @ adds r0, #0x2b
    .hword 0x7802  @ ldrb r2, [r0]
    .hword 0x2102  @ movs r1, #2
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x4011  @ ands r1, r2
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x6823  @ ldr r3, [r4]
    .hword 0x88D9  @ ldrh r1, [r3, #6]
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD005  @ beq #0xe
    .hword 0x480D  @ ldr r0, [pc, #0x34]
    .hword 0x302B  @ adds r0, #0x2b
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x2201  @ movs r2, #1
    .hword 0x4311  @ orrs r1, r2
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x88D9  @ ldrh r1, [r3, #6]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD018  @ beq #0x34
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x332B  @ adds r3, #0x2b
    .hword 0x781A  @ ldrb r2, [r3]
    .hword 0x0911  @ lsrs r1, r2, #4
    .hword 0x290A  @ cmp r1, #0xa
    .hword 0xDC0E  @ bgt #0x20
    .hword 0x3101  @ adds r1, #1
    .hword 0x0109  @ lsls r1, r1, #4
    .hword 0x200F  @ movs r0, #0xf
    .hword 0x4010  @ ands r0, r2
    .hword 0x4308  @ orrs r0, r1
    .hword 0xE00A  @ b #0x18
    .hword 0x0000  @ movs r0, r0
    .word 0x08C7EFDC  @ vmul.i16 d16, d28, d7[0]
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x01FF  @ lsls r7, r7, #7
    .hword 0x0000  @ movs r0, r0
    .hword 0xE00F  @ b #0x22
    .byte 0xFF
    .hword 0x0FFF  @ lsrs r7, r7, #0x1f
    .hword 0x1020  @ asrs r0, r4, #0x20
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x2870  @ cmp r0, #0x70
    .hword 0x311C  @ adds r1, #0x1c
    .byte 0x1C
    .word 0xFEFDF7FF  @ bl #0xfffffdfe
    .hword 0x2000  @ movs r0, #0
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x2017  @ movs r0, #0x17
    .hword 0x4770  @ bx lr

    .global sub_801C558
    .type sub_801C558, %function
    .thumb
    .thumb_func
sub_801C558:  @ 0x0801C588 (jp 0x0801C558, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x2103  @ movs r1, #3
    .word 0xFF87F7E7  @ bl #0xfffe7f12
    .hword 0x2017  @ movs r0, #0x17
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .byte 0x88
    .hword 0xC8EB  @ ldm r0, {r0, r1, r3, r5, r6, r7}
    .byte 0x08

