@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x0007CF1C-0x0007E2E0
    .syntax unified

    .global sub_807DAF4
    .type sub_807DAF4, %function
    .thumb
    .thumb_func
sub_807DAF4:  @ 0x0807CF1C (jp 0x0807DAF4, score 0.8095)
    .hword 0xB500  @ push {lr}
    .hword 0x2008  @ movs r0, #8
    .word 0xFD82F7FC  @ bl #0xffffcb08
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD001  @ beq #6
    .hword 0x2000  @ movs r0, #0
    .hword 0xE008  @ b #0x14
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x6B80  @ ldr r0, [r0, #0x38]
    .hword 0x7981  @ ldrb r1, [r0, #6]
    .hword 0x2025  @ movs r0, #0x25
    .hword 0x4041  @ eors r1, r0
    .hword 0x4248  @ rsbs r0, r1, #0
    .hword 0x4308  @ orrs r0, r1
    .hword 0x0FC0  @ lsrs r0, r0, #0x1f
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0xE3E0  @ b #0x7c4
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_807DB3C
    .type sub_807DB3C, %function
    .thumb
    .thumb_func
sub_807DB3C:  @ 0x0807CF48 (jp 0x0807DB3C, score 0.9688)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x2500  @ movs r5, #0
    .hword 0x2085  @ movs r0, #0x85
    .word 0xFD6BF7FC  @ bl #0xffffcada
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD008  @ beq #0x14
    .hword 0x2084  @ movs r0, #0x84
    .word 0xFD65F7FC  @ bl #0xffffcace
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2574  @ movs r5, #0x74
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD008  @ beq #0x14
    .hword 0x2573  @ movs r5, #0x73
    .hword 0xE008  @ b #0x14
    .hword 0x2084  @ movs r0, #0x84
    .word 0xFD5CF7FC  @ bl #0xffffcabc
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x2575  @ movs r5, #0x75
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD00B  @ beq #0x1a
    .hword 0x202D  @ movs r0, #0x2d
    .word 0xF8E1F79B  @ bl #0xfff9b1c6
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFA81F799  @ bl #0xfff99506
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFD59F79A  @ bl #0xfff9aab6
    .hword 0xE00F  @ b #0x22
    .word 0xFC04F023  @ bl #0x2380c

    .incbin "rom/fe7eu.gba", 0x7CF98, 0x26

    .global sub_807DB8C
    .type sub_807DB8C, %function
    .thumb
    .thumb_func
sub_807DB8C:  @ 0x0807CFBE (jp 0x0807DB8C, score 0.8333)
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .hword 0x282F  @ cmp r0, #0x2f
    .hword 0xD00A  @ beq #0x18
    .hword 0x2830  @ cmp r0, #0x30
    .hword 0xD008  @ beq #0x14
    .hword 0x2831  @ cmp r0, #0x31
    .hword 0xD006  @ beq #0x10
    .hword 0x282E  @ cmp r0, #0x2e
    .hword 0xD004  @ beq #0xc
    .hword 0x2000  @ movs r0, #0
    .hword 0xE003  @ b #0xa
    .hword 0x0000  @ movs r0, r0
    .hword 0x4690  @ mov r8, r2
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x2001  @ movs r0, #1

    .incbin "rom/fe7eu.gba", 0x7CFE2, 0xDE

    .global sub_807DCD0
    .type sub_807DCD0, %function
    .thumb
    .thumb_func
sub_807DCD0:  @ 0x0807D0C0 (jp 0x0807DCD0, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x200E  @ movs r0, #0xe
    .word 0xFCB0F7FC  @ bl #0xffffc964
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x4241  @ rsbs r1, r0, #0
    .hword 0x4301  @ orrs r1, r0
    .hword 0x0FCC  @ lsrs r4, r1, #0x1f
    .hword 0x200F  @ movs r0, #0xf
    .word 0xFCA8F7FC  @ bl #0xffffc954
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x2010  @ movs r0, #0x10
    .word 0xFCA1F7FC  @ bl #0xffffc946
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD002  @ beq #8
    .hword 0x1C60  @ adds r0, r4, #1
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E04  @ lsrs r4, r0, #0x18
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807DD0C
    .type sub_807DD0C, %function
    .thumb
    .thumb_func
sub_807DD0C:  @ 0x0807D0FC (jp 0x0807DD0C, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFFDFF7FF  @ bl #0xffffffc2
    .hword 0x2100  @ movs r1, #0
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD100  @ bne #4
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807DD24
    .type sub_807DD24, %function
    .thumb
    .thumb_func
sub_807DD24:  @ 0x0807D114 (jp 0x0807DD24, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFFD3F7FF  @ bl #0xffffffaa
    .hword 0x2100  @ movs r1, #0
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD800  @ bhi #4
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807DD3C
    .type sub_807DD3C, %function
    .thumb
    .thumb_func
sub_807DD3C:  @ 0x0807D12C (jp 0x0807DD3C, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFFC7F7FF  @ bl #0xffffff92
    .hword 0x2100  @ movs r1, #0
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .hword 0x2802  @ cmp r0, #2
    .hword 0xD800  @ bhi #4
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .incbin "rom/fe7eu.gba", 0x7D144, 0x30

    .global sub_807DDDC
    .type sub_807DDDC, %function
    .thumb
    .thumb_func
sub_807DDDC:  @ 0x0807D174 (jp 0x0807DDDC, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2026  @ movs r0, #0x26
    .word 0xFFE4F79A  @ bl #0xfff9afcc
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00C  @ beq #0x1c
    .hword 0x7A00  @ ldrb r0, [r0, #8]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x2806  @ cmp r0, #6
    .hword 0xDD07  @ ble #0x12
    .hword 0x200A  @ movs r0, #0xa
    .word 0xFC4CF7FC  @ bl #0xffffc89c
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD001  @ beq #6
    .hword 0x2001  @ movs r0, #1
    .hword 0xE000  @ b #4
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .incbin "rom/fe7eu.gba", 0x7D1A0, 0x30

    .global sub_807DE6C
    .type sub_807DE6C, %function
    .thumb
    .thumb_func
sub_807DE6C:  @ 0x0807D1D0 (jp 0x0807DE6C, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2001  @ movs r0, #1
    .word 0xFFB6F79A  @ bl #0xfff9af70
    .hword 0x2106  @ movs r1, #6
    .hword 0x2202  @ movs r2, #2
    .word 0xFC08F79A  @ bl #0xfff9a814
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_807DEC0
    .type sub_807DEC0, %function
    .thumb
    .thumb_func
sub_807DEC0:  @ 0x0807D1E4 (jp 0x0807DEC0, score 0.8571)
    .hword 0xB500  @ push {lr}
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x7BC0  @ ldrb r0, [r0, #0xf]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10E  @ bne #0x20
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x6840  @ ldr r0, [r0, #4]
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .hword 0x283C  @ cmp r0, #0x3c
    .hword 0xD00E  @ beq #0x20
    .hword 0x283D  @ cmp r0, #0x3d
    .hword 0xD00C  @ beq #0x1c
    .word 0xFE73F783  @ bl #0xfff83cea
    .hword 0x210B  @ movs r1, #0xb
    .word 0xF9EEF043  @ bl #0x433e0
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD005  @ beq #0xe
    .hword 0x2000  @ movs r0, #0
    .hword 0xE004  @ b #0xc
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x4690  @ mov r8, r2
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807DF0C
    .type sub_807DF0C, %function
    .thumb
    .thumb_func
sub_807DF0C:  @ 0x0807D220 (jp 0x0807DF0C, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x2500  @ movs r5, #0
    .hword 0x2401  @ movs r4, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFF7CF79B  @ bl #0xfff9befc
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD008  @ beq #0x14
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD005  @ beq #0xe
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .word 0xF982F023  @ bl #0x23308
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x0C05  @ lsrs r5, r0, #0x10
    .hword 0x3401  @ adds r4, #1
    .hword 0x2C3F  @ cmp r4, #0x3f
    .hword 0xDDEE  @ ble #0xffffffe0
    .hword 0x4802  @ ldr r0, [pc, #8]
    .hword 0x8005  @ strh r5, [r0]
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x4A8C  @ ldr r2, [pc, #0x230]
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global sub_807DF44
    .type sub_807DF44, %function
    .thumb
    .thumb_func
sub_807DF44:  @ 0x0807D258 (jp 0x0807DF44, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x2500  @ movs r5, #0
    .hword 0x2401  @ movs r4, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFF60F79B  @ bl #0xfff9bec4
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD006  @ beq #0x10
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD003  @ beq #0xa
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .word 0xF966F023  @ bl #0x232d0
    .hword 0x182D  @ adds r5, r5, r0
    .hword 0x3401  @ adds r4, #1
    .hword 0x2C3F  @ cmp r4, #0x3f
    .hword 0xDDF0  @ ble #0xffffffe4
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x1A2D  @ subs r5, r5, r0
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x4285  @ cmp r5, r0
    .hword 0xDC05  @ bgt #0xe
    .hword 0x2000  @ movs r0, #0
    .hword 0xE004  @ b #0xc
    .hword 0x4A8C  @ ldr r2, [pc, #0x230]
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x02BB  @ lsls r3, r7, #0xa
    .hword 0x0000  @ movs r0, r0
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807DF88
    .type sub_807DF88, %function
    .thumb
    .thumb_func
sub_807DF88:  @ 0x0807D29C (jp 0x0807DF88, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x2500  @ movs r5, #0
    .hword 0x2401  @ movs r4, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFF3EF79B  @ bl #0xfff9be80
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD014  @ beq #0x2c
    .hword 0x6813  @ ldr r3, [r2]
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xD011  @ beq #0x26
    .hword 0x68D0  @ ldr r0, [r2, #0xc]
    .hword 0x2104  @ movs r1, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10C  @ bne #0x1c
    .hword 0x7919  @ ldrb r1, [r3, #4]
    .hword 0x1E48  @ subs r0, r1, #1
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD901  @ bls #6
    .hword 0x292D  @ cmp r1, #0x2d
    .hword 0xD104  @ bne #0xc
    .hword 0x2008  @ movs r0, #8
    .hword 0x5610  @ ldrsb r0, [r2, r0]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x0C05  @ lsrs r5, r0, #0x10
    .hword 0x3401  @ adds r4, #1
    .hword 0x2C3F  @ cmp r4, #0x3f
    .hword 0xDDE1  @ ble #0xffffffc6
    .hword 0x2D31  @ cmp r5, #0x31
    .hword 0xD801  @ bhi #6
    .hword 0x2000  @ movs r0, #0
    .hword 0xE000  @ b #4
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807DFDC
    .type sub_807DFDC, %function
    .thumb
    .thumb_func
sub_807DFDC:  @ 0x0807D2F0 (jp 0x0807DFDC, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0xB081  @ sub sp, #4
    .hword 0x2103  @ movs r1, #3
    .hword 0x9100  @ str r1, [sp]
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x2201  @ movs r2, #1
    .hword 0x2302  @ movs r3, #2
    .word 0xFFE9F7A1  @ bl #0xfffa1fd6
    .hword 0xB001  @ add sp, #4
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .incbin "rom/fe7eu.gba", 0x7D308, 0x24

    .global sub_807E074
    .type sub_807E074, %function
    .thumb
    .thumb_func
sub_807E074:  @ 0x0807D32C (jp 0x0807E074, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFD63F7A6  @ bl #0xfffa6aca
    .hword 0x2200  @ movs r2, #0
    .hword 0x4903  @ ldr r1, [pc, #0xc]
    .hword 0x4288  @ cmp r0, r1
    .hword 0xDD00  @ ble #4
    .hword 0x2201  @ movs r2, #1
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x4E1F  @ ldr r6, [pc, #0x7c]
    .hword 0x0000  @ movs r0, r0

    .global sub_807E090
    .type sub_807E090, %function
    .thumb
    .thumb_func
sub_807E090:  @ 0x0807D348 (jp 0x0807E090, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x4802  @ ldr r0, [pc, #8]
    .word 0xFD1EF7FC  @ bl #0xffffca40
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x4E20  @ ldr r6, [pc, #0x80]
    .hword 0x0000  @ movs r0, r0

    .global sub_807E0A0
    .type sub_807E0A0, %function
    .thumb
    .thumb_func
sub_807E0A0:  @ 0x0807D358 (jp 0x0807E0A0, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2007  @ movs r0, #7
    .word 0xFB64F7FC  @ bl #0xffffc6cc
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD007  @ beq #0x12
    .hword 0x200D  @ movs r0, #0xd
    .word 0xFB5EF7FC  @ bl #0xffffc6c0
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD101  @ bne #6
    .hword 0x2001  @ movs r0, #1
    .hword 0xE000  @ b #4
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807E0D4
    .type sub_807E0D4, %function
    .thumb
    .thumb_func
sub_807E0D4:  @ 0x0807D37C (jp 0x0807E0D4, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4647  @ mov r7, r8
    .hword 0xB480  @ push {r7}
    .hword 0xB081  @ sub sp, #4
    .hword 0x4680  @ mov r8, r0
    .hword 0x2200  @ movs r2, #0
    .hword 0x2600  @ movs r6, #0
    .hword 0x2401  @ movs r4, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x9200  @ str r2, [sp]
    .word 0xFEC8F79B  @ bl #0xfff9bd94
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C67  @ adds r7, r4, #1
    .hword 0x9A00  @ ldr r2, [sp]
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD01D  @ beq #0x3e
    .hword 0x6828  @ ldr r0, [r5]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD01A  @ beq #0x38
    .hword 0x68E8  @ ldr r0, [r5, #0xc]
    .hword 0x2104  @ movs r1, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD115  @ bne #0x2e
    .hword 0x0050  @ lsls r0, r2, #1
    .hword 0x4642  @ mov r2, r8
    .hword 0x1881  @ adds r1, r0, r2
    .hword 0x8808  @ ldrh r0, [r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00E  @ beq #0x20
    .hword 0x1C0C  @ adds r4, r1, #0
    .hword 0x6828  @ ldr r0, [r5]
    .hword 0x8821  @ ldrh r1, [r4]
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .hword 0x4288  @ cmp r0, r1
    .hword 0xD104  @ bne #0xc
    .hword 0x0608  @ lsls r0, r1, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .word 0xF8B9F023  @ bl #0x23176
    .hword 0x1836  @ adds r6, r6, r0
    .hword 0x3402  @ adds r4, #2
    .hword 0x8820  @ ldrh r0, [r4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD1F1  @ bne #0xffffffe6
    .hword 0x2200  @ movs r2, #0
    .hword 0x1C3C  @ adds r4, r7, #0
    .hword 0x2C3F  @ cmp r4, #0x3f
    .hword 0xDDD5  @ ble #0xffffffae
    .hword 0x0430  @ lsls r0, r6, #0x10
    .hword 0x0C00  @ lsrs r0, r0, #0x10
    .hword 0xB001  @ add sp, #4
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807E14C
    .type sub_807E14C, %function
    .thumb
    .thumb_func
sub_807E14C:  @ 0x0807D3F0 (jp 0x0807E14C, score 0.8)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .word 0xFFC2F7FF  @ bl #0xffffff88
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .word 0xFFBEF7FF  @ bl #0xffffff80
    .hword 0x0424  @ lsls r4, r4, #0x10
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4284  @ cmp r4, r0
    .hword 0xD805  @ bhi #0xe
    .hword 0x2000  @ movs r0, #0
    .hword 0xE004  @ b #0xc
    .hword 0x853C  @ strh r4, [r7, #0x28]
    .hword 0x08DB  @ lsrs r3, r3, #3
    .hword 0x8546  @ strh r6, [r0, #0x2a]
    .hword 0x08DB  @ lsrs r3, r3, #3
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807E188
    .type sub_807E188, %function
    .thumb
    .thumb_func
sub_807E188:  @ 0x0807D41C (jp 0x0807E188, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x2009  @ movs r0, #9
    .word 0xFB02F7FC  @ bl #0xffffc608
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x4241  @ rsbs r1, r0, #0
    .hword 0x4301  @ orrs r1, r0
    .hword 0x0FCC  @ lsrs r4, r1, #0x1f
    .hword 0x200A  @ movs r0, #0xa
    .word 0xFAFAF7FC  @ bl #0xffffc5f8
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x200B  @ movs r0, #0xb
    .word 0xFAF3F7FC  @ bl #0xffffc5ea
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x2000  @ movs r0, #0
    .hword 0x2C01  @ cmp r4, #1
    .hword 0xDC00  @ bgt #4
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807E1E8
    .type sub_807E1E8, %function
    .thumb
    .thumb_func
sub_807E1E8:  @ 0x0807D458 (jp 0x0807E1E8, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x2009  @ movs r0, #9
    .word 0xFAE4F7FC  @ bl #0xffffc5cc
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x4241  @ rsbs r1, r0, #0
    .hword 0x4301  @ orrs r1, r0
    .hword 0x0FCC  @ lsrs r4, r1, #0x1f
    .hword 0x200A  @ movs r0, #0xa
    .word 0xFADCF7FC  @ bl #0xffffc5bc
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x200B  @ movs r0, #0xb
    .word 0xFAD5F7FC  @ bl #0xffffc5ae
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x200C  @ movs r0, #0xc
    .word 0xFACEF7FC  @ bl #0xffffc5a0
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x200D  @ movs r0, #0xd
    .word 0xFAC7F7FC  @ bl #0xffffc592
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x200E  @ movs r0, #0xe
    .word 0xFAC0F7FC  @ bl #0xffffc584
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x200F  @ movs r0, #0xf
    .word 0xFAB9F7FC  @ bl #0xffffc576
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x2010  @ movs r0, #0x10
    .word 0xFAB2F7FC  @ bl #0xffffc568
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x2011  @ movs r0, #0x11
    .word 0xFAABF7FC  @ bl #0xffffc55a
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x2C03  @ cmp r4, #3
    .hword 0xDD01  @ ble #6
    .hword 0x2000  @ movs r0, #0
    .hword 0xE000  @ b #4
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807E2F0
    .type sub_807E2F0, %function
    .thumb
    .thumb_func
sub_807E2F0:  @ 0x0807D4EA (jp 0x0807E2F0, score 0.8125)
    .hword 0x0000  @ movs r0, r0
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD118  @ bne #0x34
    .hword 0x205B  @ movs r0, #0x5b
    .word 0xFE21F79A  @ bl #0xfff9ac46
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x5641  @ ldrsb r1, [r0, r1]
    .hword 0x0109  @ lsls r1, r1, #4
    .hword 0x4B0A  @ ldr r3, [pc, #0x28]
    .hword 0x250C  @ movs r5, #0xc
    .hword 0x5F5A  @ ldrsh r2, [r3, r5]
    .hword 0x3A08  @ subs r2, #8
    .hword 0x1A89  @ subs r1, r1, r2
    .hword 0x2211  @ movs r2, #0x11
    .hword 0x5682  @ ldrsb r2, [r0, r2]
    .hword 0x0112  @ lsls r2, r2, #4
    .hword 0x250E  @ movs r5, #0xe
    .hword 0x5F58  @ ldrsh r0, [r3, r5]
    .hword 0x3808  @ subs r0, #8
    .hword 0x1A12  @ subs r2, r2, r0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFE7FF7A3  @ bl #0xfffa3d02
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x314D  @ adds r1, #0x4d
    .hword 0x2001  @ movs r0, #1
    .hword 0x7008  @ strb r0, [r1]
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xBBB8  @ cbnz r0, #0x72
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_807E340
    .type sub_807E340, %function
    .thumb
    .thumb_func
sub_807E340:  @ 0x0807D538 (jp 0x0807E340, score 0.8519)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .word 0xFCF0F783  @ bl #0xfff839e4
    .hword 0x2201  @ movs r2, #1
    .hword 0x4010  @ ands r0, r2
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD110  @ bne #0x24
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x314C  @ adds r1, #0x4c
    .hword 0x8808  @ ldrh r0, [r1]
    .hword 0x3001  @ adds r0, #1
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x4903  @ ldr r1, [pc, #0xc]
    .hword 0x4010  @ ands r0, r2
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD004  @ beq #0xc
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .hword 0x3801  @ subs r0, #1
    .hword 0xE003  @ b #0xa
    .hword 0xBBB8  @ cbnz r0, #0x72
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .hword 0x3001  @ adds r0, #1
    .hword 0x8188  @ strh r0, [r1, #0xc]
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_807E378
    .type sub_807E378, %function
    .thumb
    .thumb_func
sub_807E378:  @ 0x0807D570 (jp 0x0807E378, score 0.6875)
    .hword 0xB500  @ push {lr}
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD110  @ bne #0x24
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x2100  @ movs r1, #0
    .word 0xFF8DF786  @ bl #0xfff86f1e
    .hword 0x4908  @ ldr r1, [pc, #0x20]
    .hword 0x220C  @ movs r2, #0xc
    .hword 0x5E89  @ ldrsh r1, [r1, r2]
    .hword 0x62C1  @ str r1, [r0, #0x2c]
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x3041  @ adds r0, #0x41
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0780  @ lsls r0, r0, #0x1e
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDB02  @ blt #8
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .word 0xFDE0F041  @ bl #0x41bc4
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xB044  @ add sp, #0x110
    .hword 0x08DB  @ lsrs r3, r3, #3
    .hword 0xBBB8  @ cbnz r0, #0x72
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x026A  @ lsls r2, r5, #9
    .hword 0x0000  @ movs r0, r0

    .global sub_807E3BC
    .type sub_807E3BC, %function
    .thumb
    .thumb_func
sub_807E3BC:  @ 0x0807D5B4 (jp 0x0807E3BC, score 0.8)
    .hword 0xB500  @ push {lr}
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .word 0xF970F787  @ bl #0xfff872e4
    .hword 0x4A07  @ ldr r2, [pc, #0x1c]
    .hword 0x8990  @ ldrh r0, [r2, #0xc]
    .hword 0x300F  @ adds r0, #0xf
    .hword 0x2310  @ movs r3, #0x10
    .hword 0x425B  @ rsbs r3, r3, #0
    .hword 0x1C19  @ adds r1, r3, #0
    .hword 0x4008  @ ands r0, r1
    .hword 0x8190  @ strh r0, [r2, #0xc]
    .hword 0x2004  @ movs r0, #4
    .word 0xF8A5F786  @ bl #0xfff8614e
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xB044  @ add sp, #0x110
    .hword 0x08DB  @ lsrs r3, r3, #3
    .hword 0xBBB8  @ cbnz r0, #0x72
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_807E3E8
    .type sub_807E3E8, %function
    .thumb
    .thumb_func
sub_807E3E8:  @ 0x0807D5E0 (jp 0x0807E3E8, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .word 0xFED4F048  @ bl #0x48dac
    .word 0xFD3EF783  @ bl #0xfff83a80
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x314C  @ adds r1, #0x4c
    .hword 0x8808  @ ldrh r0, [r1]
    .hword 0x3801  @ subs r0, #1
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA02  @ bge #8
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF85BF787  @ bl #0xfff870ba
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .incbin "rom/fe7eu.gba", 0x7D608, 0x4

    .global sub_807E414
    .type sub_807E414, %function
    .thumb
    .thumb_func
sub_807E414:  @ 0x0807D60C (jp 0x0807E414, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x324C  @ adds r2, #0x4c
    .hword 0x210F  @ movs r1, #0xf
    .hword 0x8011  @ strh r1, [r2]
    .word 0xFFE3F7FF  @ bl #0xffffffca
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_807E428
    .type sub_807E428, %function
    .thumb
    .thumb_func
sub_807E428:  @ 0x0807D620 (jp 0x0807E428, score 0.8462)
    .hword 0xB500  @ push {lr}
    .hword 0x4A05  @ ldr r2, [pc, #0x14]
    .hword 0x21FF  @ movs r1, #0xff
    .hword 0x76D1  @ strb r1, [r2, #0x1b]
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x324C  @ adds r2, #0x4c
    .hword 0x210F  @ movs r1, #0xf
    .hword 0x8011  @ strh r1, [r2]
    .word 0xFFD6F7FF  @ bl #0xffffffb0
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x2240  @ movs r2, #0x40
    .hword 0x0202  @ lsls r2, r0, #8

    .incbin "rom/fe7eu.gba", 0x7D63C, 0x7C

    .global sub_807E4C0
    .type sub_807E4C0, %function
    .thumb
    .thumb_func
sub_807E4C0:  @ 0x0807D6B8 (jp 0x0807E4C0, score 0.7647)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD109  @ bne #0x16
    .hword 0x2084  @ movs r0, #0x84
    .word 0xFD3CF79A  @ bl #0xfff9aa7c
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x2056  @ movs r0, #0x56
    .word 0xFD32F79B  @ bl #0xfff9ba68
    .hword 0x6060  @ str r0, [r4, #4]
    .word 0xFAADF7A8  @ bl #0xfffa855e
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_807E4E8
    .type sub_807E4E8, %function
    .thumb
    .thumb_func
sub_807E4E8:  @ 0x0807D6E0 (jp 0x0807E4E8, score 0.7778)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10A  @ bne #0x18
    .hword 0x2084  @ movs r0, #0x84
    .word 0xFD28F79A  @ bl #0xfff9aa54
    .hword 0x1C04  @ adds r4, r0, #0
    .word 0xF9C9F7A9  @ bl #0xfffa9396
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA24F7EE  @ bl #0xfffee44c
    .word 0xFF80F7EF  @ bl #0xfffeff04
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_807E514
    .type sub_807E514, %function
    .thumb
    .thumb_func
sub_807E514:  @ 0x0807D70C (jp 0x0807E514, score 0.7895)
    .hword 0xB500  @ push {lr}
    .hword 0x2070  @ movs r0, #0x70
    .word 0xF98AF7FC  @ bl #0xffffc318
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD006  @ beq #0x10
    .hword 0x4802  @ ldr r0, [pc, #8]
    .word 0xFA34F79A  @ bl #0xfff9a46c
    .hword 0xE005  @ b #0xe
    .hword 0x0000  @ movs r0, r0
    .hword 0xAEF8  @ add r6, sp, #0x3e0
    .hword 0x08DD  @ lsrs r5, r3, #3
    .hword 0x4802  @ ldr r0, [pc, #8]
    .word 0xFA2DF79A  @ bl #0xfff9a45e
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xAF18  @ add r7, sp, #0x60
    .hword 0x08DD  @ lsrs r5, r3, #3

    .global sub_807E540
    .type sub_807E540, %function
    .thumb
    .thumb_func
sub_807E540:  @ 0x0807D738 (jp 0x0807E540, score 0.8333)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x7904  @ ldrb r4, [r0, #4]
    .word 0xF8F0F7B3  @ bl #0xfffb31e4
    .hword 0x4284  @ cmp r4, r0
    .hword 0xD00D  @ beq #0x1e
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x7904  @ ldrb r4, [r0, #4]
    .word 0xF8E9F7B3  @ bl #0xfffb31d6
    .hword 0x4284  @ cmp r4, r0
    .hword 0xD006  @ beq #0x10
    .hword 0x2000  @ movs r0, #0
    .hword 0xE005  @ b #0xe
    .hword 0x0000  @ movs r0, r0
    .hword 0xA3F0  @ adr r3, #0x3c0
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0xA470  @ adr r4, #0x1c0
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x2001  @ movs r0, #1
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}

    .global sub_807E584
    .type sub_807E584, %function
    .thumb
    .thumb_func
sub_807E584:  @ 0x0807D76A (jp 0x0807E584, score 0.8125)
    .hword 0x4708  @ bx r1
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD118  @ bne #0x34
    .hword 0x2044  @ movs r0, #0x44
    .word 0xFCE1F79A  @ bl #0xfff9a9c6
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x5641  @ ldrsb r1, [r0, r1]
    .hword 0x0109  @ lsls r1, r1, #4
    .hword 0x4B0A  @ ldr r3, [pc, #0x28]
    .hword 0x250C  @ movs r5, #0xc
    .hword 0x5F5A  @ ldrsh r2, [r3, r5]
    .hword 0x3A08  @ subs r2, #8
    .hword 0x1A89  @ subs r1, r1, r2
    .hword 0x2211  @ movs r2, #0x11
    .hword 0x5682  @ ldrsb r2, [r0, r2]
    .hword 0x0112  @ lsls r2, r2, #4
    .hword 0x250E  @ movs r5, #0xe
    .hword 0x5F58  @ ldrsh r0, [r3, r5]
    .hword 0x3808  @ subs r0, #8
    .hword 0x1A12  @ subs r2, r2, r0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFD3FF7A3  @ bl #0xfffa3a82
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x314D  @ adds r1, #0x4d
    .hword 0x2001  @ movs r0, #1
    .hword 0x7008  @ strb r0, [r1]
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xBBB8  @ cbnz r0, #0x72
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xB570  @ push {r4, r5, r6, lr}

    .incbin "rom/fe7eu.gba", 0x7D7BA, 0x4A

    .global sub_807E5D4
    .type sub_807E5D4, %function
    .thumb
    .thumb_func
sub_807E5D4:  @ 0x0807D804 (jp 0x0807E5D4, score 0.8)
    .hword 0xD101  @ bne #6
    .word 0xFEFDF7A3  @ bl #0xfffa3dfe
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x7D810, 0x58

    .global EventCall_HideNinianDragonSMS
    .type EventCall_HideNinianDragonSMS, %function
    .thumb
    .thumb_func
EventCall_HideNinianDragonSMS:  @ 0x0807D868 (jp 0x0807E694, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x20DA  @ movs r0, #0xda
    .word 0xFC6AF79A  @ bl #0xfff9a8d8
    .word 0xF90CF7A9  @ bl #0xfffa921c
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global EventCall_NinianDragonTrembling
    .type EventCall_NinianDragonTrembling, %function
    .thumb
    .thumb_func
EventCall_NinianDragonTrembling:  @ 0x0807D878 (jp 0x0807E6A4, score 0.8438)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0xB082  @ sub sp, #8
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x0C06  @ lsrs r6, r0, #0x10
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xD120  @ bne #0x44
    .hword 0x20DA  @ movs r0, #0xda
    .word 0xFC59F79A  @ bl #0xfff9a8b6
    .hword 0x2410  @ movs r4, #0x10
    .hword 0x5704  @ ldrsb r4, [r0, r4]
    .hword 0x0124  @ lsls r4, r4, #4
    .hword 0x4A0F  @ ldr r2, [pc, #0x3c]
    .hword 0x230C  @ movs r3, #0xc
    .hword 0x5ED1  @ ldrsh r1, [r2, r3]
    .hword 0x1A64  @ subs r4, r4, r1
    .hword 0x3408  @ adds r4, #8
    .hword 0x2511  @ movs r5, #0x11
    .hword 0x5745  @ ldrsb r5, [r0, r5]
    .hword 0x012D  @ lsls r5, r5, #4
    .hword 0x210E  @ movs r1, #0xe
    .hword 0x5E50  @ ldrsh r0, [r2, r1]
    .hword 0x1A2D  @ subs r5, r5, r0
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x490B  @ ldr r1, [pc, #0x2c]
    .word 0xFDA9F795  @ bl #0xfff95b56
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x4B0B  @ ldr r3, [pc, #0x2c]
    .hword 0x9600  @ str r6, [sp]
    .hword 0x9601  @ str r6, [sp, #4]
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x1C2A  @ adds r2, r5, #0
    .word 0xFF15F794  @ bl #0xfff94e2e
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x2101  @ movs r1, #1
    .word 0xFA7BF797  @ bl #0xfff974fa
    .hword 0xB002  @ add sp, #8
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xBBB8  @ cbnz r0, #0x72
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xC43C  @ stm r4!, {r2, r3, r4, r5}
    .hword 0x080F  @ lsrs r7, r1, #0x20
    .hword 0x3000  @ adds r0, #0
    .hword 0x0601  @ lsls r1, r0, #0x18
    .hword 0xC80C  @ ldm r0!, {r2, r3}
    .hword 0x080F  @ lsrs r7, r1, #0x20
    .hword 0xC180  @ stm r1!, {r7}
    .hword 0x0000  @ movs r0, r0
    .hword 0xD869  @ bhi #0xd6
    .hword 0x0807  @ lsrs r7, r0, #0x20

    .global EventCall_PutFallNinian
    .type EventCall_PutFallNinian, %function
    .thumb
    .thumb_func
EventCall_PutFallNinian:  @ 0x0807D8F0 (jp 0x0807E71C, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x20DA  @ movs r0, #0xda
    .word 0xFC26F79A  @ bl #0xfff9a850
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD003  @ beq #0xa
    .word 0xF8D8F7A9  @ bl #0xfffa91b4
    .word 0xFF4AF794  @ bl #0xfff94e98
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_807E774
    .type sub_807E774, %function
    .thumb
    .thumb_func
sub_807E774:  @ 0x0807D908 (jp 0x0807E774, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x2009  @ movs r0, #9
    .word 0xFC1AF79A  @ bl #0xfff9a838
    .hword 0x1C04  @ adds r4, r0, #0
    .word 0xFAA9F7FC  @ bl #0xffffc556
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD009  @ beq #0x16
    .hword 0x6860  @ ldr r0, [r4, #4]
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .hword 0x2813  @ cmp r0, #0x13
    .hword 0xD105  @ bne #0xe
    .hword 0x2008  @ movs r0, #8
    .hword 0x5620  @ ldrsb r0, [r4, r0]
    .hword 0x2804  @ cmp r0, #4
    .hword 0xDD01  @ ble #6
    .hword 0x2001  @ movs r0, #1
    .hword 0xE000  @ b #4
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807E7A4
    .type sub_807E7A4, %function
    .thumb
    .thumb_func
sub_807E7A4:  @ 0x0807D938 (jp 0x0807E7A4, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x2009  @ movs r0, #9
    .word 0xFC02F79A  @ bl #0xfff9a808
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x2500  @ movs r5, #0
    .hword 0x8BF4  @ ldrh r4, [r6, #0x1e]
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD01B  @ beq #0x3a
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFE68F799  @ bl #0xfff99cd4
    .hword 0x2101  @ movs r1, #1
    .hword 0x4001  @ ands r1, r0
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD008  @ beq #0x14
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x1C21  @ adds r1, r4, #0
    .word 0xFE9EF798  @ bl #0xfff98d40
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD001  @ beq #6
    .hword 0x2001  @ movs r0, #1
    .hword 0xE00C  @ b #0x1c
    .hword 0x1C68  @ adds r0, r5, #1
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E05  @ lsrs r5, r0, #0x18
    .hword 0x2D04  @ cmp r5, #4
    .hword 0xD806  @ bhi #0x10
    .hword 0x0069  @ lsls r1, r5, #1
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x301E  @ adds r0, #0x1e
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x8804  @ ldrh r4, [r0]
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD1E3  @ bne #0xffffffca
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807E7F8
    .type sub_807E7F8, %function
    .thumb
    .thumb_func
sub_807E7F8:  @ 0x0807D98C (jp 0x0807E7F8, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2037  @ movs r0, #0x37
    .word 0xFBD8F79A  @ bl #0xfff9a7b4
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xDC05  @ bgt #0xe
    .hword 0x2011  @ movs r0, #0x11
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xDC01  @ bgt #6
    .hword 0x2001  @ movs r0, #1
    .hword 0xE000  @ b #4
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

    .global sub_807E81C
    .type sub_807E81C, %function
    .thumb
    .thumb_func
sub_807E81C:  @ 0x0807D9B0 (jp 0x0807E81C, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2009  @ movs r0, #9
    .word 0xFBC6F79A  @ bl #0xfff9a790
    .word 0xFA62F79B  @ bl #0xfff9b4c8
    .hword 0x2100  @ movs r1, #0
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD100  @ bne #4
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807E838
    .type sub_807E838, %function
    .thumb
    .thumb_func
sub_807E838:  @ 0x0807D9CC (jp 0x0807E838, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2037  @ movs r0, #0x37
    .word 0xFBB8F79A  @ bl #0xfff9a774
    .word 0xFA54F79B  @ bl #0xfff9b4ac
    .hword 0x2100  @ movs r1, #0
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD100  @ bne #4
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807E854
    .type sub_807E854, %function
    .thumb
    .thumb_func
sub_807E854:  @ 0x0807D9E8 (jp 0x0807E854, score 0.8125)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0xB082  @ sub sp, #8
    .hword 0x2609  @ movs r6, #9
    .hword 0x2501  @ movs r5, #1
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFB97F79B  @ bl #0xfff9b732
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD04B  @ beq #0x9a
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD048  @ beq #0x94
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .hword 0x42B0  @ cmp r0, r6
    .hword 0xD145  @ bne #0x8e
    .hword 0x0630  @ lsls r0, r6, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .hword 0x2100  @ movs r1, #0
    .hword 0x2206  @ movs r2, #6
    .word 0xFC16F022  @ bl #0x22830
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFC45F79A  @ bl #0xfff9a88e
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2100  @ movs r1, #0
    .word 0xFB1DF79B  @ bl #0xfff9b63e
    .hword 0x4A1A  @ ldr r2, [pc, #0x68]
    .hword 0x210B  @ movs r1, #0xb
    .hword 0x5651  @ ldrsb r1, [r2, r1]
    .hword 0x200B  @ movs r0, #0xb
    .hword 0x5620  @ ldrsb r0, [r4, r0]
    .hword 0x4281  @ cmp r1, r0
    .hword 0xD104  @ bne #0xc
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x2248  @ movs r2, #0x48
    .word 0xF895F043  @ bl #0x4312e
    .hword 0x4A15  @ ldr r2, [pc, #0x54]
    .hword 0x210B  @ movs r1, #0xb
    .hword 0x5651  @ ldrsb r1, [r2, r1]
    .hword 0x200B  @ movs r0, #0xb
    .hword 0x5620  @ ldrsb r0, [r4, r0]
    .hword 0x4281  @ cmp r1, r0
    .hword 0xD104  @ bne #0xc
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x2248  @ movs r2, #0x48
    .word 0xF889F043  @ bl #0x43116
    .hword 0x68E0  @ ldr r0, [r4, #0xc]
    .hword 0x2120  @ movs r1, #0x20
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD006  @ beq #0x10
    .hword 0x7EE0  @ ldrb r0, [r4, #0x1b]
    .word 0xFB61F79B  @ bl #0xfff9b6c6
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xFBD7F79A  @ bl #0xfff9a7b2
    .hword 0x68E0  @ ldr r0, [r4, #0xc]
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD012  @ beq #0x28
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x4669  @ mov r1, sp
    .hword 0xAA01  @ add r2, sp, #4
    .word 0xFC7FF79A  @ bl #0xfff9a902
    .hword 0x9900  @ ldr r1, [sp]
    .hword 0x9A01  @ ldr r2, [sp, #4]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFBC8F79A  @ bl #0xfff9a794
    .hword 0xE007  @ b #0x12
    .hword 0x0000  @ movs r0, r0
    .hword 0xA3F0  @ adr r3, #0x3c0
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0xA470  @ adr r4, #0x1c0
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x3501  @ adds r5, #1
    .hword 0x2D3F  @ cmp r5, #0x3f

    .incbin "rom/fe7eu.gba", 0x7DA98, 0xC

    .global sub_807E908
    .type sub_807E908, %function
    .thumb
    .thumb_func
sub_807E908:  @ 0x0807DAA4 (jp 0x0807E908, score 0.9048)
    .hword 0xB500  @ push {lr}
    .word 0xFCD9F7FC  @ bl #0xffffc9b6
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00B  @ beq #0x1a
    .hword 0x2100  @ movs r1, #0
    .hword 0x4804  @ ldr r0, [pc, #0x10]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x6880  @ ldr r0, [r0, #8]
    .hword 0x7940  @ ldrb r0, [r0, #5]
    .hword 0x2825  @ cmp r0, #0x25
    .hword 0xD100  @ bne #4
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0xE002  @ b #8
    .hword 0xE3E0  @ b #0x7c4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807E950
    .type sub_807E950, %function
    .thumb
    .thumb_func
sub_807E950:  @ 0x0807DAD0 (jp 0x0807E950, score 0.875)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0xB085  @ sub sp, #0x14
    .hword 0x490C  @ ldr r1, [pc, #0x30]
    .hword 0x4668  @ mov r0, sp
    .hword 0x2214  @ movs r2, #0x14
    .word 0xF843F043  @ bl #0x4308a
    .hword 0x2300  @ movs r3, #0
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x6804  @ ldr r4, [r0]
    .hword 0x466A  @ mov r2, sp
    .hword 0x25C0  @ movs r5, #0xc0
    .hword 0x2001  @ movs r0, #1
    .hword 0x5610  @ ldrsb r0, [r2, r0]
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x1900  @ adds r0, r0, r4
    .hword 0x2100  @ movs r1, #0
    .hword 0x5651  @ ldrsb r1, [r2, r1]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD008  @ beq #0x14
    .hword 0x4028  @ ands r0, r5
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD105  @ bne #0xe
    .hword 0x2001  @ movs r0, #1
    .hword 0xE008  @ b #0x14
    .hword 0xC8EC  @ ldm r0!, {r2, r3, r5, r6, r7}
    .hword 0x084C  @ lsrs r4, r1, #1
    .hword 0xE3DC  @ b #0x7bc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x3202  @ adds r2, #2
    .hword 0x3301  @ adds r3, #1
    .hword 0x2B08  @ cmp r3, #8
    .hword 0xDDE7  @ ble #0xffffffd2
    .hword 0x2000  @ movs r0, #0
    .hword 0xB005  @ add sp, #0x14
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807E9A4
    .type sub_807E9A4, %function
    .thumb
    .thumb_func
sub_807E9A4:  @ 0x0807DB24 (jp 0x0807E9A4, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x2027  @ movs r0, #0x27
    .word 0xFB0CF79A  @ bl #0xfff9a61c
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x208C  @ movs r0, #0x8c
    .word 0xFCACF798  @ bl #0xfff9895c
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFF84F799  @ bl #0xfff99f0c
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_807E9C4
    .type sub_807E9C4, %function
    .thumb
    .thumb_func
sub_807E9C4:  @ 0x0807DB44 (jp 0x0807E9C4, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x3060  @ adds r0, #0x60
    .hword 0x2100  @ movs r1, #0
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x7041  @ strb r1, [r0, #1]
    .hword 0x7081  @ strb r1, [r0, #2]
    .hword 0x8081  @ strh r1, [r0, #4]
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x2102  @ movs r1, #2
    .hword 0x2201  @ movs r2, #1
    .word 0xF9F0F78A  @ bl #0xfff8a3e4
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .incbin "rom/fe7eu.gba", 0x7DB60, 0x2

    .global sub_807E9E0
    .type sub_807E9E0, %function
    .thumb
    .thumb_func
sub_807E9E0:  @ 0x0807DB62 (jp 0x0807E9E0, score 1.0)
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x4904  @ ldr r1, [pc, #0x10]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00C  @ beq #0x1c
    .hword 0x1C0A  @ adds r2, r1, #0
    .hword 0x6810  @ ldr r0, [r2]
    .hword 0x4283  @ cmp r3, r0
    .hword 0xD103  @ bne #0xa
    .hword 0x6848  @ ldr r0, [r1, #4]
    .hword 0xE007  @ b #0x12
    .byte 0x88
    .hword 0xDBEF  @ blt #0xffffffe2
    .hword 0x0808  @ lsrs r0, r1, #0x20
    .hword 0x0831  @ lsrs r1, r6, #0x20
    .hword 0x0832  @ lsrs r2, r6, #0x20
    .hword 0x0068  @ lsls r0, r5, #1
    .word 0x00D1F328  @ ssat r0, #0x12, r8, asr #3
    .hword 0x0220  @ lsls r0, r4, #8
    .hword 0x08BC  @ lsrs r4, r7, #2
    .hword 0x7047  @ strb r7, [r0, #1]
    .byte 0xB5

    .incbin "rom/fe7eu.gba", 0x7DB8E, 0x136

    .global sub_807EB44
    .type sub_807EB44, %function
    .thumb
    .thumb_func
sub_807EB44:  @ 0x0807DCC4 (jp 0x0807EB44, score 0.8462)
    .hword 0xB500  @ push {lr}
    .hword 0xB081  @ sub sp, #4
    .hword 0x2000  @ movs r0, #0
    .hword 0x9000  @ str r0, [sp]
    .hword 0x21C0  @ movs r1, #0xc0
    .hword 0x04C9  @ lsls r1, r1, #0x13
    .hword 0x4A08  @ ldr r2, [pc, #0x20]
    .hword 0x4668  @ mov r0, sp
    .word 0xFC80F042  @ bl #0x42904
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x2100  @ movs r1, #0
    .word 0xFD9EF783  @ bl #0xfff83b40
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0x2100  @ movs r1, #0
    .word 0xFD9AF783  @ bl #0xfff83b38
    .hword 0x2003  @ movs r0, #3
    .word 0xF98DF783  @ bl #0xfff8331e
    .hword 0xB001  @ add sp, #4
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0008  @ movs r0, r1
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x2C60  @ cmp r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x3460  @ adds r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_807EB80
    .type sub_807EB80, %function
    .thumb
    .thumb_func
sub_807EB80:  @ 0x0807DD00 (jp 0x0807EB80, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFAD7F791  @ bl #0xfff915b2
    .word 0xFB27F791  @ bl #0xfff91652
    .word 0xF8EDF79C  @ bl #0xfff9c1de
    .word 0xFF91F7A7  @ bl #0xfffa7f26
    .word 0xFE0DF79B  @ bl #0xfff9bc1e
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_807EB9C
    .type sub_807EB9C, %function
    .thumb
    .thumb_func
sub_807EB9C:  @ 0x0807DD1C (jp 0x0807EB9C, score 0.9091)
    .hword 0xB500  @ push {lr}
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x7EC0  @ ldrb r0, [r0, #0x1b]
    .hword 0x2803  @ cmp r0, #3
    .hword 0xD10E  @ bne #0x20
    .word 0xFB0BF7FC  @ bl #0xffffc61a
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD009  @ beq #0x16
    .hword 0x2007  @ movs r0, #7
    .word 0xFE79F7FB  @ bl #0xffffbcf6
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD003  @ beq #0xa
    .hword 0x2001  @ movs r0, #1
    .hword 0xE002  @ b #8
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x2000  @ movs r0, #0
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global sub_807EBCC
    .type sub_807EBCC, %function
    .thumb
    .thumb_func
sub_807EBCC:  @ 0x0807DD4C (jp 0x0807EBCC, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0xB08B  @ sub sp, #0x2c
    .hword 0xA804  @ add r0, sp, #0x10
    .hword 0x491F  @ ldr r1, [pc, #0x7c]
    .hword 0xC91C  @ ldm r1!, {r2, r3, r4}
    .hword 0xC01C  @ stm r0!, {r2, r3, r4}
    .hword 0xC91C  @ ldm r1!, {r2, r3, r4}
    .hword 0xC01C  @ stm r0!, {r2, r3, r4}
    .hword 0x6809  @ ldr r1, [r1]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x2700  @ movs r7, #0
    .hword 0x2601  @ movs r6, #1
    .hword 0xAD04  @ add r5, sp, #0x10
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xF9DCF79B  @ bl #0xfff9b3bc
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD024  @ beq #0x4c
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD021  @ beq #0x46
    .hword 0x7904  @ ldrb r4, [r0, #4]
    .hword 0x2C01  @ cmp r4, #1
    .hword 0xD01E  @ beq #0x40
    .hword 0x2C02  @ cmp r4, #2
    .hword 0xD01C  @ beq #0x3c
    .hword 0x2C2D  @ cmp r4, #0x2d
    .hword 0xD01A  @ beq #0x38
    .hword 0x2C26  @ cmp r4, #0x26
    .hword 0xD018  @ beq #0x34
    .hword 0x2C27  @ cmp r4, #0x27
    .hword 0xD016  @ beq #0x30
    .hword 0x68C9  @ ldr r1, [r1, #0xc]
    .hword 0x4810  @ ldr r0, [pc, #0x40]
    .hword 0x4001  @ ands r1, r0
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD111  @ bne #0x26
    .hword 0x2200  @ movs r2, #0
    .hword 0x56AA  @ ldrsb r2, [r5, r2]
    .hword 0x2301  @ movs r3, #1
    .hword 0x56EB  @ ldrsb r3, [r5, r3]
    .hword 0x9200  @ str r2, [sp]
    .hword 0x2001  @ movs r0, #1
    .hword 0x5628  @ ldrsb r0, [r5, r0]
    .hword 0x9001  @ str r0, [sp, #4]
    .hword 0x9102  @ str r1, [sp, #8]
    .hword 0x9103  @ str r1, [sp, #0xc]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2100  @ movs r1, #0
    .word 0xF906F794  @ bl #0xfff94210
    .hword 0x3504  @ adds r5, #4
    .hword 0x3701  @ adds r7, #1
    .hword 0x2F06  @ cmp r7, #6
    .hword 0xDC02  @ bgt #8
    .hword 0x3601  @ adds r6, #1
    .hword 0x2E3F  @ cmp r6, #0x3f
    .hword 0xDDD1  @ ble #0xffffffa6
    .word 0xFF37F7A7  @ bl #0xfffa7e72
    .hword 0xB00B  @ add sp, #0x2c
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .byte 0x00
    .hword 0x4CC9  @ ldr r4, [pc, #0x324]
    .hword 0x0C08  @ lsrs r0, r1, #0x10
    .hword 0x0100  @ lsls r0, r0, #4
    .byte 0x00

    .global sub_807EC58
    .type sub_807EC58, %function
    .thumb
    .thumb_func
sub_807EC58:  @ 0x0807DDD8 (jp 0x0807EC58, score 0.75)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0xB08A  @ sub sp, #0x28
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0xAA07  @ add r2, sp, #0x1c
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0xC838  @ ldm r0!, {r3, r4, r5}
    .hword 0xC138  @ stm r1!, {r3, r4, r5}
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x7EC0  @ ldrb r0, [r0, #0x1b]
    .hword 0x2803  @ cmp r0, #3
    .hword 0xD109  @ bne #0x16
    .hword 0x2002  @ movs r0, #2
    .hword 0x9004  @ str r0, [sp, #0x10]
    .hword 0x202D  @ movs r0, #0x2d
    .hword 0x9005  @ str r0, [sp, #0x14]
    .hword 0x2001  @ movs r0, #1
    .hword 0xE008  @ b #0x14
    .hword 0xC91C  @ ldm r1!, {r2, r3, r4}
    .hword 0x084C  @ lsrs r4, r1, #1
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x2001  @ movs r0, #1
    .hword 0x9004  @ str r0, [sp, #0x10]
    .hword 0x202D  @ movs r0, #0x2d
    .hword 0x9005  @ str r0, [sp, #0x14]
    .hword 0x2002  @ movs r0, #2
    .hword 0x9006  @ str r0, [sp, #0x18]
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD116  @ bne #0x30
    .hword 0x1C14  @ adds r4, r2, #0
    .hword 0xAF04  @ add r7, sp, #0x10
    .hword 0x2502  @ movs r5, #2
    .hword 0xCF01  @ ldm r7!, {r0}
    .hword 0x2200  @ movs r2, #0
    .hword 0x56A2  @ ldrsb r2, [r4, r2]
    .hword 0x2301  @ movs r3, #1
    .hword 0x56E3  @ ldrsb r3, [r4, r3]
    .hword 0x2102  @ movs r1, #2
    .hword 0x5661  @ ldrsb r1, [r4, r1]
    .hword 0x9100  @ str r1, [sp]
    .hword 0x2103  @ movs r1, #3
    .hword 0x5661  @ ldrsb r1, [r4, r1]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x2100  @ movs r1, #0
    .hword 0x9102  @ str r1, [sp, #8]
    .hword 0x9603  @ str r6, [sp, #0xc]
    .word 0xF8BEF794  @ bl #0xfff94180
    .hword 0x3404  @ adds r4, #4
    .hword 0x3D01  @ subs r5, #1
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDAEB  @ bge #0xffffffda
    .hword 0xB00A  @ add sp, #0x28
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global Finial_EventLoadAllies1
    .type Finial_EventLoadAllies1, %function
    .thumb
    .thumb_func
Finial_EventLoadAllies1:  @ 0x0807DE54 (jp 0x0807ECD4, score 0.7812)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0xB087  @ sub sp, #0x1c
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0xA904  @ add r1, sp, #0x10
    .hword 0x4829  @ ldr r0, [pc, #0xa4]
    .hword 0xC81C  @ ldm r0!, {r2, r3, r4}
    .hword 0xC11C  @ stm r1!, {r2, r3, r4}
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x0C04  @ lsrs r4, r0, #0x10
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD143  @ bne #0x8a
    .hword 0xA804  @ add r0, sp, #0x10
    .hword 0x2200  @ movs r2, #0
    .hword 0x5682  @ ldrsb r2, [r0, r2]
    .hword 0x2301  @ movs r3, #1
    .hword 0x56C3  @ ldrsb r3, [r0, r3]
    .hword 0x7880  @ ldrb r0, [r0, #2]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x9000  @ str r0, [sp]
    .hword 0xA804  @ add r0, sp, #0x10
    .hword 0x78C0  @ ldrb r0, [r0, #3]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x9001  @ str r0, [sp, #4]
    .hword 0x9402  @ str r4, [sp, #8]
    .hword 0x9503  @ str r5, [sp, #0xc]
    .hword 0x2027  @ movs r0, #0x27
    .hword 0x2100  @ movs r1, #0
    .word 0xF892F794  @ bl #0xfff94128
    .hword 0xA804  @ add r0, sp, #0x10
    .hword 0x2204  @ movs r2, #4
    .hword 0x5682  @ ldrsb r2, [r0, r2]
    .hword 0x2305  @ movs r3, #5
    .hword 0x56C3  @ ldrsb r3, [r0, r3]
    .hword 0x7980  @ ldrb r0, [r0, #6]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x9000  @ str r0, [sp]
    .hword 0xA804  @ add r0, sp, #0x10
    .hword 0x79C0  @ ldrb r0, [r0, #7]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x9001  @ str r0, [sp, #4]
    .hword 0x9402  @ str r4, [sp, #8]
    .hword 0x9503  @ str r5, [sp, #0xc]
    .hword 0x2026  @ movs r0, #0x26
    .hword 0x2100  @ movs r1, #0
    .word 0xF87EF794  @ bl #0xfff94100
    .hword 0x4810  @ ldr r0, [pc, #0x40]
    .hword 0x302B  @ adds r0, #0x2b
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x2401  @ movs r4, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD013  @ beq #0x2a
    .hword 0xA804  @ add r0, sp, #0x10
    .hword 0x2208  @ movs r2, #8
    .hword 0x5682  @ ldrsb r2, [r0, r2]
    .hword 0x2309  @ movs r3, #9
    .hword 0x56C3  @ ldrsb r3, [r0, r3]
    .hword 0x7A80  @ ldrb r0, [r0, #0xa]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x9000  @ str r0, [sp]
    .hword 0xA804  @ add r0, sp, #0x10
    .hword 0x7AC0  @ ldrb r0, [r0, #0xb]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x9001  @ str r0, [sp, #4]
    .hword 0x9402  @ str r4, [sp, #8]
    .hword 0x9503  @ str r5, [sp, #0xc]
    .hword 0x20CD  @ movs r0, #0xcd
    .hword 0x2151  @ movs r1, #0x51
    .word 0xF862F794  @ bl #0xfff940c8
    .hword 0xB007  @ add sp, #0x1c
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xC928  @ ldm r1!, {r3, r5}
    .hword 0x084C  @ lsrs r4, r1, #1
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8

    .global Finial_EventLoadAllies2
    .type Finial_EventLoadAllies2, %function
    .thumb
    .thumb_func
Finial_EventLoadAllies2:  @ 0x0807DF0C (jp 0x0807ED8C, score 0.875)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4647  @ mov r7, r8
    .hword 0xB480  @ push {r7}
    .hword 0xB088  @ sub sp, #0x20
    .hword 0x1C07  @ adds r7, r0, #0
    .hword 0x2000  @ movs r0, #0
    .hword 0x4680  @ mov r8, r0
    .hword 0xA904  @ add r1, sp, #0x10
    .hword 0x4823  @ ldr r0, [pc, #0x8c]
    .hword 0xC81C  @ ldm r0!, {r2, r3, r4}
    .hword 0xC11C  @ stm r1!, {r2, r3, r4}
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD135  @ bne #0x6e
    .hword 0x2601  @ movs r6, #1
    .hword 0xAD04  @ add r5, sp, #0x10
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xF8F3F79B  @ bl #0xfff9b1ea
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD028  @ beq #0x54
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD025  @ beq #0x4e
    .hword 0x7904  @ ldrb r4, [r0, #4]
    .hword 0x2C01  @ cmp r4, #1
    .hword 0xD022  @ beq #0x48
    .hword 0x2C02  @ cmp r4, #2
    .hword 0xD020  @ beq #0x44
    .hword 0x2C2D  @ cmp r4, #0x2d
    .hword 0xD01E  @ beq #0x40
    .hword 0x2C26  @ cmp r4, #0x26
    .hword 0xD01C  @ beq #0x3c
    .hword 0x2C27  @ cmp r4, #0x27
    .hword 0xD01A  @ beq #0x38
    .hword 0x68C9  @ ldr r1, [r1, #0xc]
    .hword 0x4813  @ ldr r0, [pc, #0x4c]
    .hword 0x4001  @ ands r1, r0
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD115  @ bne #0x2e
    .hword 0x2200  @ movs r2, #0
    .hword 0x56AA  @ ldrsb r2, [r5, r2]
    .hword 0x2301  @ movs r3, #1
    .hword 0x56EB  @ ldrsb r3, [r5, r3]
    .hword 0x2002  @ movs r0, #2
    .hword 0x5628  @ ldrsb r0, [r5, r0]
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2003  @ movs r0, #3
    .hword 0x5628  @ ldrsb r0, [r5, r0]
    .hword 0x9001  @ str r0, [sp, #4]
    .hword 0x9102  @ str r1, [sp, #8]
    .hword 0x9703  @ str r7, [sp, #0xc]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2100  @ movs r1, #0
    .word 0xF81BF794  @ bl #0xfff9403a
    .hword 0x3504  @ adds r5, #4
    .hword 0x2001  @ movs r0, #1
    .hword 0x4480  @ add r8, r0
    .hword 0x4642  @ mov r2, r8
    .hword 0x2A03  @ cmp r2, #3
    .hword 0xDC02  @ bgt #8
    .hword 0x3601  @ adds r6, #1
    .hword 0x2E3F  @ cmp r6, #0x3f
    .hword 0xDDCD  @ ble #0xffffff9e
    .word 0xFE4AF7A7  @ bl #0xfffa7c98
    .hword 0xB008  @ add sp, #0x20
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xC934  @ ldm r1!, {r2, r4, r5}
    .hword 0x084C  @ lsrs r4, r1, #1
    .hword 0x000C  @ movs r4, r1
    .hword 0x0001  @ movs r1, r0

    .global Finial_EventLoadAllies3
    .type Finial_EventLoadAllies3, %function
    .thumb
    .thumb_func
Finial_EventLoadAllies3:  @ 0x0807DFB4 (jp 0x0807EE34, score 0.7812)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4647  @ mov r7, r8
    .hword 0xB480  @ push {r7}
    .hword 0xB087  @ sub sp, #0x1c
    .hword 0x4680  @ mov r8, r0
    .hword 0x2700  @ movs r7, #0
    .hword 0xA904  @ add r1, sp, #0x10
    .hword 0x4823  @ ldr r0, [pc, #0x8c]
    .hword 0xC81C  @ ldm r0!, {r2, r3, r4}
    .hword 0xC11C  @ stm r1!, {r2, r3, r4}
    .hword 0x4640  @ mov r0, r8
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x2004  @ movs r0, #4
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD136  @ bne #0x70
    .hword 0x2601  @ movs r6, #1
    .hword 0x466D  @ mov r5, sp
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xF8A2F79B  @ bl #0xfff9b148
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD029  @ beq #0x56
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD026  @ beq #0x50
    .hword 0x7904  @ ldrb r4, [r0, #4]
    .hword 0x2C01  @ cmp r4, #1
    .hword 0xD023  @ beq #0x4a
    .hword 0x2C02  @ cmp r4, #2
    .hword 0xD021  @ beq #0x46
    .hword 0x2C2D  @ cmp r4, #0x2d
    .hword 0xD01F  @ beq #0x42
    .hword 0x2C26  @ cmp r4, #0x26
    .hword 0xD01D  @ beq #0x3e
    .hword 0x2C27  @ cmp r4, #0x27
    .hword 0xD01B  @ beq #0x3a
    .hword 0x68C9  @ ldr r1, [r1, #0xc]
    .hword 0x4813  @ ldr r0, [pc, #0x4c]
    .hword 0x4001  @ ands r1, r0
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD116  @ bne #0x30
    .hword 0x2F03  @ cmp r7, #3
    .hword 0xDD10  @ ble #0x24
    .hword 0x2200  @ movs r2, #0
    .hword 0x56AA  @ ldrsb r2, [r5, r2]
    .hword 0x2301  @ movs r3, #1
    .hword 0x56EB  @ ldrsb r3, [r5, r3]
    .hword 0x2002  @ movs r0, #2
    .hword 0x5628  @ ldrsb r0, [r5, r0]
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2003  @ movs r0, #3
    .hword 0x5628  @ ldrsb r0, [r5, r0]
    .hword 0x9001  @ str r0, [sp, #4]
    .hword 0x9102  @ str r1, [sp, #8]
    .hword 0x4640  @ mov r0, r8
    .hword 0x9003  @ str r0, [sp, #0xc]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2100  @ movs r1, #0
    .word 0xFFC7F793  @ bl #0xfff93f92
    .hword 0x3504  @ adds r5, #4
    .hword 0x3701  @ adds r7, #1
    .hword 0x2F06  @ cmp r7, #6
    .hword 0xDC02  @ bgt #8
    .hword 0x3601  @ adds r6, #1
    .hword 0x2E3F  @ cmp r6, #0x3f
    .hword 0xDDCC  @ ble #0xffffff9c
    .word 0xFDF8F7A7  @ bl #0xfffa7bf4
    .hword 0xB007  @ add sp, #0x1c
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xC944  @ ldm r1!, {r2, r6}
    .hword 0x084C  @ lsrs r4, r1, #1
    .hword 0x000C  @ movs r4, r1
    .hword 0x0001  @ movs r1, r0

    .incbin "rom/fe7eu.gba", 0x7E058, 0x84

    .global sub_807EF68
    .type sub_807EF68, %function
    .thumb
    .thumb_func
sub_807EF68:  @ 0x0807E0DC (jp 0x0807EF68, score 1.0)
    .hword 0xB500  @ push {lr}
    .hword 0x2027  @ movs r0, #0x27
    .word 0xF830F79A  @ bl #0xfff9a064
    .hword 0x2100  @ movs r1, #0
    .word 0xF997F7B5  @ bl #0xfffb5332
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_807EF7C
    .type sub_807EF7C, %function
    .thumb
    .thumb_func
sub_807EF7C:  @ 0x0807E0F0 (jp 0x0807EF7C, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x4D1F  @ ldr r5, [pc, #0x7c]
    .hword 0x481F  @ ldr r0, [pc, #0x7c]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x2100  @ movs r1, #0
    .word 0xF9EDF79B  @ bl #0xfff9b3de
    .hword 0x2027  @ movs r0, #0x27
    .word 0xF820F79A  @ bl #0xfff9a044
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x481C  @ ldr r0, [pc, #0x70]
    .word 0xFBACF78C  @ bl #0xfff8c75c
    .hword 0x2001  @ movs r0, #1
    .word 0xF819F79A  @ bl #0xfff9a036
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4819  @ ldr r0, [pc, #0x64]
    .word 0xFBA5F78C  @ bl #0xfff8c74e
    .hword 0x2001  @ movs r0, #1
    .word 0xF812F79A  @ bl #0xfff9a028
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4817  @ ldr r0, [pc, #0x5c]
    .word 0xFB9EF78C  @ bl #0xfff8c740
    .hword 0x2002  @ movs r0, #2
    .word 0xF80BF79A  @ bl #0xfff9a01a
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4814  @ ldr r0, [pc, #0x50]
    .word 0xFB97F78C  @ bl #0xfff8c732
    .hword 0x202D  @ movs r0, #0x2d
    .word 0xF804F79A  @ bl #0xfff9a00c
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4812  @ ldr r0, [pc, #0x48]
    .word 0xFB90F78C  @ bl #0xfff8c724
    .hword 0x2401  @ movs r4, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFFECF79A  @ bl #0xfff9afdc
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD100  @ bne #4
    .hword 0xE084  @ b #0x10c
    .hword 0x6810  @ ldr r0, [r2]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD100  @ bne #4
    .hword 0xE080  @ b #0x104
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .hword 0x3801  @ subs r0, #1
    .hword 0x282C  @ cmp r0, #0x2c
    .hword 0xD86F  @ bhi #0xe2
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4909  @ ldr r1, [pc, #0x24]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x4687  @ mov pc, r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x0428  @ lsls r0, r5, #0x10
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0xE3F4  @ b #0x7ec
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x04A8  @ lsls r0, r5, #0x12
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x04C8  @ lsls r0, r1, #0x13
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x03C8  @ lsls r0, r1, #0xf
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x03E8  @ lsls r0, r5, #0xf
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0x0408  @ lsls r0, r1, #0x10
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0xE190  @ b #0x324
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE25E  @ b #0x4c0
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE25E  @ b #0x4c0
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE25E  @ b #0x4c0
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE25E  @ b #0x4c0
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE244  @ b #0x48c
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0xE25E  @ b #0x4c0
    .hword 0x0807  @ lsrs r7, r0, #0x20
    .hword 0x68D0  @ ldr r0, [r2, #0xc]
    .hword 0x490B  @ ldr r1, [pc, #0x2c]
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD107  @ bne #0x12
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x1C11  @ adds r1, r2, #0
    .word 0xFB07F78C  @ bl #0xfff8c612
    .hword 0x3510  @ adds r5, #0x10
    .hword 0x7828  @ ldrb r0, [r5]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD003  @ beq #0xa
    .hword 0x3401  @ adds r4, #1
    .hword 0x2C3F  @ cmp r4, #0x3f
    .hword 0xDC00  @ bgt #4
    .hword 0xE76F  @ b #0xfffffee2
    .word 0xFE3FF79B  @ bl #0xfff9bc82
    .word 0xFCE3F7A7  @ bl #0xfffa79ca
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x000C  @ movs r4, r1
    .hword 0x0001  @ movs r1, r0

    .global sub_807F104
    .type sub_807F104, %function
    .thumb
    .thumb_func
sub_807F104:  @ 0x0807E278 (jp 0x0807F104, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x4D16  @ ldr r5, [pc, #0x58]
    .hword 0x4816  @ ldr r0, [pc, #0x58]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x2100  @ movs r1, #0
    .word 0xF929F79B  @ bl #0xfff9b256
    .hword 0x2401  @ movs r4, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFF4BF79A  @ bl #0xfff9ae9a
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD014  @ beq #0x2c
    .hword 0x6810  @ ldr r0, [r2]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD011  @ beq #0x26
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .hword 0x2826  @ cmp r0, #0x26
    .hword 0xD00E  @ beq #0x20
    .hword 0x2827  @ cmp r0, #0x27
    .hword 0xD00C  @ beq #0x1c
    .hword 0x68D0  @ ldr r0, [r2, #0xc]
    .hword 0x490D  @ ldr r1, [pc, #0x34]
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD107  @ bne #0x12
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x1C11  @ adds r1, r2, #0
    .word 0xFAD7F78C  @ bl #0xfff8c5b2
    .hword 0x3510  @ adds r5, #0x10
    .hword 0x7828  @ ldrb r0, [r5]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD002  @ beq #8
    .hword 0x3401  @ adds r4, #1
    .hword 0x2C3F  @ cmp r4, #0x3f
    .hword 0xDDE1  @ ble #0xffffffc6
    .word 0xFE10F79B  @ bl #0xfff9bc24
    .word 0xFCB4F7A7  @ bl #0xfffa796c
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x04E8  @ lsls r0, r5, #0x13
    .hword 0x08DE  @ lsrs r6, r3, #3
    .hword 0xE3F4  @ b #0x7ec
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x000C  @ movs r4, r1
    .hword 0x0001  @ movs r1, r0

