@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x0008273C-0x000830F4
    .syntax unified

    .global PutSpriteTalkBox
    .type PutSpriteTalkBox, %function
    .thumb
    .thumb_func
PutSpriteTalkBox:  @ 0x0808273C (jp 0x08083088, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB087  @ sub sp, #0x1c
    .hword 0x4682  @ mov sl, r0
    .hword 0x4689  @ mov sb, r1
    .hword 0x1C17  @ adds r7, r2, #0
    .hword 0x4698  @ mov r8, r3
    .hword 0x2F1F  @ cmp r7, #0x1f
    .hword 0xDC00  @ bgt #4
    .hword 0x2720  @ movs r7, #0x20
    .hword 0x2FC0  @ cmp r7, #0xc0
    .hword 0xDD00  @ ble #4
    .hword 0x27C0  @ movs r7, #0xc0
    .hword 0x4640  @ mov r0, r8
    .hword 0x280F  @ cmp r0, #0xf
    .hword 0xDC01  @ bgt #6
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x4688  @ mov r8, r1
    .hword 0x4643  @ mov r3, r8
    .hword 0x2B30  @ cmp r3, #0x30
    .hword 0xDD01  @ ble #6
    .hword 0x2030  @ movs r0, #0x30
    .hword 0x4680  @ mov r8, r0
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x301F  @ adds r0, #0x1f
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA00  @ bge #4
    .hword 0x301F  @ adds r0, #0x1f
    .hword 0x1140  @ asrs r0, r0, #5
    .hword 0x4641  @ mov r1, r8
    .hword 0x310F  @ adds r1, #0xf
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDA00  @ bge #4
    .hword 0x310F  @ adds r1, #0xf
    .hword 0x1109  @ asrs r1, r1, #4
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x1E46  @ subs r6, r0, #1
    .hword 0x9606  @ str r6, [sp, #0x18]
    .hword 0x4649  @ mov r1, sb
    .hword 0x3908  @ subs r1, #8
    .hword 0x9105  @ str r1, [sp, #0x14]
    .hword 0x464B  @ mov r3, sb
    .hword 0x4443  @ add r3, r8
    .hword 0x9303  @ str r3, [sp, #0xc]
    .hword 0x4650  @ mov r0, sl
    .hword 0x3808  @ subs r0, #8
    .hword 0x9004  @ str r0, [sp, #0x10]
    .hword 0x4651  @ mov r1, sl
    .hword 0x19C9  @ adds r1, r1, r7
    .hword 0x9102  @ str r1, [sp, #8]
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xDB23  @ blt #0x4a
    .hword 0x9D01  @ ldr r5, [sp, #4]
    .hword 0x1E74  @ subs r4, r6, #1
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDB1C  @ blt #0x3c
    .hword 0x1C70  @ adds r0, r6, #1
    .hword 0x0141  @ lsls r1, r0, #5
    .hword 0x42B9  @ cmp r1, r7
    .hword 0xDD00  @ ble #4
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x3920  @ subs r1, #0x20
    .hword 0x1C68  @ adds r0, r5, #1
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x4540  @ cmp r0, r8
    .hword 0xDD00  @ ble #4
    .hword 0x4640  @ mov r0, r8
    .hword 0x3810  @ subs r0, #0x10
    .hword 0x4451  @ add r1, sl
    .hword 0x464B  @ mov r3, sb
    .hword 0x181A  @ adds r2, r3, r0
    .hword 0x4B47  @ ldr r3, [pc, #0x11c]
    .hword 0x00B0  @ lsls r0, r6, #2
    .hword 0x8E1B  @ ldrh r3, [r3, #0x30]
    .hword 0x18C0  @ adds r0, r0, r3
    .hword 0x01AB  @ lsls r3, r5, #6
    .hword 0x18C0  @ adds r0, r0, r3
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x4B44  @ ldr r3, [pc, #0x110]
    .word 0xF9A1F784  @ bl #0xfff84346
    .hword 0x3D01  @ subs r5, #1
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDAE2  @ bge #0xffffffc8
    .hword 0x1C26  @ adds r6, r4, #0
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xDADB  @ bge #0xffffffba
    .hword 0x9E06  @ ldr r6, [sp, #0x18]
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xDB1D  @ blt #0x3e
    .hword 0x4D3D  @ ldr r5, [pc, #0xf4]
    .hword 0x1C70  @ adds r0, r6, #1
    .hword 0x0141  @ lsls r1, r0, #5
    .hword 0x42B9  @ cmp r1, r7
    .hword 0xDD00  @ ble #4
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x3920  @ subs r1, #0x20
    .hword 0x4650  @ mov r0, sl
    .hword 0x1844  @ adds r4, r0, r1
    .hword 0x8E28  @ ldrh r0, [r5, #0x30]
    .hword 0x301B  @ adds r0, #0x1b
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x9A05  @ ldr r2, [sp, #0x14]
    .hword 0x4B38  @ ldr r3, [pc, #0xe0]
    .word 0xF986F784  @ bl #0xfff84310
    .hword 0x8E28  @ ldrh r0, [r5, #0x30]
    .hword 0x301B  @ adds r0, #0x1b
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x9A03  @ ldr r2, [sp, #0xc]
    .hword 0x4B34  @ ldr r3, [pc, #0xd0]
    .word 0xF97DF784  @ bl #0xfff842fe
    .hword 0x3E01  @ subs r6, #1
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xDAE2  @ bge #0xffffffc8
    .hword 0x9D01  @ ldr r5, [sp, #4]
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDB1D  @ blt #0x3e
    .hword 0x4E2D  @ ldr r6, [pc, #0xb4]
    .hword 0x1C68  @ adds r0, r5, #1
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x4540  @ cmp r0, r8
    .hword 0xDD00  @ ble #4
    .hword 0x4640  @ mov r0, r8
    .hword 0x3810  @ subs r0, #0x10
    .hword 0x4649  @ mov r1, sb
    .hword 0x180C  @ adds r4, r1, r0
    .hword 0x8E30  @ ldrh r0, [r6, #0x30]
    .hword 0x301F  @ adds r0, #0x1f
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x9904  @ ldr r1, [sp, #0x10]
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x4B29  @ ldr r3, [pc, #0xa4]
    .word 0xF965F784  @ bl #0xfff842ce
    .hword 0x8E30  @ ldrh r0, [r6, #0x30]
    .hword 0x301F  @ adds r0, #0x1f
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x9902  @ ldr r1, [sp, #8]
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x4B26  @ ldr r3, [pc, #0x98]
    .word 0xF95CF784  @ bl #0xfff842bc
    .hword 0x3D01  @ subs r5, #1
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDAE2  @ bge #0xffffffc8
    .hword 0x4B24  @ ldr r3, [pc, #0x90]
    .hword 0x4C1D  @ ldr r4, [pc, #0x74]
    .hword 0x8E20  @ ldrh r0, [r4, #0x30]
    .hword 0x303E  @ adds r0, #0x3e
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x9904  @ ldr r1, [sp, #0x10]
    .hword 0x9A05  @ ldr r2, [sp, #0x14]
    .word 0xF94FF784  @ bl #0xfff842a2
    .hword 0x4B20  @ ldr r3, [pc, #0x80]
    .hword 0x8E20  @ ldrh r0, [r4, #0x30]
    .hword 0x303E  @ adds r0, #0x3e
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x9902  @ ldr r1, [sp, #8]
    .hword 0x9A05  @ ldr r2, [sp, #0x14]
    .word 0xF946F784  @ bl #0xfff84290
    .hword 0x4B1C  @ ldr r3, [pc, #0x70]
    .hword 0x8E20  @ ldrh r0, [r4, #0x30]
    .hword 0x303E  @ adds r0, #0x3e
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x9904  @ ldr r1, [sp, #0x10]
    .hword 0x9A03  @ ldr r2, [sp, #0xc]
    .word 0xF93DF784  @ bl #0xfff8427e
    .hword 0x4B19  @ ldr r3, [pc, #0x64]
    .hword 0x8E20  @ ldrh r0, [r4, #0x30]
    .hword 0x303E  @ adds r0, #0x3e
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x9902  @ ldr r1, [sp, #8]
    .hword 0x9A03  @ ldr r2, [sp, #0xc]
    .word 0xF934F784  @ bl #0xfff8426c
    .hword 0x980F  @ ldr r0, [sp, #0x3c]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10B  @ bne #0x1a
    .hword 0x464A  @ mov r2, sb
    .hword 0x3A0B  @ subs r2, #0xb
    .hword 0x4B0A  @ ldr r3, [pc, #0x28]
    .hword 0x8E21  @ ldrh r1, [r4, #0x30]
    .hword 0x4812  @ ldr r0, [pc, #0x48]
    .hword 0x4008  @ ands r0, r1
    .hword 0x305C  @ adds r0, #0x5c
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x4651  @ mov r1, sl
    .word 0xF925F784  @ bl #0xfff8424e
    .hword 0xB007  @ add sp, #0x1c
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE6A0  @ b #0xfffffd44
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0xBBAC  @ cbnz r4, #0x6e
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0xBBBC  @ cbnz r4, #0x72
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0xBBCC  @ cbnz r4, #0x76
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0xBB84  @ cbnz r4, #0x64
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0xBBD4  @ cbnz r4, #0x78
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0xBB64  @ cbnz r4, #0x5c
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0xBBDC  @ cbnz r4, #0x7a
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0xBBE4  @ cbnz r4, #0x7c
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0xBBEC  @ cbnz r4, #0x7e
    .hword 0x08C8  @ lsrs r0, r1, #3
    .hword 0x03FF  @ lsls r7, r7, #0xf
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x8291C, 0x90

    .global sub_80832E0
    .type sub_80832E0, %function
    .thumb
    .thumb_func
sub_80832E0:  @ 0x080829AC (jp 0x080832E0, score 0.9062)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x4C1C  @ ldr r4, [pc, #0x70]
    .word 0xF97DF794  @ bl #0xfff942fe
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2120  @ movs r1, #0x20
    .hword 0x2207  @ movs r2, #7
    .word 0xF8CDF783  @ bl #0xfff8319e
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xF90AF794  @ bl #0xfff94218
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x214C  @ movs r1, #0x4c
    .hword 0x2207  @ movs r2, #7
    .word 0xF8C4F783  @ bl #0xfff8318c
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFE73F794  @ bl #0xfff94cea
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2190  @ movs r1, #0x90
    .hword 0x2207  @ movs r2, #7
    .word 0xF8CDF783  @ bl #0xfff8319e
    .hword 0x3408  @ adds r4, #8
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFE51F794  @ bl #0xfff94ca6
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2120  @ movs r1, #0x20
    .hword 0x2207  @ movs r2, #7
    .word 0xF8C3F783  @ bl #0xfff8318a
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFE54F794  @ bl #0xfff94cac
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x215A  @ movs r1, #0x5a
    .hword 0x2207  @ movs r2, #7
    .word 0xF8BAF783  @ bl #0xfff83178
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFE63F794  @ bl #0xfff94cca
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2190  @ movs r1, #0x90
    .hword 0x2207  @ movs r2, #7
    .word 0xF8B1F783  @ bl #0xfff83166
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xE6B8  @ b #0xfffffd74
    .hword 0x0203  @ lsls r3, r0, #8

    .incbin "rom/fe7eu.gba", 0x82A28, 0x200

    .global sub_80834D8
    .type sub_80834D8, %function
    .thumb
    .thumb_func
sub_80834D8:  @ 0x08082C28 (jp 0x080834D8, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x315E  @ adds r1, #0x5e
    .hword 0x8808  @ ldrh r0, [r1]
    .hword 0x3801  @ subs r0, #1
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDC3C  @ bgt #0x7c
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3060  @ adds r0, #0x60
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x6B20  @ ldr r0, [r4, #0x30]
    .word 0xFC27F782  @ bl #0xfff82852
    .hword 0x2600  @ movs r6, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3062  @ adds r0, #0x62
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E81  @ ldrsh r1, [r0, r2]
    .hword 0x1C07  @ adds r7, r0, #0
    .hword 0x428E  @ cmp r6, r1
    .hword 0xDA2A  @ bge #0x58
    .hword 0x1C25  @ adds r5, r4, #0
    .hword 0x355C  @ adds r5, #0x5c
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .hword 0x7802  @ ldrb r2, [r0]
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x2A01  @ cmp r2, #1
    .hword 0xD00B  @ beq #0x1a
    .hword 0x2A01  @ cmp r2, #1
    .hword 0xDC02  @ bgt #8
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD003  @ beq #0xa
    .hword 0xE00E  @ b #0x20
    .hword 0x2A04  @ cmp r2, #4
    .hword 0xD00A  @ beq #0x18
    .hword 0xE00B  @ b #0x1a
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFD1DF781  @ bl #0xfff81a3e
    .hword 0xE017  @ b #0x32
    .hword 0x1C58  @ adds r0, r3, #1
    .hword 0x62E0  @ str r0, [r4, #0x2c]
    .hword 0x8828  @ ldrh r0, [r5]
    .hword 0x3001  @ adds r0, #1
    .hword 0x8028  @ strh r0, [r5]
    .hword 0xE00C  @ b #0x1c
    .hword 0x1C58  @ adds r0, r3, #1
    .hword 0xE009  @ b #0x16
    .hword 0x2000  @ movs r0, #0
    .hword 0x5E29  @ ldrsh r1, [r5, r0]
    .hword 0x0089  @ lsls r1, r1, #2
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3034  @ adds r0, #0x34
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1C19  @ adds r1, r3, #0
    .word 0xFDDCF782  @ bl #0xfff82bbc
    .hword 0x62E0  @ str r0, [r4, #0x2c]
    .hword 0x3601  @ adds r6, #1
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E78  @ ldrsh r0, [r7, r1]
    .hword 0x4286  @ cmp r6, r0
    .hword 0xDBD6  @ blt #0xffffffb0
    .hword 0x2000  @ movs r0, #0
    .word 0xFBF1F782  @ bl #0xfff827e6
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_808356C
    .type sub_808356C, %function
    .thumb
    .thumb_func
sub_808356C:  @ 0x08082CBC (jp 0x0808356C, score 0.9375)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x6B20  @ ldr r0, [r4, #0x30]
    .word 0xFBE9F782  @ bl #0xfff827d6
    .hword 0x2600  @ movs r6, #0
    .hword 0x00B1  @ lsls r1, r6, #2
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3034  @ adds r0, #0x34
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6805  @ ldr r5, [r0]
    .hword 0x7928  @ ldrb r0, [r5, #4]
    .hword 0x00C0  @ lsls r0, r0, #3
    .hword 0x6AE1  @ ldr r1, [r4, #0x2c]
    .word 0xFD0AF782  @ bl #0xfff82a18
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFC68F782  @ bl #0xfff828d4
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x2901  @ cmp r1, #1
    .hword 0xD00B  @ beq #0x1a
    .hword 0x2901  @ cmp r1, #1
    .hword 0xDC02  @ bgt #8
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD013  @ beq #0x2a
    .hword 0xE00C  @ b #0x1c
    .hword 0x2905  @ cmp r1, #5
    .hword 0xDC0A  @ bgt #0x18
    .hword 0x2904  @ cmp r1, #4
    .hword 0xDB08  @ blt #0x14
    .hword 0x3001  @ adds r0, #1
    .hword 0x62E0  @ str r0, [r4, #0x2c]
    .hword 0xE7EF  @ b #0xffffffe2
    .hword 0x3001  @ adds r0, #1
    .hword 0x62E0  @ str r0, [r4, #0x2c]
    .hword 0x3601  @ adds r6, #1
    .hword 0x2E05  @ cmp r6, #5
    .hword 0xDDDC  @ ble #0xffffffbc
    .hword 0xE005  @ b #0xe
    .hword 0x6AE1  @ ldr r1, [r4, #0x2c]
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFDA2F782  @ bl #0xfff82b48
    .hword 0x62E0  @ str r0, [r4, #0x2c]
    .hword 0xE7E3  @ b #0xffffffca
    .hword 0x6B20  @ ldr r0, [r4, #0x30]
    .word 0xFBBBF782  @ bl #0xfff8277a
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_80835D8
    .type sub_80835D8, %function
    .thumb
    .thumb_func
sub_80835D8:  @ 0x08082D28 (jp 0x080835D8, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x6DAC  @ ldr r4, [r5, #0x58]
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .word 0xFBB2F782  @ bl #0xfff82768
    .hword 0x2000  @ movs r0, #0
    .word 0xFB8DF782  @ bl #0xfff8271e
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF862F7FF  @ bl #0xfffff0c8
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2901  @ cmp r1, #1
    .hword 0xD00F  @ beq #0x22
    .hword 0x2901  @ cmp r1, #1
    .hword 0xDC04  @ bgt #0xc
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD007  @ beq #0x12
    .hword 0xE01B  @ b #0x3a
    .hword 0xE6A0  @ b #0xfffffd44
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x2902  @ cmp r1, #2
    .hword 0xD00D  @ beq #0x1e
    .hword 0x2903  @ cmp r1, #3
    .hword 0xD00F  @ beq #0x22
    .hword 0xE014  @ b #0x2c
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x3064  @ adds r0, #0x64
    .hword 0x8001  @ strh r1, [r0]
    .hword 0xE010  @ b #0x24
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFDD8F7FF  @ bl #0xfffffbb4
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x3164  @ adds r1, #0x64
    .hword 0x2002  @ movs r0, #2
    .hword 0xE008  @ b #0x14
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFE57F7FF  @ bl #0xfffffcb2
    .hword 0xE001  @ b #6
    .word 0xFE84F7FF  @ bl #0xfffffd0c
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x3164  @ adds r1, #0x64
    .hword 0x2001  @ movs r0, #1
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x2000  @ movs r0, #0
    .word 0xFB85F782  @ bl #0xfff8270e
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFC92F781  @ bl #0xfff81928
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_808364C
    .type sub_808364C, %function
    .thumb
    .thumb_func
sub_808364C:  @ 0x08082D9C (jp 0x0808364C, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x6DAC  @ ldr r4, [r5, #0x58]
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .word 0xFB78F782  @ bl #0xfff826f4
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF82BF7FF  @ bl #0xfffff05a
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD004  @ beq #0xc
    .hword 0x2803  @ cmp r0, #3
    .hword 0xD006  @ beq #0x10
    .hword 0xE007  @ b #0x12
    .hword 0xE6A0  @ b #0xfffffd44
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFDF5F7FF  @ bl #0xfffffbee
    .hword 0xE001  @ b #6
    .word 0xFEB2F7FF  @ bl #0xfffffd68
    .hword 0x2000  @ movs r0, #0
    .word 0xFB65F782  @ bl #0xfff826ce
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFC72F781  @ bl #0xfff818e8
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_808368C
    .type sub_808368C, %function
    .thumb
    .thumb_func
sub_808368C:  @ 0x08082DDC (jp 0x0808368C, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x4656  @ mov r6, sl
    .hword 0x464D  @ mov r5, sb
    .hword 0x4644  @ mov r4, r8
    .hword 0xB470  @ push {r4, r5, r6}
    .hword 0x4682  @ mov sl, r0
    .hword 0x4D26  @ ldr r5, [pc, #0x98]
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFB54F782  @ bl #0xfff826ac
    .hword 0x2001  @ movs r0, #1
    .word 0xFB2FF782  @ bl #0xfff82662
    .hword 0x2018  @ movs r0, #0x18
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x4681  @ mov sb, r0
    .hword 0x2106  @ movs r1, #6
    .word 0xFBDFF782  @ bl #0xfff827c2
    .hword 0x2120  @ movs r1, #0x20
    .hword 0x1949  @ adds r1, r1, r5
    .hword 0x4688  @ mov r8, r1
    .hword 0x4640  @ mov r0, r8
    .hword 0x2106  @ movs r1, #6
    .word 0xFBD8F782  @ bl #0xfff827b4
    .hword 0x1C2E  @ adds r6, r5, #0
    .hword 0x3628  @ adds r6, #0x28
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x2106  @ movs r1, #6
    .word 0xFBD2F782  @ bl #0xfff827a8
    .hword 0x2000  @ movs r0, #0
    .word 0xFB3BF782  @ bl #0xfff8267a
    .hword 0x4C19  @ ldr r4, [pc, #0x64]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFD39F781  @ bl #0xfff81a76
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2103  @ movs r1, #3
    .word 0xFB37F781  @ bl #0xfff81672
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x6325  @ str r5, [r4, #0x30]
    .hword 0x4648  @ mov r0, sb
    .hword 0x6360  @ str r0, [r4, #0x34]
    .hword 0x4641  @ mov r1, r8
    .hword 0x63A1  @ str r1, [r4, #0x38]
    .hword 0x63E6  @ str r6, [r4, #0x3c]
    .hword 0x4650  @ mov r0, sl
    .hword 0x3064  @ adds r0, #0x64
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x305C  @ adds r0, #0x5c
    .hword 0x2500  @ movs r5, #0
    .hword 0x8001  @ strh r1, [r0]
    .hword 0x4651  @ mov r1, sl
    .hword 0x6DC8  @ ldr r0, [r1, #0x5c]
    .word 0xF851F790  @ bl #0xfff900a6
    .word 0xF881F790  @ bl #0xfff90106
    .hword 0x62E0  @ str r0, [r4, #0x2c]
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x3162  @ adds r1, #0x62
    .hword 0x2301  @ movs r3, #1
    .hword 0x800B  @ strh r3, [r1]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x305E  @ adds r0, #0x5e
    .hword 0x8005  @ strh r5, [r0]
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x3040  @ adds r0, #0x40
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0640  @ lsls r0, r0, #0x19
    .hword 0x0F82  @ lsrs r2, r0, #0x1e
    .hword 0x2A01  @ cmp r2, #1
    .hword 0xD014  @ beq #0x2c
    .hword 0x2A01  @ cmp r2, #1
    .hword 0xDC09  @ bgt #0x16
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD00C  @ beq #0x1c
    .hword 0xE01D  @ b #0x3e
    .hword 0x0000  @ movs r0, r0
    .hword 0xE6A0  @ b #0xfffffd44
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x248C  @ movs r4, #0x8c
    .hword 0x08DC  @ lsrs r4, r3, #3
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x2A02  @ cmp r2, #2
    .hword 0xD00A  @ beq #0x18
    .hword 0x2A03  @ cmp r2, #3
    .hword 0xD00D  @ beq #0x1e
    .hword 0xE011  @ b #0x26
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x3160  @ adds r1, #0x60
    .hword 0x2002  @ movs r0, #2
    .hword 0xE00C  @ b #0x1c
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3060  @ adds r0, #0x60
    .hword 0x8002  @ strh r2, [r0]
    .hword 0xE009  @ b #0x16
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3060  @ adds r0, #0x60
    .hword 0x8003  @ strh r3, [r0]
    .hword 0x800A  @ strh r2, [r1]
    .hword 0xE004  @ b #0xc
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3060  @ adds r0, #0x60
    .hword 0x8005  @ strh r5, [r0]
    .hword 0x207F  @ movs r0, #0x7f
    .hword 0x8008  @ strh r0, [r1]
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global StartHelpBoxTextInit
    .type StartHelpBoxTextInit, %function
    .thumb
    .thumb_func
StartHelpBoxTextInit:  @ 0x08082ECC (jp 0x0808377C, score 0.8462)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0x4804  @ ldr r0, [pc, #0x10]
    .hword 0x2103  @ movs r1, #3
    .word 0xFAE3F781  @ bl #0xfff815ca
    .hword 0x6584  @ str r4, [r0, #0x58]
    .hword 0x65C5  @ str r5, [r0, #0x5c]
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x24B4  @ movs r4, #0xb4
    .hword 0x08DC  @ lsrs r4, r3, #3

    .global ClearHelpBoxText
    .type ClearHelpBoxText, %function
    .thumb
    .thumb_func
ClearHelpBoxText:  @ 0x08082EE8 (jp 0x08083798, score 0.8621)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4C0E  @ ldr r4, [pc, #0x38]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFAD3F782  @ bl #0xfff825aa
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3018  @ adds r0, #0x18
    .word 0xFEEFF782  @ bl #0xfff82de2
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3020  @ adds r0, #0x20
    .word 0xFEEBF782  @ bl #0xfff82dda
    .hword 0x3428  @ adds r4, #0x28
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFEE7F782  @ bl #0xfff82dd2
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .word 0xFCC6F781  @ bl #0xfff81990
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .word 0xFCC3F781  @ bl #0xfff8198a
    .hword 0x2000  @ movs r0, #0
    .word 0xFABEF782  @ bl #0xfff82580
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE6A0  @ b #0xfffffd44
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x248C  @ movs r4, #0x8c
    .hword 0x08DC  @ lsrs r4, r3, #3
    .hword 0x24B4  @ movs r4, #0xb4
    .hword 0x08DC  @ lsrs r4, r3, #3

    .global sub_80837E0
    .type sub_80837E0, %function
    .thumb
    .thumb_func
sub_80837E0:  @ 0x08082F30 (jp 0x080837E0, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x2105  @ movs r1, #5
    .word 0xFC15F7FE  @ bl #0xffffe82e
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x3248  @ adds r2, #0x48
    .hword 0x344A  @ adds r4, #0x4a
    .hword 0x8813  @ ldrh r3, [r2]
    .hword 0x2000  @ movs r0, #0
    .hword 0x5E11  @ ldrsh r1, [r2, r0]
    .hword 0x2500  @ movs r5, #0
    .hword 0x5F60  @ ldrsh r0, [r4, r5]
    .hword 0x4281  @ cmp r1, r0
    .hword 0xDA01  @ bge #6
    .hword 0x1C58  @ adds r0, r3, #1
    .hword 0x8010  @ strh r0, [r2]
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_8083808
    .type sub_8083808, %function
    .thumb
    .thumb_func
sub_8083808:  @ 0x08082F58 (jp 0x08083808, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .word 0xF95CF000  @ bl #0x2bc
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .hword 0x7C01  @ ldrb r1, [r0, #0x10]
    .hword 0x7C42  @ ldrb r2, [r0, #0x11]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF952F000  @ bl #0x2a8
    .hword 0x1C25  @ adds r5, r4, #0
    .hword 0x354A  @ adds r5, #0x4a
    .hword 0x2100  @ movs r1, #0
    .hword 0x5E68  @ ldrsh r0, [r5, r1]
    .hword 0x2103  @ movs r1, #3
    .word 0xFC6DF03D  @ bl #0x3d8de
    .hword 0x8028  @ strh r0, [r5]
    .hword 0x3448  @ adds r4, #0x48
    .hword 0x8020  @ strh r0, [r4]
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_8083838
    .type sub_8083838, %function
    .thumb
    .thumb_func
sub_8083838:  @ 0x08082F88 (jp 0x08083838, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x2100  @ movs r1, #0
    .word 0xFBE9F7FE  @ bl #0xffffe7d6
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x3148  @ adds r1, #0x48
    .hword 0x8808  @ ldrh r0, [r1]
    .hword 0x3801  @ subs r0, #1
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA02  @ bge #8
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFB88F781  @ bl #0xfff81714
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_8083860
    .type sub_8083860, %function
    .thumb
    .thumb_func
sub_8083860:  @ 0x08082FB0 (jp 0x08083860, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x2300  @ movs r3, #0
    .hword 0x7404  @ strb r4, [r0, #0x10]
    .hword 0x7441  @ strb r1, [r0, #0x11]
    .hword 0x8242  @ strh r2, [r0, #0x12]
    .hword 0x6143  @ str r3, [r0, #0x14]
    .hword 0x6183  @ str r3, [r0, #0x18]
    .word 0xF8B1F000  @ bl #0x166
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xE6D4  @ b #0xfffffdac
    .hword 0x0203  @ lsls r3, r0, #8

    .global sub_8083880
    .type sub_8083880, %function
    .thumb
    .thumb_func
sub_8083880:  @ 0x08082FD0 (jp 0x08083880, score 0.9062)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0xB082  @ sub sp, #8
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x4C0F  @ ldr r4, [pc, #0x3c]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFB71F781  @ bl #0xfff816e6
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD11B  @ bne #0x3a
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2103  @ movs r1, #3
    .word 0xFA5AF781  @ bl #0xfff814b8
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x3041  @ adds r0, #0x41
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0780  @ lsls r0, r0, #0x1e
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDB03  @ blt #0xa
    .hword 0x20E4  @ movs r0, #0xe4
    .hword 0x0080  @ lsls r0, r0, #2
    .word 0xF8AFF03C  @ bl #0x3c162
    .hword 0x7C31  @ ldrb r1, [r6, #0x10]
    .hword 0x7C72  @ ldrb r2, [r6, #0x11]
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xF902F000  @ bl #0x208
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xF903F000  @ bl #0x20a
    .hword 0xE011  @ b #0x26
    .hword 0x24DC  @ movs r4, #0xdc
    .hword 0x08DC  @ lsrs r4, r3, #3
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x8E28  @ ldrh r0, [r5, #0x30]
    .hword 0x8728  @ strh r0, [r5, #0x38]
    .hword 0x8E68  @ ldrh r0, [r5, #0x32]
    .hword 0x8768  @ strh r0, [r5, #0x3a]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x3044  @ adds r0, #0x44
    .hword 0x8801  @ ldrh r1, [r0]
    .hword 0x3804  @ subs r0, #4
    .hword 0x8001  @ strh r1, [r0]
    .hword 0x3006  @ adds r0, #6
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x3142  @ adds r1, #0x42
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x62EE  @ str r6, [r5, #0x2c]
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x3148  @ adds r1, #0x48
    .hword 0x2000  @ movs r0, #0
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x3102  @ adds r1, #2
    .hword 0x200C  @ movs r0, #0xc
    .hword 0x8008  @ strh r0, [r1]
    .hword 0x8A70  @ ldrh r0, [r6, #0x12]
    .hword 0x1C2C  @ adds r4, r5, #0
    .hword 0x344C  @ adds r4, #0x4c
    .hword 0x8020  @ strh r0, [r4]
    .hword 0x2001  @ movs r0, #1
    .word 0xF9FFF782  @ bl #0xfff82402
    .hword 0x8820  @ ldrh r0, [r4]
    .word 0xFF4EF78F  @ bl #0xfff8fea0
    .hword 0xAA01  @ add r2, sp, #4
    .hword 0x4669  @ mov r1, sp
    .word 0xFB54F782  @ bl #0xfff826ac
    .hword 0x2000  @ movs r0, #0
    .word 0xF9F5F782  @ bl #0xfff823ee
    .hword 0x9900  @ ldr r1, [sp]
    .hword 0x9A01  @ ldr r2, [sp, #4]
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xF872F000  @ bl #0xe8
    .hword 0x7C31  @ ldrb r1, [r6, #0x10]
    .hword 0x7C72  @ ldrb r2, [r6, #0x11]
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xF88DF000  @ bl #0x11e
    .word 0xFF33F7FF  @ bl #0xfffffe6a
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x304E  @ adds r0, #0x4e
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x8821  @ ldrh r1, [r4]
    .word 0xFF1FF7FF  @ bl #0xfffffe42
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x6006  @ str r6, [r0]
    .hword 0xB002  @ add sp, #8
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE6F0  @ b #0xfffffde4
    .hword 0x0203  @ lsls r3, r0, #8

    .global sub_8083950
    .type sub_8083950, %function
    .thumb
    .thumb_func
sub_8083950:  @ 0x080830A0 (jp 0x08083950, score 0.8095)
    .hword 0xB500  @ push {lr}
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x3041  @ adds r0, #0x41
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0780  @ lsls r0, r0, #0x1e
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDB02  @ blt #8
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .word 0xF856F03C  @ bl #0x3c0b0
    .word 0xFF18F7FF  @ bl #0xfffffe34
    .hword 0x4804  @ ldr r0, [pc, #0x10]
    .word 0xFBFDF781  @ bl #0xfff817fe
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x0391  @ lsls r1, r2, #0xe
    .hword 0x0000  @ movs r0, r0
    .hword 0x24DC  @ movs r4, #0xdc
    .hword 0x08DC  @ lsrs r4, r3, #3

    .global sub_8083980
    .type sub_8083980, %function
    .thumb
    .thumb_func
sub_8083980:  @ 0x080830D0 (jp 0x08083980, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x3050  @ adds r0, #0x50
    .hword 0x2100  @ movs r1, #0
    .hword 0x8001  @ strh r1, [r0]
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .hword 0x6941  @ ldr r1, [r0, #0x14]
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD002  @ beq #8
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFB9AF03D  @ bl #0x3d738
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .word 0xFF71F7FF  @ bl #0xfffffee6
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

