@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x0001A00C-0x0001B60C
    .syntax unified

    .global sub_8019FC0
    .type sub_8019FC0, %function
    .thumb
    .thumb_func
sub_8019FC0:  @ 0x0801A00C (jp 0x08019FC0, score 0.8889)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x060C  @ lsls r4, r1, #0x18
    .hword 0x0E24  @ lsrs r4, r4, #0x18
    .word 0xFDE2F7FE  @ bl #0xffffebc8
    .word 0xF878F000  @ bl #0xf4
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x4808  @ ldr r0, [pc, #0x20]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x5628  @ ldrsb r0, [r5, r0]
    .hword 0x2111  @ movs r1, #0x11
    .hword 0x5669  @ ldrsb r1, [r5, r1]
    .hword 0x0624  @ lsls r4, r4, #0x18
    .hword 0x1624  @ asrs r4, r4, #0x18
    .hword 0x230B  @ movs r3, #0xb
    .hword 0x56EB  @ ldrsb r3, [r5, r3]
    .hword 0x1C22  @ adds r2, r4, #0
    .word 0xF879F000  @ bl #0xf6
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xE3E4  @ b #0x7cc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global sub_8019FFC
    .type sub_8019FFC, %function
    .thumb
    .thumb_func
sub_8019FFC:  @ 0x0801A048 (jp 0x08019FFC, score 0.8696)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .word 0xFDC6F7FE  @ bl #0xffffeb90
    .word 0xF85CF000  @ bl #0xbc
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x4807  @ ldr r0, [pc, #0x1c]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x5620  @ ldrsb r0, [r4, r0]
    .hword 0x2111  @ movs r1, #0x11
    .hword 0x5661  @ ldrsb r1, [r4, r1]
    .hword 0x227C  @ movs r2, #0x7c
    .hword 0x2300  @ movs r3, #0
    .word 0xF860F000  @ bl #0xc4
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE3E4  @ b #0x7cc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global MapFloodRange_Unitless
    .type MapFloodRange_Unitless, %function
    .thumb
    .thumb_func
MapFloodRange_Unitless:  @ 0x0801A07C (jp 0x0801A030, score 0.9545)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0x1C10  @ adds r0, r2, #0
    .word 0xF842F000  @ bl #0x88
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x227C  @ movs r2, #0x7c
    .hword 0x2300  @ movs r3, #0
    .word 0xF848F000  @ bl #0x94
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE3E8  @ b #0x7d4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global GenerateExtendedMovementMap
    .type GenerateExtendedMovementMap, %function
    .thumb
    .thumb_func
GenerateExtendedMovementMap:  @ 0x0801A0AC (jp 0x0801A060, score 0.8636)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0x1C10  @ adds r0, r2, #0
    .word 0xF82AF000  @ bl #0x58
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x227C  @ movs r2, #0x7c
    .hword 0x2300  @ movs r3, #0
    .word 0xF830F000  @ bl #0x64
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE3E4  @ b #0x7cc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global sub_801A090
    .type sub_801A090, %function
    .thumb
    .thumb_func
sub_801A090:  @ 0x0801A0DC (jp 0x0801A090, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x4646  @ mov r6, r8
    .hword 0xB440  @ push {r6}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0x1C16  @ adds r6, r2, #0
    .hword 0x4698  @ mov r8, r3
    .word 0xFD77F7FE  @ bl #0xffffeaf2
    .word 0xF80DF000  @ bl #0x1e
    .hword 0x230B  @ movs r3, #0xb
    .hword 0x56E3  @ ldrsb r3, [r4, r3]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x1C31  @ adds r1, r6, #0
    .hword 0x4642  @ mov r2, r8
    .word 0xF816F000  @ bl #0x30
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_801A0C0
    .type sub_801A0C0, %function
    .thumb
    .thumb_func
sub_801A0C0:  @ 0x0801A10C (jp 0x0801A0C0, score 0.9375)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x2200  @ movs r2, #0
    .hword 0x4C05  @ ldr r4, [pc, #0x14]
    .hword 0x1910  @ adds r0, r2, r4
    .hword 0x1899  @ adds r1, r3, r2
    .hword 0x7809  @ ldrb r1, [r1]
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x3201  @ adds r2, #1
    .hword 0x2A40  @ cmp r2, #0x40
    .hword 0xDDF8  @ ble #0xfffffff4
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x43F0  @ mvns r0, r6
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global sub_801A0E0
    .type sub_801A0E0, %function
    .thumb
    .thumb_func
sub_801A0E0:  @ 0x0801A12C (jp 0x0801A0E0, score 0.9062)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4647  @ mov r7, r8
    .hword 0xB480  @ push {r7}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0F  @ adds r7, r1, #0
    .hword 0x4905  @ ldr r1, [pc, #0x14]
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x6048  @ str r0, [r1, #4]
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x724A  @ strb r2, [r1, #9]
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xD107  @ bne #0x12
    .hword 0x7233  @ strb r3, [r6, #8]
    .hword 0xE008  @ b #0x14
    .hword 0x46A0  @ mov r8, r4
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x41F0  @ rors r0, r6
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x4490  @ add r8, r2
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x2001  @ movs r0, #1
    .hword 0x7230  @ strb r0, [r6, #8]
    .hword 0x72B3  @ strb r3, [r6, #0xa]
    .hword 0x2000  @ movs r0, #0
    .hword 0x4680  @ mov r8, r0
    .hword 0x2078  @ movs r0, #0x78
    .hword 0x72F0  @ strb r0, [r6, #0xb]
    .hword 0x4C11  @ ldr r4, [pc, #0x44]
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .word 0xF9B3F7FF  @ bl #0xfffff36a
    .hword 0x6870  @ ldr r0, [r6, #4]
    .hword 0x7005  @ strb r5, [r0]
    .hword 0x6870  @ ldr r0, [r6, #4]
    .hword 0x7047  @ strb r7, [r0, #1]
    .hword 0x6871  @ ldr r1, [r6, #4]
    .hword 0x2005  @ movs r0, #5
    .hword 0x7088  @ strb r0, [r1, #2]
    .hword 0x6870  @ ldr r0, [r6, #4]
    .hword 0x4641  @ mov r1, r8
    .hword 0x70C1  @ strb r1, [r0, #3]
    .hword 0x6821  @ ldr r1, [r4]
    .hword 0x00B8  @ lsls r0, r7, #2
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x4641  @ mov r1, r8
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x6870  @ ldr r0, [r6, #4]
    .hword 0x3004  @ adds r0, #4
    .hword 0x6070  @ str r0, [r6, #4]
    .hword 0x2104  @ movs r1, #4
    .hword 0x7081  @ strb r1, [r0, #2]
    .word 0xF939F7EA  @ bl #0xfffea276
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .incbin "rom/fe7eu.gba", 0x1A1B0, 0xD0

    .global BuildBestMoveScript
    .type BuildBestMoveScript, %function
    .thumb
    .thumb_func
BuildBestMoveScript:  @ 0x0801A280 (jp 0x0801A23C, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB085  @ sub sp, #0x14
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x4689  @ mov sb, r1
    .hword 0x9202  @ str r2, [sp, #8]
    .hword 0x9203  @ str r2, [sp, #0xc]
    .hword 0x2000  @ movs r0, #0
    .hword 0x4684  @ mov ip, r0
    .hword 0x490D  @ ldr r1, [pc, #0x34]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x464B  @ mov r3, sb
    .hword 0x009A  @ lsls r2, r3, #2
    .hword 0x1810  @ adds r0, r2, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1980  @ adds r0, r0, r6
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD100  @ bne #4
    .hword 0xE0B1  @ b #0x166
    .hword 0x466C  @ mov r4, sp
    .hword 0xAF01  @ add r7, sp, #4
    .hword 0x46BA  @ mov sl, r7
    .hword 0x4690  @ mov r8, r2
    .hword 0x4806  @ ldr r0, [pc, #0x18]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E80  @ ldrsh r0, [r0, r2]
    .hword 0x3801  @ subs r0, #1
    .hword 0x4286  @ cmp r6, r0
    .hword 0xD108  @ bne #0x14
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x23FF  @ movs r3, #0xff
    .hword 0x4318  @ orrs r0, r3
    .hword 0xE009  @ b #0x16
    .hword 0x0000  @ movs r0, r0
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x4440  @ add r0, r8
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x7840  @ ldrb r0, [r0, #1]
    .hword 0x7020  @ strb r0, [r4]
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xD103  @ bne #0xa
    .hword 0x7860  @ ldrb r0, [r4, #1]
    .hword 0x27FF  @ movs r7, #0xff
    .hword 0x4338  @ orrs r0, r7
    .hword 0xE005  @ b #0xe
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x4440  @ add r0, r8
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x3801  @ subs r0, #1
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x7060  @ strb r0, [r4, #1]
    .hword 0x4A05  @ ldr r2, [pc, #0x14]
    .hword 0x2302  @ movs r3, #2
    .hword 0x5ED0  @ ldrsh r0, [r2, r3]
    .hword 0x3801  @ subs r0, #1
    .hword 0x4581  @ cmp sb, r0
    .hword 0xD106  @ bne #0x10
    .hword 0x78E0  @ ldrb r0, [r4, #3]
    .hword 0x27FF  @ movs r7, #0xff
    .hword 0x4338  @ orrs r0, r7
    .hword 0xE007  @ b #0x12
    .hword 0x0000  @ movs r0, r0
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x4440  @ add r0, r8
    .hword 0x6840  @ ldr r0, [r0, #4]
    .hword 0x1980  @ adds r0, r0, r6
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x70E0  @ strb r0, [r4, #3]
    .hword 0x4648  @ mov r0, sb
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD103  @ bne #0xa
    .hword 0x78A0  @ ldrb r0, [r4, #2]
    .hword 0x21FF  @ movs r1, #0xff
    .hword 0x4308  @ orrs r0, r1
    .hword 0xE005  @ b #0xe
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x4440  @ add r0, r8
    .hword 0x3804  @ subs r0, #4
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1980  @ adds r0, r0, r6
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x70A0  @ strb r0, [r4, #2]
    .hword 0x2180  @ movs r1, #0x80
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x2700  @ movs r7, #0
    .hword 0x2200  @ movs r2, #0
    .hword 0x9B02  @ ldr r3, [sp, #8]
    .hword 0x3301  @ adds r3, #1
    .hword 0x9304  @ str r3, [sp, #0x10]
    .hword 0x466B  @ mov r3, sp
    .hword 0x1898  @ adds r0, r3, r2
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x4281  @ cmp r1, r0
    .hword 0xDD00  @ ble #4
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x3201  @ adds r2, #1
    .hword 0x2A03  @ cmp r2, #3
    .hword 0xDDF6  @ ble #0xfffffff0
    .hword 0x2200  @ movs r2, #0
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0xAB01  @ add r3, sp, #4
    .hword 0x4669  @ mov r1, sp
    .hword 0x1888  @ adds r0, r1, r2
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x4285  @ cmp r5, r0
    .hword 0xD109  @ bne #0x16
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x0408  @ lsls r0, r1, #0x10
    .hword 0x2780  @ movs r7, #0x80
    .hword 0x027F  @ lsls r7, r7, #9
    .hword 0x19C0  @ adds r0, r0, r7
    .hword 0x0C07  @ lsrs r7, r0, #0x10
    .hword 0x0409  @ lsls r1, r1, #0x10
    .hword 0x1409  @ asrs r1, r1, #0x10
    .hword 0x1859  @ adds r1, r3, r1
    .hword 0x700A  @ strb r2, [r1]
    .hword 0x3201  @ adds r2, #1
    .hword 0x2A03  @ cmp r2, #3
    .hword 0xDDED  @ ble #0xffffffde
    .hword 0x0438  @ lsls r0, r7, #0x10
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x2802  @ cmp r0, #2
    .hword 0xD00B  @ beq #0x1a
    .hword 0x2802  @ cmp r0, #2
    .hword 0xDC02  @ bgt #8
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD005  @ beq #0xe
    .hword 0xE010  @ b #0x24
    .hword 0x2803  @ cmp r0, #3
    .hword 0xD006  @ beq #0x10
    .hword 0x2804  @ cmp r0, #4
    .hword 0xD006  @ beq #0x10
    .hword 0xE00B  @ b #0x1a
    .hword 0x4650  @ mov r0, sl
    .hword 0xE007  @ b #0x12
    .hword 0x2002  @ movs r0, #2
    .hword 0xE002  @ b #8
    .hword 0x2003  @ movs r0, #3
    .hword 0xE000  @ b #4
    .hword 0x2004  @ movs r0, #4
    .word 0xFD42F7E6  @ bl #0xfffe6a88
    .hword 0x4450  @ add r0, sl
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x4684  @ mov ip, r0
    .hword 0x4662  @ mov r2, ip
    .hword 0x9902  @ ldr r1, [sp, #8]
    .hword 0x700A  @ strb r2, [r1]
    .hword 0x9B04  @ ldr r3, [sp, #0x10]
    .hword 0x9302  @ str r3, [sp, #8]
    .hword 0x4660  @ mov r0, ip
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD00B  @ beq #0x1a
    .hword 0x2801  @ cmp r0, #1
    .hword 0xDC02  @ bgt #8
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD005  @ beq #0xe
    .hword 0xE013  @ b #0x2a
    .hword 0x2802  @ cmp r0, #2
    .hword 0xD00B  @ beq #0x1a
    .hword 0x2803  @ cmp r0, #3
    .hword 0xD004  @ beq #0xc
    .hword 0xE00E  @ b #0x20
    .hword 0x3601  @ adds r6, #1
    .hword 0xE00C  @ b #0x1c
    .hword 0x3E01  @ subs r6, #1
    .hword 0xE00A  @ b #0x18
    .hword 0x2704  @ movs r7, #4
    .hword 0x44B8  @ add r8, r7
    .hword 0x2001  @ movs r0, #1
    .hword 0x4481  @ add sb, r0
    .hword 0xE005  @ b #0xe
    .hword 0x2104  @ movs r1, #4
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x4488  @ add r8, r1
    .hword 0x2201  @ movs r2, #1
    .hword 0x4252  @ rsbs r2, r2, #0
    .hword 0x4491  @ add sb, r2
    .hword 0x490B  @ ldr r1, [pc, #0x2c]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x4440  @ add r0, r8
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1980  @ adds r0, r0, r6
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0xE751  @ b #0xfffffea6
    .hword 0x9803  @ ldr r0, [sp, #0xc]
    .hword 0x9902  @ ldr r1, [sp, #8]
    .word 0xF80BF000  @ bl #0x1a
    .hword 0xB005  @ add sp, #0x14
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .incbin "rom/fe7eu.gba", 0x1A434, 0x2

    .global sub_801A3F0
    .type sub_801A3F0, %function
    .thumb
    .thumb_func
sub_801A3F0:  @ 0x0801A436 (jp 0x0801A3F0, score 0.9231)
    .hword 0xB090  @ sub sp, #0x40
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x466A  @ mov r2, sp
    .hword 0x4299  @ cmp r1, r3
    .hword 0xD905  @ bls #0xe
    .hword 0x3901  @ subs r1, #1
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x7010  @ strb r0, [r2]
    .hword 0x3201  @ adds r2, #1
    .hword 0x4299  @ cmp r1, r3
    .hword 0xD8F9  @ bhi #0xfffffff6
    .hword 0x2004  @ movs r0, #4
    .hword 0x7010  @ strb r0, [r2]
    .hword 0x466A  @ mov r2, sp
    .hword 0xE002  @ b #8
    .hword 0x7018  @ strb r0, [r3]
    .hword 0x3201  @ adds r2, #1
    .hword 0x3301  @ adds r3, #1
    .hword 0x7810  @ ldrb r0, [r2]
    .hword 0x2804  @ cmp r0, #4
    .hword 0xD1F9  @ bne #0xfffffff6
    .hword 0x2004  @ movs r0, #4
    .hword 0x7018  @ strb r0, [r3]
    .hword 0xB010  @ add sp, #0x40
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .incbin "rom/fe7eu.gba", 0x1A46A, 0x2

    .global sub_801A424
    .type sub_801A424, %function
    .thumb
    .thumb_func
sub_801A424:  @ 0x0801A46C (jp 0x0801A424, score 0.8125)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x1C07  @ adds r7, r0, #0
    .hword 0x1C0B  @ adds r3, r1, #0
    .hword 0x1C14  @ adds r4, r2, #0
    .hword 0x4D02  @ ldr r5, [pc, #8]
    .hword 0x4E03  @ ldr r6, [pc, #0xc]
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x4684  @ mov ip, r0
    .hword 0xE007  @ b #0x12
    .hword 0x0000  @ movs r0, r0
    .hword 0x3E00  @ subs r6, #0
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0xA85C  @ add r0, sp, #0x170
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0xE3F0  @ b #0x7e4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x3501  @ adds r5, #1
    .hword 0x73B3  @ strb r3, [r6, #0xe]
    .hword 0x73F4  @ strb r4, [r6, #0xf]
    .hword 0x7828  @ ldrb r0, [r5]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD00E  @ beq #0x20
    .hword 0x2801  @ cmp r0, #1
    .hword 0xDC02  @ bgt #8
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD008  @ beq #0x14
    .hword 0xE00A  @ b #0x18
    .hword 0x2802  @ cmp r0, #2
    .hword 0xD003  @ beq #0xa
    .hword 0x2803  @ cmp r0, #3
    .hword 0xD106  @ bne #0x10
    .hword 0x3C01  @ subs r4, #1
    .hword 0xE004  @ b #0xc
    .hword 0x3401  @ adds r4, #1
    .hword 0xE002  @ b #8
    .hword 0x3B01  @ subs r3, #1
    .hword 0xE000  @ b #4
    .hword 0x3301  @ adds r3, #1
    .hword 0x6838  @ ldr r0, [r7]
    .hword 0x687A  @ ldr r2, [r7, #4]
    .hword 0x6A81  @ ldr r1, [r0, #0x28]
    .hword 0x6A90  @ ldr r0, [r2, #0x28]
    .hword 0x4301  @ orrs r1, r0
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x4001  @ ands r1, r0
    .hword 0x00A2  @ lsls r2, r4, #2
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD113  @ bne #0x2a
    .hword 0x4661  @ mov r1, ip
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1810  @ adds r0, r2, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x18C0  @ adds r0, r0, r3
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x2002  @ movs r0, #2
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD009  @ beq #0x16
    .hword 0x2004  @ movs r0, #4
    .hword 0x7068  @ strb r0, [r5, #1]
    .hword 0x201B  @ movs r0, #0x1b
    .hword 0x7470  @ strb r0, [r6, #0x11]
    .hword 0x73B3  @ strb r3, [r6, #0xe]
    .hword 0x73F4  @ strb r4, [r6, #0xf]
    .hword 0xE016  @ b #0x30
    .hword 0x0000  @ movs r0, r0
    .hword 0x1808  @ adds r0, r1, r0
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x4661  @ mov r1, ip
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1810  @ adds r0, r2, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x18C0  @ adds r0, r0, r3
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .hword 0x4008  @ ands r0, r1
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD006  @ beq #0x10
    .hword 0x200A  @ movs r0, #0xa
    .hword 0x7028  @ strb r0, [r5]
    .hword 0x2004  @ movs r0, #4
    .hword 0x7068  @ strb r0, [r5, #1]
    .hword 0x201B  @ movs r0, #0x1b
    .hword 0x7470  @ strb r0, [r6, #0x11]
    .hword 0xE002  @ b #8
    .hword 0x7828  @ ldrb r0, [r5]
    .hword 0x2804  @ cmp r0, #4
    .hword 0xD1B7  @ bne #0xffffff72
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_801A4DC
    .type sub_801A4DC, %function
    .thumb
    .thumb_func
sub_801A4DC:  @ 0x0801A524 (jp 0x0801A4DC, score 0.9375)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0x4935  @ ldr r1, [pc, #0xd4]
    .hword 0x2202  @ movs r2, #2
    .hword 0x5E88  @ ldrsh r0, [r1, r2]
    .hword 0x1E44  @ subs r4, r0, #1
    .hword 0x4F34  @ ldr r7, [pc, #0xd0]
    .hword 0x46B9  @ mov sb, r7
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xDB56  @ blt #0xb0
    .hword 0x468C  @ mov ip, r1
    .hword 0x46CA  @ mov sl, sb
    .hword 0x4661  @ mov r1, ip
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E88  @ ldrsh r0, [r1, r2]
    .hword 0x1E43  @ subs r3, r0, #1
    .hword 0x1E67  @ subs r7, r4, #1
    .hword 0x46B8  @ mov r8, r7
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xDB49  @ blt #0x96
    .hword 0x00A5  @ lsls r5, r4, #2
    .hword 0x4656  @ mov r6, sl
    .hword 0x492D  @ ldr r1, [pc, #0xb4]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x18C1  @ adds r1, r0, r3
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x2878  @ cmp r0, #0x78
    .hword 0xD83C  @ bhi #0x7c
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x7AF2  @ ldrb r2, [r6, #0xb]
    .hword 0x4290  @ cmp r0, r2
    .hword 0xD037  @ beq #0x72
    .hword 0x3901  @ subs r1, #1
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA02  @ bge #8
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xD000  @ beq #4
    .hword 0x700A  @ strb r2, [r1]
    .hword 0x4A22  @ ldr r2, [pc, #0x88]
    .hword 0x6810  @ ldr r0, [r2]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1819  @ adds r1, r3, r0
    .hword 0x2001  @ movs r0, #1
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA07  @ bge #0x12
    .hword 0x4667  @ mov r7, ip
    .hword 0x2200  @ movs r2, #0
    .hword 0x5EB8  @ ldrsh r0, [r7, r2]
    .hword 0x3801  @ subs r0, #1
    .hword 0x4283  @ cmp r3, r0
    .hword 0xD001  @ beq #6
    .hword 0x7AF0  @ ldrb r0, [r6, #0xb]
    .hword 0x7048  @ strb r0, [r1, #1]
    .hword 0x4F1A  @ ldr r7, [pc, #0x68]
    .hword 0x6838  @ ldr r0, [r7]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x3804  @ subs r0, #4
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x18C1  @ adds r1, r0, r3
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA03  @ bge #0xa
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD001  @ beq #6
    .hword 0x7AF0  @ ldrb r0, [r6, #0xb]
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x4913  @ ldr r1, [pc, #0x4c]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x6840  @ ldr r0, [r0, #4]
    .hword 0x18C1  @ adds r1, r0, r3
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA07  @ bge #0x12
    .hword 0x4662  @ mov r2, ip
    .hword 0x2702  @ movs r7, #2
    .hword 0x5FD0  @ ldrsh r0, [r2, r7]
    .hword 0x3801  @ subs r0, #1
    .hword 0x4284  @ cmp r4, r0
    .hword 0xD001  @ beq #6
    .hword 0x7AF0  @ ldrb r0, [r6, #0xb]
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x3B01  @ subs r3, #1
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xDAB7  @ bge #0xffffff72
    .hword 0x4644  @ mov r4, r8
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xDAAA  @ bge #0xffffff58
    .hword 0x4649  @ mov r1, sb
    .hword 0x7AC8  @ ldrb r0, [r1, #0xb]
    .hword 0x3001  @ adds r0, #1
    .hword 0x72C8  @ strb r0, [r1, #0xb]
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x46A0  @ mov r8, r4
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0xE3E4  @ b #0x7cc
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_801A5C8
    .type sub_801A5C8, %function
    .thumb
    .thumb_func
sub_801A5C8:  @ 0x0801A610 (jp 0x0801A5C8, score 0.9375)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0x4935  @ ldr r1, [pc, #0xd4]
    .hword 0x2202  @ movs r2, #2
    .hword 0x5E88  @ ldrsh r0, [r1, r2]
    .hword 0x1E44  @ subs r4, r0, #1
    .hword 0x4F34  @ ldr r7, [pc, #0xd0]
    .hword 0x46B9  @ mov sb, r7
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xDB56  @ blt #0xb0
    .hword 0x468C  @ mov ip, r1
    .hword 0x46CA  @ mov sl, sb
    .hword 0x4661  @ mov r1, ip
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E88  @ ldrsh r0, [r1, r2]
    .hword 0x1E43  @ subs r3, r0, #1
    .hword 0x1E67  @ subs r7, r4, #1
    .hword 0x46B8  @ mov r8, r7
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xDB49  @ blt #0x96
    .hword 0x00A5  @ lsls r5, r4, #2
    .hword 0x4656  @ mov r6, sl
    .hword 0x492D  @ ldr r1, [pc, #0xb4]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x18C1  @ adds r1, r0, r3
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x2878  @ cmp r0, #0x78
    .hword 0xD83C  @ bhi #0x7c
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x7AF2  @ ldrb r2, [r6, #0xb]
    .hword 0x4290  @ cmp r0, r2
    .hword 0xD037  @ beq #0x72
    .hword 0x3901  @ subs r1, #1
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA02  @ bge #8
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xD000  @ beq #4
    .hword 0x700A  @ strb r2, [r1]
    .hword 0x4A22  @ ldr r2, [pc, #0x88]
    .hword 0x6810  @ ldr r0, [r2]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1819  @ adds r1, r3, r0
    .hword 0x2001  @ movs r0, #1
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA07  @ bge #0x12
    .hword 0x4667  @ mov r7, ip
    .hword 0x2200  @ movs r2, #0
    .hword 0x5EB8  @ ldrsh r0, [r7, r2]
    .hword 0x3801  @ subs r0, #1
    .hword 0x4283  @ cmp r3, r0
    .hword 0xD001  @ beq #6
    .hword 0x7AF0  @ ldrb r0, [r6, #0xb]
    .hword 0x7048  @ strb r0, [r1, #1]
    .hword 0x4F1A  @ ldr r7, [pc, #0x68]
    .hword 0x6838  @ ldr r0, [r7]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x3804  @ subs r0, #4
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x18C1  @ adds r1, r0, r3
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA03  @ bge #0xa
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD001  @ beq #6
    .hword 0x7AF0  @ ldrb r0, [r6, #0xb]
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x4913  @ ldr r1, [pc, #0x4c]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x6840  @ ldr r0, [r0, #4]
    .hword 0x18C1  @ adds r1, r0, r3
    .hword 0x2000  @ movs r0, #0
    .hword 0x5608  @ ldrsb r0, [r1, r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDA07  @ bge #0x12
    .hword 0x4662  @ mov r2, ip
    .hword 0x2702  @ movs r7, #2
    .hword 0x5FD0  @ ldrsh r0, [r2, r7]
    .hword 0x3801  @ subs r0, #1
    .hword 0x4284  @ cmp r4, r0
    .hword 0xD001  @ beq #6
    .hword 0x7AF0  @ ldrb r0, [r6, #0xb]
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x3B01  @ subs r3, #1
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xDAB7  @ bge #0xffffff72
    .hword 0x4644  @ mov r4, r8
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xDAAA  @ bge #0xffffff58
    .hword 0x4649  @ mov r1, sb
    .hword 0x7AC8  @ ldrb r0, [r1, #0xb]
    .hword 0x3001  @ adds r0, #1
    .hword 0x72C8  @ strb r0, [r1, #0xb]
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x46A0  @ mov r8, r4
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global sub_801A6B4
    .type sub_801A6B4, %function
    .thumb
    .thumb_func
sub_801A6B4:  @ 0x0801A6FC (jp 0x0801A6B4, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB081  @ sub sp, #4
    .hword 0x9000  @ str r0, [sp]
    .hword 0x4689  @ mov sb, r1
    .hword 0x4690  @ mov r8, r2
    .hword 0x469A  @ mov sl, r3
    .hword 0x4645  @ mov r5, r8
    .hword 0x464C  @ mov r4, sb
    .hword 0x1960  @ adds r0, r4, r5
    .hword 0x4284  @ cmp r4, r0
    .hword 0xDC30  @ bgt #0x64
    .hword 0x4937  @ ldr r1, [pc, #0xdc]
    .hword 0x2202  @ movs r2, #2
    .hword 0x5E88  @ ldrsh r0, [r1, r2]
    .hword 0x4284  @ cmp r4, r0
    .hword 0xDA2B  @ bge #0x5a
    .hword 0x9E00  @ ldr r6, [sp]
    .hword 0x1B71  @ subs r1, r6, r5
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x3001  @ adds r0, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDA01  @ bge #6
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x2100  @ movs r1, #0
    .hword 0x180B  @ adds r3, r1, r0
    .hword 0x4A30  @ ldr r2, [pc, #0xc0]
    .hword 0x2600  @ movs r6, #0
    .hword 0x5F90  @ ldrsh r0, [r2, r6]
    .hword 0x4283  @ cmp r3, r0
    .hword 0xDD00  @ ble #4
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C0A  @ adds r2, r1, #0
    .hword 0x3D01  @ subs r5, #1
    .hword 0x1C67  @ adds r7, r4, #1
    .hword 0x464E  @ mov r6, sb
    .hword 0x4446  @ add r6, r8
    .hword 0x429A  @ cmp r2, r3
    .hword 0xDA0D  @ bge #0x1e
    .hword 0x482A  @ ldr r0, [pc, #0xa8]
    .hword 0x4684  @ mov ip, r0
    .hword 0x00A4  @ lsls r4, r4, #2
    .hword 0x4661  @ mov r1, ip
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1820  @ adds r0, r4, r0
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x1889  @ adds r1, r1, r2
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x4450  @ add r0, sl
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x3201  @ adds r2, #1
    .hword 0x429A  @ cmp r2, r3
    .hword 0xDBF4  @ blt #0xffffffec
    .hword 0x1C3C  @ adds r4, r7, #0
    .hword 0x42B4  @ cmp r4, r6
    .hword 0xDC04  @ bgt #0xc
    .hword 0x4A21  @ ldr r2, [pc, #0x84]
    .hword 0x2602  @ movs r6, #2
    .hword 0x5F90  @ ldrsh r0, [r2, r6]
    .hword 0x4284  @ cmp r4, r0
    .hword 0xDBD3  @ blt #0xffffffaa
    .hword 0x4645  @ mov r5, r8
    .hword 0x3D01  @ subs r5, #1
    .hword 0x464C  @ mov r4, sb
    .hword 0x3C01  @ subs r4, #1
    .hword 0x4648  @ mov r0, sb
    .hword 0x4641  @ mov r1, r8
    .hword 0x1A40  @ subs r0, r0, r1
    .hword 0x4680  @ mov r8, r0
    .hword 0x4544  @ cmp r4, r8
    .hword 0xDB2A  @ blt #0x58
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xDB28  @ blt #0x54
    .hword 0x4A18  @ ldr r2, [pc, #0x60]
    .hword 0x4694  @ mov ip, r2
    .hword 0x4E18  @ ldr r6, [pc, #0x60]
    .hword 0x46B1  @ mov sb, r6
    .hword 0x9800  @ ldr r0, [sp]
    .hword 0x1B41  @ subs r1, r0, r5
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x3001  @ adds r0, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDA01  @ bge #6
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x2100  @ movs r1, #0
    .hword 0x180B  @ adds r3, r1, r0
    .hword 0x4662  @ mov r2, ip
    .hword 0x2600  @ movs r6, #0
    .hword 0x5F90  @ ldrsh r0, [r2, r6]
    .hword 0x4283  @ cmp r3, r0
    .hword 0xDD00  @ ble #4
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x1C0A  @ adds r2, r1, #0
    .hword 0x3D01  @ subs r5, #1
    .hword 0x1E66  @ subs r6, r4, #1
    .hword 0x429A  @ cmp r2, r3
    .hword 0xDA0B  @ bge #0x1a
    .hword 0x464F  @ mov r7, sb
    .hword 0x00A4  @ lsls r4, r4, #2
    .hword 0x6838  @ ldr r0, [r7]
    .hword 0x1820  @ adds r0, r4, r0
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x1889  @ adds r1, r1, r2
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x4450  @ add r0, sl
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x3201  @ adds r2, #1
    .hword 0x429A  @ cmp r2, r3
    .hword 0xDBF5  @ blt #0xffffffee
    .hword 0x1C34  @ adds r4, r6, #0
    .hword 0x4546  @ cmp r6, r8
    .hword 0xDB01  @ blt #6
    .hword 0x2E00  @ cmp r6, #0
    .hword 0xDADA  @ bge #0xffffffb8
    .hword 0xB001  @ add sp, #4
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global sub_801A7B8
    .type sub_801A7B8, %function
    .thumb
    .thumb_func
sub_801A7B8:  @ 0x0801A800 (jp 0x0801A7B8, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB081  @ sub sp, #4
    .hword 0x9000  @ str r0, [sp]
    .hword 0x4689  @ mov sb, r1
    .hword 0x4690  @ mov r8, r2
    .hword 0x469A  @ mov sl, r3
    .hword 0x4645  @ mov r5, r8
    .hword 0x464B  @ mov r3, sb
    .hword 0x1958  @ adds r0, r3, r5
    .hword 0x4283  @ cmp r3, r0
    .hword 0xDC2E  @ bgt #0x60
    .hword 0x4C35  @ ldr r4, [pc, #0xd4]
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E60  @ ldrsh r0, [r4, r1]
    .hword 0x4283  @ cmp r3, r0
    .hword 0xDA29  @ bge #0x56
    .hword 0x9A00  @ ldr r2, [sp]
    .hword 0x1B51  @ subs r1, r2, r5
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x3001  @ adds r0, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDA01  @ bge #6
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x2100  @ movs r1, #0
    .hword 0x180A  @ adds r2, r1, r0
    .hword 0x4C2E  @ ldr r4, [pc, #0xb8]
    .hword 0x2600  @ movs r6, #0
    .hword 0x5FA0  @ ldrsh r0, [r4, r6]
    .hword 0x4282  @ cmp r2, r0
    .hword 0xDD00  @ ble #4
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x1E6E  @ subs r6, r5, #1
    .hword 0x1C5F  @ adds r7, r3, #1
    .hword 0x4648  @ mov r0, sb
    .hword 0x4440  @ add r0, r8
    .hword 0x4684  @ mov ip, r0
    .hword 0x4291  @ cmp r1, r2
    .hword 0xDA0A  @ bge #0x18
    .hword 0x4D28  @ ldr r5, [pc, #0xa0]
    .hword 0x009C  @ lsls r4, r3, #2
    .hword 0x6828  @ ldr r0, [r5]
    .hword 0x1820  @ adds r0, r4, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4653  @ mov r3, sl
    .hword 0x7003  @ strb r3, [r0]
    .hword 0x3101  @ adds r1, #1
    .hword 0x4291  @ cmp r1, r2
    .hword 0xDBF6  @ blt #0xfffffff0
    .hword 0x1C35  @ adds r5, r6, #0
    .hword 0x1C3B  @ adds r3, r7, #0
    .hword 0x4563  @ cmp r3, ip
    .hword 0xDC04  @ bgt #0xc
    .hword 0x4C20  @ ldr r4, [pc, #0x80]
    .hword 0x2602  @ movs r6, #2
    .hword 0x5FA0  @ ldrsh r0, [r4, r6]
    .hword 0x4283  @ cmp r3, r0
    .hword 0xDBD5  @ blt #0xffffffae
    .hword 0x4645  @ mov r5, r8
    .hword 0x3D01  @ subs r5, #1
    .hword 0x464B  @ mov r3, sb
    .hword 0x3B01  @ subs r3, #1
    .hword 0x4648  @ mov r0, sb
    .hword 0x4641  @ mov r1, r8
    .hword 0x1A40  @ subs r0, r0, r1
    .hword 0x4680  @ mov r8, r0
    .hword 0x4543  @ cmp r3, r8
    .hword 0xDB29  @ blt #0x56
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xDB27  @ blt #0x52
    .hword 0x4A17  @ ldr r2, [pc, #0x5c]
    .hword 0x4694  @ mov ip, r2
    .hword 0x4C17  @ ldr r4, [pc, #0x5c]
    .hword 0x46A1  @ mov sb, r4
    .hword 0x9E00  @ ldr r6, [sp]
    .hword 0x1B71  @ subs r1, r6, r5
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x3001  @ adds r0, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDA01  @ bge #6
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x2100  @ movs r1, #0
    .hword 0x180A  @ adds r2, r1, r0
    .hword 0x4664  @ mov r4, ip
    .hword 0x2600  @ movs r6, #0
    .hword 0x5FA0  @ ldrsh r0, [r4, r6]
    .hword 0x4282  @ cmp r2, r0
    .hword 0xDD00  @ ble #4
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x1E6E  @ subs r6, r5, #1
    .hword 0x1E5C  @ subs r4, r3, #1
    .hword 0x4291  @ cmp r1, r2
    .hword 0xDA0A  @ bge #0x18
    .hword 0x464F  @ mov r7, sb
    .hword 0x009D  @ lsls r5, r3, #2
    .hword 0x6838  @ ldr r0, [r7]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4653  @ mov r3, sl
    .hword 0x7003  @ strb r3, [r0]
    .hword 0x3101  @ adds r1, #1
    .hword 0x4291  @ cmp r1, r2
    .hword 0xDBF6  @ blt #0xfffffff0
    .hword 0x1C35  @ adds r5, r6, #0
    .hword 0x1C23  @ adds r3, r4, #0
    .hword 0x4544  @ cmp r4, r8
    .hword 0xDB01  @ blt #6
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xDADB  @ bge #0xffffffba
    .hword 0xB001  @ add sp, #4
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .incbin "rom/fe7eu.gba", 0x1A8FC, 0x93C

    .global sub_801B1F0
    .type sub_801B1F0, %function
    .thumb
    .thumb_func
sub_801B1F0:  @ 0x0801B238 (jp 0x0801B1F0, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0x1C04  @ adds r4, r0, #0
    .word 0xF87CF7FC  @ bl #0xffffc0fc
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFB38F7FD  @ bl #0xffffd674
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x2D03  @ cmp r5, #3
    .hword 0xD050  @ beq #0xa4
    .hword 0x2D03  @ cmp r5, #3
    .hword 0xDC02  @ bgt #8
    .hword 0x2D01  @ cmp r5, #1
    .hword 0xD004  @ beq #0xc
    .hword 0xE0D8  @ b #0x1b4
    .hword 0x2D20  @ cmp r5, #0x20
    .hword 0xD100  @ bne #4
    .hword 0xE090  @ b #0x124
    .hword 0xE0D4  @ b #0x1ac
    .hword 0x481F  @ ldr r0, [pc, #0x7c]
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x1E41  @ subs r1, r0, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDA00  @ bge #4
    .hword 0xE0CD  @ b #0x19e
    .hword 0x481C  @ ldr r0, [pc, #0x70]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E80  @ ldrsh r0, [r0, r2]
    .hword 0x1E45  @ subs r5, r0, #1
    .hword 0x1E4B  @ subs r3, r1, #1
    .hword 0x4698  @ mov r8, r3
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDB2C  @ blt #0x5c
    .hword 0x008E  @ lsls r6, r1, #2
    .hword 0x0408  @ lsls r0, r1, #0x10
    .hword 0x1407  @ asrs r7, r0, #0x10
    .hword 0x4817  @ ldr r0, [pc, #0x5c]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2878  @ cmp r0, #0x78
    .hword 0xD81E  @ bhi #0x40
    .hword 0x4814  @ ldr r0, [pc, #0x50]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD116  @ bne #0x30
    .hword 0x4811  @ ldr r0, [pc, #0x44]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10E  @ bne #0x20
    .hword 0x042C  @ lsls r4, r5, #0x10
    .hword 0x1424  @ asrs r4, r4, #0x10
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x2201  @ movs r2, #1
    .hword 0x2301  @ movs r3, #1
    .word 0xFA18F7FF  @ bl #0xfffff434
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x2200  @ movs r2, #0
    .hword 0x2301  @ movs r3, #1
    .hword 0x425B  @ rsbs r3, r3, #0
    .word 0xFA11F7FF  @ bl #0xfffff426
    .hword 0x3D01  @ subs r5, #1
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDAD5  @ bge #0xffffffae
    .hword 0x4641  @ mov r1, r8
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDAC7  @ bge #0xffffff92
    .hword 0xE094  @ b #0x12c
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3E4  @ b #0x7cc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3DC  @ b #0x7bc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3F4  @ b #0x7ec
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x481F  @ ldr r0, [pc, #0x7c]
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x1E41  @ subs r1, r0, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDA00  @ bge #4
    .hword 0xE085  @ b #0x10e
    .hword 0x481C  @ ldr r0, [pc, #0x70]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E80  @ ldrsh r0, [r0, r2]
    .hword 0x1E45  @ subs r5, r0, #1
    .hword 0x1E4B  @ subs r3, r1, #1
    .hword 0x4698  @ mov r8, r3
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDB2C  @ blt #0x5c
    .hword 0x008E  @ lsls r6, r1, #2
    .hword 0x0408  @ lsls r0, r1, #0x10
    .hword 0x1407  @ asrs r7, r0, #0x10
    .hword 0x4817  @ ldr r0, [pc, #0x5c]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2878  @ cmp r0, #0x78
    .hword 0xD81E  @ bhi #0x40
    .hword 0x4814  @ ldr r0, [pc, #0x50]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD116  @ bne #0x30
    .hword 0x4811  @ ldr r0, [pc, #0x44]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10E  @ bne #0x20
    .hword 0x042C  @ lsls r4, r5, #0x10
    .hword 0x1424  @ asrs r4, r4, #0x10
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x2202  @ movs r2, #2
    .hword 0x2301  @ movs r3, #1
    .word 0xF9D0F7FF  @ bl #0xfffff3a4
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x2200  @ movs r2, #0
    .hword 0x2301  @ movs r3, #1
    .hword 0x425B  @ rsbs r3, r3, #0
    .word 0xF9C9F7FF  @ bl #0xfffff396
    .hword 0x3D01  @ subs r5, #1
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDAD5  @ bge #0xffffffae
    .hword 0x4641  @ mov r1, r8
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDAC7  @ bge #0xffffff92
    .hword 0xE04C  @ b #0x9c
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3E4  @ b #0x7cc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3DC  @ b #0x7bc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3F4  @ b #0x7ec
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x4825  @ ldr r0, [pc, #0x94]
    .hword 0x2102  @ movs r1, #2
    .hword 0x5E40  @ ldrsh r0, [r0, r1]
    .hword 0x1E41  @ subs r1, r0, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDB3E  @ blt #0x80
    .hword 0x0410  @ lsls r0, r2, #0x10
    .hword 0x1400  @ asrs r0, r0, #0x10
    .hword 0x4682  @ mov sl, r0
    .hword 0x4821  @ ldr r0, [pc, #0x84]
    .hword 0x2200  @ movs r2, #0
    .hword 0x5E80  @ ldrsh r0, [r0, r2]
    .hword 0x1E45  @ subs r5, r0, #1
    .hword 0x1E4B  @ subs r3, r1, #1
    .hword 0x4698  @ mov r8, r3
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDB30  @ blt #0x64
    .hword 0x008E  @ lsls r6, r1, #2
    .hword 0x0408  @ lsls r0, r1, #0x10
    .hword 0x1407  @ asrs r7, r0, #0x10
    .hword 0x4650  @ mov r0, sl
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4681  @ mov sb, r0
    .hword 0x481B  @ ldr r0, [pc, #0x6c]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2878  @ cmp r0, #0x78
    .hword 0xD81F  @ bhi #0x42
    .hword 0x4818  @ ldr r0, [pc, #0x60]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD117  @ bne #0x32
    .hword 0x4815  @ ldr r0, [pc, #0x54]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x1940  @ adds r0, r0, r5
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD10F  @ bne #0x22
    .hword 0x042C  @ lsls r4, r5, #0x10
    .hword 0x1424  @ asrs r4, r4, #0x10
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x464B  @ mov r3, sb
    .hword 0x141A  @ asrs r2, r3, #0x10
    .hword 0x2301  @ movs r3, #1
    .word 0xF982F7FF  @ bl #0xfffff308
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .hword 0x2200  @ movs r2, #0
    .hword 0x2301  @ movs r3, #1
    .hword 0x425B  @ rsbs r3, r3, #0
    .word 0xF97BF7FF  @ bl #0xfffff2fa
    .hword 0x3D01  @ subs r5, #1
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xDAD4  @ bge #0xffffffac
    .hword 0x4641  @ mov r1, r8
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDAC3  @ bge #0xffffff8a
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xE3D8  @ b #0x7b4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3E4  @ b #0x7cc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3DC  @ b #0x7bc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3F4  @ b #0x7ec
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_801B3E8
    .type sub_801B3E8, %function
    .thumb
    .thumb_func
sub_801B3E8:  @ 0x0801B430 (jp 0x0801B3E8, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB081  @ sub sp, #4
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2001  @ movs r0, #1
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x4682  @ mov sl, r0
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x2100  @ movs r1, #0
    .word 0xF843F7FE  @ bl #0xffffe08a
    .word 0xFCC5F008  @ bl #0x898e
    .hword 0x4681  @ mov sb, r0
    .hword 0x464E  @ mov r6, sb
    .hword 0x3601  @ adds r6, #1
    .hword 0xE07A  @ b #0xf8
    .hword 0x0000  @ movs r0, r0
    .hword 0xE3E8  @ b #0x7d4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xFE5DF7FD  @ bl #0xffffdcbe
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD06F  @ beq #0xe2
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD06C  @ beq #0xdc
    .hword 0x9900  @ ldr r1, [sp]
    .hword 0x0608  @ lsls r0, r1, #0x18
    .hword 0x4680  @ mov r8, r0
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD005  @ beq #0xe
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA31F7FD  @ bl #0xffffd466
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD061  @ beq #0xc6
    .hword 0x4823  @ ldr r0, [pc, #0x8c]
    .hword 0x7B40  @ ldrb r0, [r0, #0xd]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00C  @ beq #0x1c
    .hword 0x2111  @ movs r1, #0x11
    .hword 0x5661  @ ldrsb r1, [r4, r1]
    .hword 0x4821  @ ldr r0, [pc, #0x84]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x0089  @ lsls r1, r1, #2
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x2210  @ movs r2, #0x10
    .hword 0x56A2  @ ldrsb r2, [r4, r2]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD050  @ beq #0xa4
    .hword 0x68E5  @ ldr r5, [r4, #0xc]
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x4005  @ ands r5, r0
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD14B  @ bne #0x9a
    .hword 0x6860  @ ldr r0, [r4, #4]
    .hword 0x7C81  @ ldrb r1, [r0, #0x12]
    .hword 0x7F60  @ ldrb r0, [r4, #0x1d]
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x0609  @ lsls r1, r1, #0x18
    .hword 0x1609  @ asrs r1, r1, #0x18
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFDA1F7FE  @ bl #0xffffeb46
    .hword 0x2111  @ movs r1, #0x11
    .hword 0x5661  @ ldrsb r1, [r4, r1]
    .hword 0x4815  @ ldr r0, [pc, #0x54]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x0089  @ lsls r1, r1, #2
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x2210  @ movs r2, #0x10
    .hword 0x56A2  @ ldrsb r2, [r4, r2]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x7807  @ ldrb r7, [r0]
    .hword 0x7005  @ strb r5, [r0]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA00F7FD  @ bl #0xffffd404
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1605  @ asrs r5, r0, #0x18
    .hword 0x45AA  @ cmp sl, r5
    .hword 0xD00A  @ beq #0x18
    .hword 0x480D  @ ldr r0, [pc, #0x34]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x2100  @ movs r1, #0
    .word 0xFFEFF7FD  @ bl #0xffffdfe2
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD002  @ beq #8
    .hword 0x2001  @ movs r0, #1
    .word 0xF836F000  @ bl #0x70
    .hword 0x46AA  @ mov sl, r5
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x4641  @ mov r1, r8
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD00F  @ beq #0x22
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFE8FF7FF  @ bl #0xfffffd22
    .hword 0xE00E  @ b #0x20
    .hword 0xBBF8  @ cbnz r0, #0x82
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3EC  @ b #0x7dc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3DC  @ b #0x7bc
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3F4  @ b #0x7ec
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xE3E8  @ b #0x7d4
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF9E1F7FF  @ bl #0xfffff3c6
    .hword 0x2111  @ movs r1, #0x11
    .hword 0x5661  @ ldrsb r1, [r4, r1]
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x0089  @ lsls r1, r1, #2
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x2210  @ movs r2, #0x10
    .hword 0x56A2  @ ldrsb r2, [r4, r2]
    .hword 0x6808  @ ldr r0, [r1]
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x7007  @ strb r7, [r0]
    .hword 0x3601  @ adds r6, #1
    .hword 0x4648  @ mov r0, sb
    .hword 0x3080  @ adds r0, #0x80
    .hword 0x4286  @ cmp r6, r0
    .hword 0xDA00  @ bge #4
    .hword 0xE783  @ b #0xffffff0a
    .hword 0xB001  @ add sp, #4
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xE3DC  @ b #0x7bc
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_801B528
    .type sub_801B528, %function
    .thumb
    .thumb_func
sub_801B528:  @ 0x0801B570 (jp 0x0801B528, score 1.0)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x2481  @ movs r4, #0x81
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFDD4F7FD  @ bl #0xffffdbac
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD013  @ beq #0x2a
    .hword 0x6811  @ ldr r1, [r2]
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD010  @ beq #0x24
    .hword 0x6850  @ ldr r0, [r2, #4]
    .hword 0x6A89  @ ldr r1, [r1, #0x28]
    .hword 0x6A80  @ ldr r0, [r0, #0x28]
    .hword 0x4301  @ orrs r1, r0
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x04C0  @ lsls r0, r0, #0x13
    .hword 0x4001  @ ands r1, r0
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD007  @ beq #0x12
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x5610  @ ldrsb r0, [r2, r0]
    .hword 0x2111  @ movs r1, #0x11
    .hword 0x5651  @ ldrsb r1, [r2, r1]
    .hword 0x220A  @ movs r2, #0xa
    .hword 0x1C2B  @ adds r3, r5, #0
    .word 0xF92BF7FF  @ bl #0xfffff25a
    .hword 0x3401  @ adds r4, #1
    .hword 0x2CBF  @ cmp r4, #0xbf
    .hword 0xDDE2  @ ble #0xffffffc8
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global SetWorkingBmMap
    .type SetWorkingBmMap, %function
    .thumb
    .thumb_func
SetWorkingBmMap:  @ 0x0801B5B8 (jp 0x0801B570, score 0.8333)
    .hword 0x4901  @ ldr r1, [pc, #4]
    .hword 0x6008  @ str r0, [r1]
    .hword 0x4770  @ bx lr
    .hword 0x0000  @ movs r0, r0
    .hword 0x41E0  @ rors r0, r4
    .hword 0x0300  @ lsls r0, r0, #0xc

    .global MapAddInBoundedRange
    .type MapAddInBoundedRange, %function
    .thumb
    .thumb_func
MapAddInBoundedRange:  @ 0x0801B5C4 (jp 0x0801B57C, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x1C14  @ adds r4, r2, #0
    .hword 0x1C1A  @ adds r2, r3, #0
    .hword 0x0424  @ lsls r4, r4, #0x10
    .hword 0x0C24  @ lsrs r4, r4, #0x10
    .hword 0x042D  @ lsls r5, r5, #0x10
    .hword 0x142D  @ asrs r5, r5, #0x10
    .hword 0x0436  @ lsls r6, r6, #0x10
    .hword 0x1436  @ asrs r6, r6, #0x10
    .hword 0x0412  @ lsls r2, r2, #0x10
    .hword 0x1412  @ asrs r2, r2, #0x10
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x1C31  @ adds r1, r6, #0
    .hword 0x2301  @ movs r3, #1
    .word 0xF88AF7FF  @ bl #0xfffff118
    .hword 0x0424  @ lsls r4, r4, #0x10
    .hword 0x1424  @ asrs r4, r4, #0x10
    .hword 0x3C01  @ subs r4, #1
    .hword 0x2301  @ movs r3, #1
    .hword 0x425B  @ rsbs r3, r3, #0
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x1C31  @ adds r1, r6, #0
    .hword 0x1C22  @ adds r2, r4, #0
    .word 0xF880F7FF  @ bl #0xfffff104
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global GetWorkingMoveCosts
    .type GetWorkingMoveCosts, %function
    .thumb
    .thumb_func
GetWorkingMoveCosts:  @ 0x0801B604 (jp 0x0801B5BC, score 0.75)
    .hword 0x4800  @ ldr r0, [pc, #0]
    .hword 0x4770  @ bx lr
    .hword 0x43F0  @ mvns r0, r6
    .hword 0x0300  @ lsls r0, r0, #0xc

