@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x000942D4-0x00094C88
    .syntax unified

    .global PrepItemTrade_ApplyItemSwap
    .type PrepItemTrade_ApplyItemSwap, %function
    .thumb
    .thumb_func
PrepItemTrade_ApplyItemSwap:  @ 0x080942D4 (jp 0x080948A0, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C16  @ adds r6, r2, #0
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x341E  @ adds r4, #0x1e
    .hword 0x1864  @ adds r4, r4, r1
    .hword 0x8825  @ ldrh r5, [r4]
    .hword 0x005B  @ lsls r3, r3, #1
    .hword 0x1C31  @ adds r1, r6, #0
    .hword 0x311E  @ adds r1, #0x1e
    .hword 0x18C9  @ adds r1, r1, r3
    .hword 0x880A  @ ldrh r2, [r1]
    .hword 0x8022  @ strh r2, [r4]
    .hword 0x800D  @ strh r5, [r1]
    .word 0xFBC6F783  @ bl #0xfff83790
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xFBC3F783  @ bl #0xfff8378a
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .incbin "rom/fe7eu.gba", 0x94300, 0x24C

    .global sub_8094AC0
    .type sub_8094AC0, %function
    .thumb
    .thumb_func
sub_8094AC0:  @ 0x0809454C (jp 0x08094AC0, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB086  @ sub sp, #0x18
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x4689  @ mov sb, r1
    .hword 0x4692  @ mov sl, r2
    .hword 0x061B  @ lsls r3, r3, #0x18
    .hword 0x0E1B  @ lsrs r3, r3, #0x18
    .hword 0x9302  @ str r3, [sp, #8]
    .hword 0x210B  @ movs r1, #0xb
    .hword 0x2209  @ movs r2, #9
    .hword 0x2300  @ movs r3, #0
    .word 0xFF0DF031  @ bl #0x31e1e
    .hword 0x4650  @ mov r0, sl
    .word 0xFAB0F783  @ bl #0xfff83564
    .hword 0x9004  @ str r0, [sp, #0x10]
    .hword 0x2000  @ movs r0, #0
    .hword 0x9003  @ str r0, [sp, #0xc]
    .hword 0x9904  @ ldr r1, [sp, #0x10]
    .hword 0x4288  @ cmp r0, r1
    .hword 0xDA4F  @ bge #0xa2
    .hword 0x1D20  @ adds r0, r4, #4
    .hword 0x9005  @ str r0, [sp, #0x14]
    .hword 0x46A0  @ mov r8, r4
    .hword 0x9803  @ ldr r0, [sp, #0xc]
    .hword 0x0041  @ lsls r1, r0, #1
    .hword 0x4650  @ mov r0, sl
    .hword 0x301E  @ adds r0, #0x1e
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x8806  @ ldrh r6, [r0]
    .hword 0x9902  @ ldr r1, [sp, #8]
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD004  @ beq #0xc
    .hword 0x4650  @ mov r0, sl
    .hword 0x1C31  @ adds r1, r6, #0
    .word 0xF800F794  @ bl #0xfff94004
    .hword 0xE003  @ b #0xa
    .hword 0x4650  @ mov r0, sl
    .hword 0x1C31  @ adds r1, r6, #0
    .word 0xFC2BF782  @ bl #0xfff8285a
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E04  @ lsrs r4, r0, #0x18
    .hword 0x4648  @ mov r0, sb
    .word 0xFFBAF770  @ bl #0xfff70f78
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xFFBFF782  @ bl #0xfff82f82
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2200  @ movs r2, #0
    .hword 0x0620  @ lsls r0, r4, #0x18
    .hword 0x1605  @ asrs r5, r0, #0x18
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD100  @ bne #4
    .hword 0x2201  @ movs r2, #1
    .hword 0x2000  @ movs r0, #0
    .hword 0x9000  @ str r0, [sp]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x4648  @ mov r0, sb
    .hword 0x9905  @ ldr r1, [sp, #0x14]
    .hword 0x2300  @ movs r3, #0
    .word 0xFAA0F771  @ bl #0xfff71544
    .hword 0x4644  @ mov r4, r8
    .hword 0x3416  @ adds r4, #0x16
    .hword 0x2701  @ movs r7, #1
    .hword 0x2D00  @ cmp r5, #0
    .hword 0xD000  @ beq #4
    .hword 0x2702  @ movs r7, #2
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xF827F783  @ bl #0xfff83052
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .word 0xFE14F771  @ bl #0xfff71c2c
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xF8DDF783  @ bl #0xfff831be
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4640  @ mov r0, r8
    .hword 0x2280  @ movs r2, #0x80
    .hword 0x01D2  @ lsls r2, r2, #7
    .word 0xFC2FF770  @ bl #0xfff70862
    .hword 0x2008  @ movs r0, #8
    .hword 0x4481  @ add sb, r0
    .hword 0x9905  @ ldr r1, [sp, #0x14]
    .hword 0x3180  @ adds r1, #0x80
    .hword 0x9105  @ str r1, [sp, #0x14]
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x4480  @ add r8, r0
    .hword 0x9903  @ ldr r1, [sp, #0xc]
    .hword 0x3101  @ adds r1, #1
    .hword 0x9103  @ str r1, [sp, #0xc]
    .hword 0x9804  @ ldr r0, [sp, #0x10]
    .hword 0x4281  @ cmp r1, r0
    .hword 0xDBB2  @ blt #0xffffff68
    .hword 0xB006  @ add sp, #0x18
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_8094BA4
    .type sub_8094BA4, %function
    .thumb
    .thumb_func
sub_8094BA4:  @ 0x08094630 (jp 0x08094BA4, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C0F  @ adds r7, r1, #0
    .hword 0x1C38  @ adds r0, r7, #0
    .word 0xFA4CF783  @ bl #0xfff8349c
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x2500  @ movs r5, #0
    .hword 0x42B5  @ cmp r5, r6
    .hword 0xDA10  @ bge #0x24
    .hword 0x0069  @ lsls r1, r5, #1
    .hword 0x1C38  @ adds r0, r7, #0
    .hword 0x301E  @ adds r0, #0x1e
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x8800  @ ldrh r0, [r0]
    .word 0xF8B1F783  @ bl #0xfff83166
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x2280  @ movs r2, #0x80
    .hword 0x01D2  @ lsls r2, r2, #7
    .word 0xFC03F770  @ bl #0xfff7080a
    .hword 0x3480  @ adds r4, #0x80
    .hword 0x3501  @ adds r5, #1
    .hword 0x42B5  @ cmp r5, r6
    .hword 0xDBEE  @ blt #0xffffffe0
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_8094BE0
    .type sub_8094BE0, %function
    .thumb
    .thumb_func
sub_8094BE0:  @ 0x0809466C (jp 0x08094BE0, score 0.7812)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x464F  @ mov r7, sb
    .hword 0x4646  @ mov r6, r8
    .hword 0xB4C0  @ push {r6, r7}
    .hword 0xB08A  @ sub sp, #0x28
    .hword 0x4680  @ mov r8, r0
    .hword 0xA902  @ add r1, sp, #8
    .hword 0x483A  @ ldr r0, [pc, #0xe8]
    .hword 0xC81C  @ ldm r0!, {r2, r3, r4}
    .hword 0xC11C  @ stm r1!, {r2, r3, r4}
    .hword 0xC81C  @ ldm r0!, {r2, r3, r4}
    .hword 0xC11C  @ stm r1!, {r2, r3, r4}
    .hword 0xC80C  @ ldm r0!, {r2, r3}
    .hword 0xC10C  @ stm r1!, {r2, r3}
    .hword 0x4837  @ ldr r0, [pc, #0xdc]
    .hword 0x8800  @ ldrh r0, [r0]
    .word 0xF9F4F76E  @ bl #0xfff6e3ec
    .hword 0xA802  @ add r0, sp, #8
    .word 0xFAF7F772  @ bl #0xfff725f2
    .hword 0x4B35  @ ldr r3, [pc, #0xd4]
    .hword 0x7B19  @ ldrb r1, [r3, #0xc]
    .hword 0x2204  @ movs r2, #4
    .hword 0x4252  @ rsbs r2, r2, #0
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x4008  @ ands r0, r1
    .hword 0x2101  @ movs r1, #1
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7318  @ strb r0, [r3, #0xc]
    .hword 0x7C19  @ ldrb r1, [r3, #0x10]
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x4008  @ ands r0, r1
    .hword 0x2102  @ movs r1, #2
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7418  @ strb r0, [r3, #0x10]
    .hword 0x7D18  @ ldrb r0, [r3, #0x14]
    .hword 0x4002  @ ands r2, r0
    .hword 0x751A  @ strb r2, [r3, #0x14]
    .hword 0x7E18  @ ldrb r0, [r3, #0x18]
    .hword 0x2103  @ movs r1, #3
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7618  @ strb r0, [r3, #0x18]
    .hword 0x2000  @ movs r0, #0
    .word 0xFA96F76E  @ bl #0xfff6e530
    .hword 0x2100  @ movs r1, #0
    .word 0xF8A7F76D  @ bl #0xfff6d152
    .hword 0x2001  @ movs r0, #1
    .word 0xFA90F76E  @ bl #0xfff6e524
    .hword 0x2100  @ movs r1, #0
    .word 0xF8A1F76D  @ bl #0xfff6d146
    .hword 0x2002  @ movs r0, #2
    .word 0xFA8AF76E  @ bl #0xfff6e518
    .hword 0x2100  @ movs r1, #0
    .word 0xF89BF76D  @ bl #0xfff6d13a
    .word 0xFE85F770  @ bl #0xfff70d0e
    .word 0xFB19F770  @ bl #0xfff70636
    .word 0xFC4DF7B5  @ bl #0xfffb589e
    .word 0xF8A5F781  @ bl #0xfff8114e
    .hword 0x2000  @ movs r0, #0
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xFB4CF76D  @ bl #0xfff6d69c
    .hword 0x2001  @ movs r0, #1
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xFB47F76D  @ bl #0xfff6d692
    .hword 0x2002  @ movs r0, #2
    .hword 0x2100  @ movs r1, #0
    .hword 0x2200  @ movs r2, #0
    .word 0xFB42F76D  @ bl #0xfff6d688
    .hword 0x4816  @ ldr r0, [pc, #0x58]
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .word 0xFF61F7ED  @ bl #0xfffedec6
    .hword 0x2004  @ movs r0, #4
    .word 0xFB20F770  @ bl #0xfff70644
    .word 0xFF94F7F9  @ bl #0xffff9f2c
    .hword 0x4812  @ ldr r0, [pc, #0x48]
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x3628  @ adds r6, #0x28
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x2404  @ movs r4, #4
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x2107  @ movs r1, #7
    .word 0xFED5F770  @ bl #0xfff70dae
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x2107  @ movs r1, #7
    .word 0xFED1F770  @ bl #0xfff70da6
    .hword 0x3608  @ adds r6, #8
    .hword 0x3508  @ adds r5, #8
    .hword 0x3C01  @ subs r4, #1
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xDAF2  @ bge #0xffffffe8
    .hword 0x20FF  @ movs r0, #0xff
    .hword 0x4644  @ mov r4, r8
    .hword 0x63A0  @ str r0, [r4, #0x38]
    .hword 0x6C21  @ ldr r1, [r4, #0x40]
    .hword 0x2001  @ movs r0, #1
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x4281  @ cmp r1, r0
    .hword 0xD00D  @ beq #0x1e
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x3008  @ adds r0, #8
    .hword 0x6360  @ str r0, [r4, #0x34]
    .hword 0xE016  @ b #0x30
    .hword 0x1AF4  @ subs r4, r6, r3
    .hword 0x084D  @ lsrs r5, r1, #1
    .hword 0x3688  @ adds r6, #0x88
    .hword 0x08DC  @ lsrs r4, r3, #3
    .hword 0x2870  @ cmp r0, #0x70
    .hword 0x0300  @ lsls r0, r0, #0xc
    .hword 0x4000  @ ands r0, r0
    .hword 0x0601  @ lsls r1, r0, #0x18
    .hword 0x2A20  @ cmp r2, #0x20
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x4641  @ mov r1, r8
    .hword 0x6AC8  @ ldr r0, [r1, #0x2c]
    .word 0xF9AAF783  @ bl #0xfff83358
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD103  @ bne #0xa
    .hword 0x2008  @ movs r0, #8
    .hword 0x4642  @ mov r2, r8
    .hword 0x6350  @ str r0, [r2, #0x34]
    .hword 0xE002  @ b #8
    .hword 0x2000  @ movs r0, #0
    .hword 0x4643  @ mov r3, r8
    .hword 0x6358  @ str r0, [r3, #0x34]
    .hword 0x20FF  @ movs r0, #0xff
    .hword 0x4644  @ mov r4, r8
    .hword 0x63E0  @ str r0, [r4, #0x3c]
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .word 0xFC25F784  @ bl #0xfff8484e
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2404  @ movs r4, #4
    .hword 0x4264  @ rsbs r4, r4, #0
    .hword 0x4862  @ ldr r0, [pc, #0x188]
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2000  @ movs r0, #0
    .hword 0x2240  @ movs r2, #0x40
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFAAFF773  @ bl #0xfff73562
    .hword 0x4641  @ mov r1, r8
    .hword 0x6B08  @ ldr r0, [r1, #0x30]
    .word 0xFC17F784  @ bl #0xfff84832
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x485D  @ ldr r0, [pc, #0x174]
    .hword 0x9000  @ str r0, [sp]
    .hword 0x2001  @ movs r0, #1
    .hword 0x22AE  @ movs r2, #0xae
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFAA3F773  @ bl #0xfff7354a
    .hword 0x2600  @ movs r6, #0
    .hword 0x9600  @ str r6, [sp]
    .hword 0x2001  @ movs r0, #1
    .hword 0x2108  @ movs r1, #8
    .hword 0x220E  @ movs r2, #0xe
    .hword 0x230C  @ movs r3, #0xc
    .word 0xF943F7B5  @ bl #0xfffb528a
    .hword 0x9600  @ str r6, [sp]
    .hword 0x200F  @ movs r0, #0xf
    .hword 0x2108  @ movs r1, #8
    .hword 0x220E  @ movs r2, #0xe
    .hword 0x230C  @ movs r3, #0xc
    .word 0xF93CF7B5  @ bl #0xfffb527c
    .hword 0x2007  @ movs r0, #7
    .word 0xFC0DF76C  @ bl #0xfff6c81e
    .hword 0x4642  @ mov r2, r8
    .hword 0x6AD0  @ ldr r0, [r2, #0x2c]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x8800  @ ldrh r0, [r0]
    .word 0xFB7FF77E  @ bl #0xfff7e702
    .hword 0x1C07  @ adds r7, r0, #0
    .word 0xFF1EF770  @ bl #0xfff70e40
    .hword 0x1C03  @ adds r3, r0, #0
    .hword 0x2430  @ movs r4, #0x30
    .hword 0x1AE3  @ subs r3, r4, r3
    .hword 0x0FD8  @ lsrs r0, r3, #0x1f
    .hword 0x181B  @ adds r3, r3, r0
    .hword 0x105B  @ asrs r3, r3, #1
    .hword 0x484A  @ ldr r0, [pc, #0x128]
    .hword 0x4681  @ mov sb, r0
    .hword 0x2506  @ movs r5, #6
    .hword 0x9500  @ str r5, [sp]
    .hword 0x9701  @ str r7, [sp, #4]
    .hword 0x2000  @ movs r0, #0
    .hword 0x4649  @ mov r1, sb
    .hword 0x2200  @ movs r2, #0
    .word 0xF97CF771  @ bl #0xfff712fc
    .hword 0x4641  @ mov r1, r8
    .hword 0x6B08  @ ldr r0, [r1, #0x30]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x8800  @ ldrh r0, [r0]
    .word 0xFB66F77E  @ bl #0xfff7e6d0
    .hword 0x1C07  @ adds r7, r0, #0
    .word 0xFF05F770  @ bl #0xfff70e0e
    .hword 0x1A24  @ subs r4, r4, r0
    .hword 0x0FE0  @ lsrs r0, r4, #0x1f
    .hword 0x1824  @ adds r4, r4, r0
    .hword 0x1064  @ asrs r4, r4, #1
    .hword 0x4649  @ mov r1, sb
    .hword 0x3130  @ adds r1, #0x30
    .hword 0x9500  @ str r5, [sp]
    .hword 0x9701  @ str r7, [sp, #4]
    .hword 0x2000  @ movs r0, #0
    .hword 0x2200  @ movs r2, #0
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xF966F771  @ bl #0xfff712d0
    .hword 0x2091  @ movs r0, #0x91
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4448  @ add r0, sb
    .hword 0x4C3A  @ ldr r4, [pc, #0xe8]
    .hword 0x4643  @ mov r3, r8
    .hword 0x6ADA  @ ldr r2, [r3, #0x2c]
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x2300  @ movs r3, #0
    .word 0xFE76F7FF  @ bl #0xfffffcf0
    .hword 0x2098  @ movs r0, #0x98
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4448  @ add r0, sb
    .hword 0x3428  @ adds r4, #0x28
    .hword 0x4641  @ mov r1, r8
    .hword 0x6B0A  @ ldr r2, [r1, #0x30]
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x2300  @ movs r3, #0
    .word 0xFE6CF7FF  @ bl #0xfffffcdc
    .hword 0x4640  @ mov r0, r8
    .word 0xFB2FF014  @ bl #0x14662
    .hword 0x4640  @ mov r0, r8
    .word 0xF88AF015  @ bl #0x15118
    .hword 0x20C0  @ movs r0, #0xc0
    .hword 0x00C0  @ lsls r0, r0, #3
    .hword 0x2101  @ movs r1, #1
    .word 0xF897F015  @ bl #0x15132
    .hword 0x4642  @ mov r2, r8
    .hword 0x6B51  @ ldr r1, [r2, #0x34]
    .hword 0x10CA  @ asrs r2, r1, #3
    .hword 0x00D0  @ lsls r0, r2, #3
    .hword 0x1A80  @ subs r0, r0, r2
    .hword 0x0100  @ lsls r0, r0, #4
    .hword 0x3010  @ adds r0, #0x10
    .hword 0x2207  @ movs r2, #7
    .hword 0x4011  @ ands r1, r2
    .hword 0x0109  @ lsls r1, r1, #4
    .hword 0x3148  @ adds r1, #0x48
    .hword 0x2580  @ movs r5, #0x80
    .hword 0x012D  @ lsls r5, r5, #4
    .hword 0x220B  @ movs r2, #0xb
    .hword 0x1C2B  @ adds r3, r5, #0
    .word 0xF8C4F015  @ bl #0x1518c
    .hword 0x20C8  @ movs r0, #0xc8
    .hword 0x2190  @ movs r1, #0x90
    .hword 0x4642  @ mov r2, r8
    .word 0xFB85F7ED  @ bl #0xfffed70e
    .hword 0x21E0  @ movs r1, #0xe0
    .hword 0x0109  @ lsls r1, r1, #4
    .hword 0x23C0  @ movs r3, #0xc0
    .hword 0x011B  @ lsls r3, r3, #4
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x00C0  @ lsls r0, r0, #3
    .hword 0x9000  @ str r0, [sp]
    .hword 0x4644  @ mov r4, r8
    .hword 0x9401  @ str r4, [sp, #4]
    .hword 0x200D  @ movs r0, #0xd
    .hword 0x220F  @ movs r2, #0xf
    .word 0xFBE2F015  @ bl #0x157c8
    .hword 0x2128  @ movs r1, #0x28
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x2401  @ movs r4, #1
    .hword 0x4264  @ rsbs r4, r4, #0
    .hword 0x2000  @ movs r0, #0
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x2301  @ movs r3, #1
    .word 0xFC19F015  @ bl #0x15836
    .hword 0x2001  @ movs r0, #1
    .hword 0x21B8  @ movs r1, #0xb8
    .hword 0x1C22  @ adds r2, r4, #0
    .hword 0x2300  @ movs r3, #0
    .word 0xFC13F015  @ bl #0x1582a
    .hword 0x4B14  @ ldr r3, [pc, #0x50]
    .hword 0x1C1A  @ adds r2, r3, #0
    .hword 0x323C  @ adds r2, #0x3c
    .hword 0x7811  @ ldrb r1, [r2]
    .hword 0x203F  @ movs r0, #0x3f
    .hword 0x4008  @ ands r0, r1
    .hword 0x2140  @ movs r1, #0x40
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7010  @ strb r0, [r2]
    .hword 0x1C19  @ adds r1, r3, #0
    .hword 0x3144  @ adds r1, #0x44
    .hword 0x200E  @ movs r0, #0xe
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x3101  @ adds r1, #1
    .hword 0x2004  @ movs r0, #4
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x3046  @ adds r0, #0x46
    .hword 0x7006  @ strb r6, [r0]
    .hword 0x8F99  @ ldrh r1, [r3, #0x3c]
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x4008  @ ands r0, r1
    .hword 0x490B  @ ldr r1, [pc, #0x2c]
    .hword 0x4008  @ ands r0, r1
    .hword 0x4328  @ orrs r0, r5
    .hword 0x8798  @ strh r0, [r3, #0x3c]
    .hword 0xB00A  @ add sp, #0x28
    .hword 0xBC18  @ pop {r3, r4}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0203  @ lsls r3, r0, #8
    .hword 0x0000  @ movs r0, r0
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x0000  @ movs r0, r0
    .hword 0x2C60  @ cmp r4, #0x60
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x2A20  @ cmp r2, #0x20
    .hword 0x0201  @ lsls r1, r0, #8
    .hword 0x2870  @ cmp r0, #0x70
    .hword 0x0300  @ lsls r0, r0, #0xc
    .word 0x0000FFE0  @ vaddl.u32 q8, d0, d0
    .hword 0xE0FF  @ b #0x202
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x9494C, 0x300

    .global PrepItemTrade_OnEnd
    .type PrepItemTrade_OnEnd, %function
    .thumb
    .thumb_func
PrepItemTrade_OnEnd:  @ 0x08094C4C (jp 0x080951C0, score 1.0)
    .hword 0xB500  @ push {lr}
    .word 0xFD11F7F9  @ bl #0xffff9a26
    .hword 0x2000  @ movs r0, #0
    .word 0xF918F772  @ bl #0xfff72234
    .hword 0x2001  @ movs r0, #1
    .word 0xF915F772  @ bl #0xfff7222e
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global StartPrepItemTradeScreenProc
    .type StartPrepItemTradeScreenProc, %function
    .thumb
    .thumb_func
StartPrepItemTradeScreenProc:  @ 0x08094C64 (jp 0x080951D8, score 0.8824)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0x1C11  @ adds r1, r2, #0
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .word 0xFC49F76F  @ bl #0xfff6f896
    .hword 0x62C4  @ str r4, [r0, #0x2c]
    .hword 0x6305  @ str r5, [r0, #0x30]
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x6401  @ str r1, [r0, #0x40]
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x4554  @ cmp r4, sl
    .hword 0x08DC  @ lsrs r4, r3, #3

