@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x000A6814-0x000A6AE0
    .syntax unified

    .global sub_80A7058
    .type sub_80A7058, %function
    .thumb
    .thumb_func
sub_80A7058:  @ 0x080A6814 (jp 0x080A7058, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0xB092  @ sub sp, #0x48
    .hword 0x1C0D  @ adds r5, r1, #0
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E04  @ lsrs r4, r0, #0x18
    .hword 0x1C26  @ adds r6, r4, #0
    .hword 0x2C02  @ cmp r4, #2
    .hword 0xD859  @ bhi #0xb6
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA75F7FA  @ bl #0xffffa4ee
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1602  @ asrs r2, r0, #0x18
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD038  @ beq #0x74
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x4669  @ mov r1, sp
    .word 0xFA77F7FA  @ bl #0xffffa4f2
    .hword 0x4668  @ mov r0, sp
    .word 0xFE8CF7DB  @ bl #0xfffdbd1c
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x3137  @ adds r1, #0x37
    .hword 0x1909  @ adds r1, r1, r4
    .hword 0x2200  @ movs r2, #0
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x00A1  @ lsls r1, r4, #2
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x3048  @ adds r0, #0x48
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x9900  @ ldr r1, [sp]
    .hword 0x6001  @ str r1, [r0]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x303A  @ adds r0, #0x3a
    .hword 0x1905  @ adds r5, r0, r4
    .hword 0x702A  @ strb r2, [r5]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFA92F7FA  @ bl #0xffffa528
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD003  @ beq #0xa
    .hword 0x7828  @ ldrb r0, [r5]
    .hword 0x2101  @ movs r1, #1
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7028  @ strb r0, [r5]
    .hword 0x4668  @ mov r0, sp
    .word 0xFA7CF7FA  @ bl #0xffffa4fc
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD003  @ beq #0xa
    .hword 0x7828  @ ldrb r0, [r5]
    .hword 0x2102  @ movs r1, #2
    .hword 0x4308  @ orrs r0, r1
    .hword 0x7028  @ strb r0, [r5]
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x1820  @ adds r0, r4, r0
    .hword 0x4669  @ mov r1, sp
    .hword 0x7D09  @ ldrb r1, [r1, #0x14]
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x1820  @ adds r0, r4, r0
    .hword 0x4669  @ mov r1, sp
    .hword 0x7EC9  @ ldrb r1, [r1, #0x1b]
    .hword 0x7001  @ strb r1, [r0]
    .hword 0xE038  @ b #0x74
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x3037  @ adds r0, #0x37
    .hword 0x1980  @ adds r0, r0, r6
    .hword 0x21FF  @ movs r1, #0xff
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x303A  @ adds r0, #0x3a
    .hword 0x1980  @ adds r0, r0, r6
    .hword 0x7002  @ strb r2, [r0]
    .hword 0x00B1  @ lsls r1, r6, #2
    .hword 0x1C28  @ adds r0, r5, #0
    .hword 0x3048  @ adds r0, #0x48
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6002  @ str r2, [r0]
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x7002  @ strb r2, [r0]
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x1830  @ adds r0, r6, r0
    .hword 0x7002  @ strb r2, [r0]
    .hword 0xE01F  @ b #0x42
    .hword 0x0000  @ movs r0, r0
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x1C2C  @ adds r4, r5, #0
    .hword 0x3444  @ adds r4, #0x44
    .hword 0x8821  @ ldrh r1, [r4]
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x4281  @ cmp r1, r0
    .hword 0xD113  @ bne #0x2a
    .hword 0x2003  @ movs r0, #3
    .word 0xFEF2F7FA  @ bl #0xffffade8
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD00B  @ beq #0x1a
    .hword 0x2003  @ movs r0, #3
    .hword 0x4669  @ mov r1, sp
    .word 0xFF15F7FA  @ bl #0xffffae2e
    .hword 0x4668  @ mov r0, sp
    .hword 0x7B00  @ ldrb r0, [r0, #0xc]
    .hword 0x1C29  @ adds r1, r5, #0
    .hword 0x313F  @ adds r1, #0x3f
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x9800  @ ldr r0, [sp]
    .hword 0x6568  @ str r0, [r5, #0x54]
    .hword 0xE001  @ b #6
    .hword 0x20F0  @ movs r0, #0xf0
    .hword 0x8020  @ strh r0, [r4]
    .hword 0xB012  @ add sp, #0x48
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global sub_80A715C
    .type sub_80A715C, %function
    .thumb
    .thumb_func
sub_80A715C:  @ 0x080A6918 (jp 0x080A715C, score 0.9062)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4647  @ mov r7, r8
    .hword 0xB480  @ push {r7}
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .hword 0x4680  @ mov r8, r0
    .hword 0x2500  @ movs r5, #0
    .hword 0x271B  @ movs r7, #0x1b
    .hword 0x261A  @ movs r6, #0x1a
    .hword 0x481D  @ ldr r0, [pc, #0x74]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x2040  @ movs r0, #0x40
    .hword 0x4008  @ ands r0, r1
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x17C4  @ asrs r4, r0, #0x1f
    .hword 0x2004  @ movs r0, #4
    .hword 0x4004  @ ands r4, r0
    .hword 0x4818  @ ldr r0, [pc, #0x60]
    .hword 0x1828  @ adds r0, r5, r0
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x2901  @ cmp r1, #1
    .hword 0xD101  @ bne #6
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x4304  @ orrs r4, r0
    .hword 0x2902  @ cmp r1, #2
    .hword 0xD103  @ bne #0xa
    .hword 0x2020  @ movs r0, #0x20
    .hword 0x4304  @ orrs r4, r0
    .hword 0x0620  @ lsls r0, r4, #0x18
    .hword 0x0E04  @ lsrs r4, r0, #0x18
    .hword 0x2903  @ cmp r1, #3
    .hword 0xD103  @ bne #0xa
    .hword 0x2040  @ movs r0, #0x40
    .hword 0x4304  @ orrs r4, r0
    .hword 0x0620  @ lsls r0, r4, #0x18
    .hword 0x0E04  @ lsrs r4, r0, #0x18
    .hword 0x4545  @ cmp r5, r8
    .hword 0xD003  @ beq #0xa
    .hword 0x2002  @ movs r0, #2
    .hword 0x4304  @ orrs r4, r0
    .hword 0x0620  @ lsls r0, r4, #0x18
    .hword 0x0E04  @ lsrs r4, r0, #0x18
    .hword 0x2101  @ movs r1, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x4308  @ orrs r0, r1
    .hword 0x1C31  @ adds r1, r6, #0
    .word 0xFB6FF7DB  @ bl #0xfffdb6e2
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .word 0xFB6BF7DB  @ bl #0xfffdb6da
    .hword 0x3702  @ adds r7, #2
    .hword 0x3602  @ adds r6, #2
    .hword 0x3501  @ adds r5, #1
    .hword 0x2D02  @ cmp r5, #2
    .hword 0xDDCC  @ ble #0xffffff9c
    .word 0xFB6AF75A  @ bl #0xfff5a6d8
    .hword 0xBC08  @ pop {r3}
    .hword 0x4698  @ mov r8, r3
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x0068  @ lsls r0, r5, #1
    .hword 0x0200  @ lsls r0, r0, #8

    .global sub_80A71EC
    .type sub_80A71EC, %function
    .thumb
    .thumb_func
sub_80A71EC:  @ 0x080A69A8 (jp 0x080A71EC, score 0.9062)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB082  @ sub sp, #8
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x9100  @ str r1, [sp]
    .hword 0x106D  @ asrs r5, r5, #1
    .hword 0x201F  @ movs r0, #0x1f
    .hword 0x4005  @ ands r5, r0
    .hword 0x2D10  @ cmp r5, #0x10
    .hword 0xDD03  @ ble #0xa
    .hword 0x200F  @ movs r0, #0xf
    .hword 0x4028  @ ands r0, r5
    .hword 0x2110  @ movs r1, #0x10
    .hword 0x1A0D  @ subs r5, r1, r0
    .hword 0x2200  @ movs r2, #0
    .hword 0x490B  @ ldr r1, [pc, #0x2c]
    .hword 0x1850  @ adds r0, r2, r1
    .hword 0x7801  @ ldrb r1, [r0]
    .hword 0x2040  @ movs r0, #0x40
    .hword 0x4008  @ ands r0, r1
    .hword 0x1C51  @ adds r1, r2, #1
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD057  @ beq #0xb2
    .hword 0x0190  @ lsls r0, r2, #6
    .hword 0x21A0  @ movs r1, #0xa0
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4906  @ ldr r1, [pc, #0x18]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4680  @ mov r8, r0
    .hword 0x9800  @ ldr r0, [sp]
    .hword 0x4282  @ cmp r2, r0
    .hword 0xD10C  @ bne #0x1c
    .hword 0x4904  @ ldr r1, [pc, #0x10]
    .hword 0x468C  @ mov ip, r1
    .hword 0x4E04  @ ldr r6, [pc, #0x10]
    .hword 0xE00B  @ b #0x1a
    .hword 0x0000  @ movs r0, r0
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x2A72  @ cmp r2, #0x72
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0xC9D6  @ ldm r1, {r1, r2, r4, r6, r7}
    .hword 0x084C  @ lsrs r4, r1, #1
    .hword 0xCAD6  @ ldm r2, {r1, r2, r4, r6, r7}
    .hword 0x084C  @ lsrs r4, r1, #1
    .hword 0x4826  @ ldr r0, [pc, #0x98]
    .hword 0x4684  @ mov ip, r0
    .hword 0x4E26  @ ldr r6, [pc, #0x98]
    .hword 0x3201  @ adds r2, #1
    .hword 0x9201  @ str r2, [sp, #4]
    .hword 0x2010  @ movs r0, #0x10
    .hword 0x1B47  @ subs r7, r0, r5
    .hword 0x21F8  @ movs r1, #0xf8
    .hword 0x01C9  @ lsls r1, r1, #7
    .hword 0x468A  @ mov sl, r1
    .hword 0x2006  @ movs r0, #6
    .hword 0x4681  @ mov sb, r0
    .hword 0x4661  @ mov r1, ip
    .hword 0x880C  @ ldrh r4, [r1]
    .hword 0x201F  @ movs r0, #0x1f
    .hword 0x4020  @ ands r0, r4
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x436A  @ muls r2, r5, r2
    .hword 0x8833  @ ldrh r3, [r6]
    .hword 0x201F  @ movs r0, #0x1f
    .hword 0x4018  @ ands r0, r3
    .hword 0x4378  @ muls r0, r7, r0
    .hword 0x1812  @ adds r2, r2, r0
    .hword 0x1112  @ asrs r2, r2, #4
    .hword 0x201F  @ movs r0, #0x1f
    .hword 0x4002  @ ands r2, r0
    .hword 0x20F8  @ movs r0, #0xf8
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4020  @ ands r0, r4
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4369  @ muls r1, r5, r1
    .hword 0x20F8  @ movs r0, #0xf8
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4018  @ ands r0, r3
    .hword 0x4378  @ muls r0, r7, r0
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x1109  @ asrs r1, r1, #4
    .hword 0x20F8  @ movs r0, #0xf8
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x4001  @ ands r1, r0
    .hword 0x1852  @ adds r2, r2, r1
    .hword 0x4650  @ mov r0, sl
    .hword 0x4020  @ ands r0, r4
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4369  @ muls r1, r5, r1
    .hword 0x4650  @ mov r0, sl
    .hword 0x4018  @ ands r0, r3
    .hword 0x4378  @ muls r0, r7, r0
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x1109  @ asrs r1, r1, #4
    .hword 0x4650  @ mov r0, sl
    .hword 0x4001  @ ands r1, r0
    .hword 0x1852  @ adds r2, r2, r1
    .hword 0x4641  @ mov r1, r8
    .hword 0x800A  @ strh r2, [r1]
    .hword 0x2002  @ movs r0, #2
    .hword 0x4480  @ add r8, r0
    .hword 0x4484  @ add ip, r0
    .hword 0x3602  @ adds r6, #2
    .hword 0x2101  @ movs r1, #1
    .hword 0x4249  @ rsbs r1, r1, #0
    .hword 0x4489  @ add sb, r1
    .hword 0x4648  @ mov r0, sb
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDACA  @ bge #0xffffff98
    .hword 0x9A01  @ ldr r2, [sp, #4]
    .hword 0x2A02  @ cmp r2, #2
    .hword 0xDD9B  @ ble #0xffffff3a
    .word 0xFAE8F75A  @ bl #0xfff5a5d4
    .hword 0xB002  @ add sp, #8
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0xC9F6  @ ldm r1, {r1, r2, r4, r5, r6, r7}
    .hword 0x084C  @ lsrs r4, r1, #1
    .hword 0xCAF6  @ ldm r2, {r1, r2, r4, r5, r6, r7}
    .hword 0x084C  @ lsrs r4, r1, #1

    .global SaveMenuGetValidMenuAmt
    .type SaveMenuGetValidMenuAmt, %function
    .thumb
    .thumb_func
SaveMenuGetValidMenuAmt:  @ 0x080A6AB0 (jp 0x080A72F4, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C0C  @ adds r4, r1, #0
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x0E03  @ lsrs r3, r0, #0x18
    .hword 0x2100  @ movs r1, #0
    .hword 0x2201  @ movs r2, #1
    .hword 0x429A  @ cmp r2, r3
    .hword 0xDA0A  @ bge #0x18
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3030  @ adds r0, #0x30
    .hword 0x7804  @ ldrb r4, [r0]
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x4010  @ ands r0, r2
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD000  @ beq #4
    .hword 0x3101  @ adds r1, #1
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x429A  @ cmp r2, r3
    .hword 0xDBF7  @ blt #0xfffffff2
    .hword 0x0608  @ lsls r0, r1, #0x18
    .hword 0x0E00  @ lsrs r0, r0, #0x18
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1

