@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x000A6800-0x000A6814
    .syntax unified

    .global StartSaveBgUp
    .type StartSaveBgUp, %function
    .thumb
    .thumb_func
StartSaveBgUp:  @ 0x080A6800 (jp 0x080A7044, score 0.7778)
    .hword 0xB500  @ push {lr}
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4802  @ ldr r0, [pc, #8]
    .word 0xFE4BF75D  @ bl #0xfff5dc9a
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0
    .hword 0x3F20  @ subs r7, #0x20
    .hword 0x08DE  @ lsrs r6, r3, #3

