@ Auto-generated by scripts/split_eu.py — do not edit by hand.
@ split-range: 0x000053F4-0x00005FF8
    .syntax unified

    .global ResetText
    .type ResetText, %function
    .thumb
    .thumb_func
ResetText:  @ 0x080053F4 (jp 0x08005280, score 0.8824)
    .hword 0xB500  @ push {lr}
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x4905  @ ldr r1, [pc, #0x14]
    .hword 0x2280  @ movs r2, #0x80
    .hword 0x2300  @ movs r3, #0
    .word 0xF80BF000  @ bl #0x1a
    .hword 0x4904  @ ldr r1, [pc, #0x10]
    .hword 0x20FF  @ movs r0, #0xff
    .hword 0x7008  @ strb r0, [r1]
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x8D58  @ ldrh r0, [r3, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x1000  @ asrs r0, r0, #0x20
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x8D78  @ ldrh r0, [r7, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .global InitTextFont
    .type InitTextFont, %function
    .thumb
    .thumb_func
InitTextFont:  @ 0x08005418 (jp 0x080052A4, score 0.8889)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD100  @ bne #4
    .hword 0x4C0A  @ ldr r4, [pc, #0x28]
    .hword 0x6021  @ str r1, [r4]
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x60E0  @ str r0, [r4, #0xc]
    .hword 0x2100  @ movs r1, #0
    .hword 0x82A3  @ strh r3, [r4, #0x14]
    .hword 0x0318  @ lsls r0, r3, #0xc
    .hword 0x1810  @ adds r0, r2, r0
    .hword 0x8220  @ strh r0, [r4, #0x10]
    .hword 0x8261  @ strh r1, [r4, #0x12]
    .word 0xFFD2F7FF  @ bl #0xffffffa8
    .hword 0x75A0  @ strb r0, [r4, #0x16]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF82CF000  @ bl #0x5c
    .word 0xFB20F000  @ bl #0x644
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x8D58  @ ldrh r0, [r3, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x58C5  @ ldr r5, [r0, r3]
    .hword 0x0800  @ lsrs r0, r0, #0x20

    .incbin "rom/fe7eu.gba", 0x5454, 0x2C

    .global ResetTextFont
    .type ResetTextFont, %function
    .thumb
    .thumb_func
ResetTextFont:  @ 0x08005480 (jp 0x08005308, score 0.75)
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x2000  @ movs r0, #0
    .hword 0x8248  @ strh r0, [r1, #0x12]
    .hword 0x4902  @ ldr r1, [pc, #8]
    .hword 0x20FF  @ movs r0, #0xff
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x4770  @ bx lr
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x8D78  @ ldrh r0, [r7, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .incbin "rom/fe7eu.gba", 0x5498, 0x24

    .global InitText
    .type InitText, %function
    .thumb
    .thumb_func
InitText:  @ 0x080054BC (jp 0x08005344, score 0.7895)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4A08  @ ldr r2, [pc, #0x20]
    .hword 0x6814  @ ldr r4, [r2]
    .hword 0x8A63  @ ldrh r3, [r4, #0x12]
    .hword 0x2200  @ movs r2, #0
    .hword 0x8003  @ strh r3, [r0]
    .hword 0x7101  @ strb r1, [r0, #4]
    .hword 0x7182  @ strb r2, [r0, #6]
    .hword 0x7142  @ strb r2, [r0, #5]
    .hword 0x71C2  @ strb r2, [r0, #7]
    .hword 0x8A62  @ ldrh r2, [r4, #0x12]
    .hword 0x1852  @ adds r2, r2, r1
    .hword 0x8262  @ strh r2, [r4, #0x12]
    .word 0xF827F000  @ bl #0x52
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .global InitTextDb
    .type InitTextDb, %function
    .thumb
    .thumb_func
InitTextDb:  @ 0x080054E4 (jp 0x0800536C, score 0.85)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x4A08  @ ldr r2, [pc, #0x20]
    .hword 0x6813  @ ldr r3, [r2]
    .hword 0x8A5A  @ ldrh r2, [r3, #0x12]
    .hword 0x2400  @ movs r4, #0
    .hword 0x8002  @ strh r2, [r0]
    .hword 0x7101  @ strb r1, [r0, #4]
    .hword 0x7184  @ strb r4, [r0, #6]
    .hword 0x2201  @ movs r2, #1
    .hword 0x7142  @ strb r2, [r0, #5]
    .hword 0x71C4  @ strb r4, [r0, #7]
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x8A58  @ ldrh r0, [r3, #0x12]
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x8259  @ strh r1, [r3, #0x12]
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .global InitTextList
    .type InitTextList, %function
    .thumb
    .thumb_func
InitTextList:  @ 0x0800550C (jp 0x08005394, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0xE004  @ b #0xc
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x7921  @ ldrb r1, [r4, #4]
    .word 0xFFD1F7FF  @ bl #0xffffffa6
    .hword 0x3408  @ adds r4, #8
    .hword 0x6820  @ ldr r0, [r4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD1F7  @ bne #0xfffffff2
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global ClearText
    .type ClearText, %function
    .thumb
    .thumb_func
ClearText:  @ 0x08005528 (jp 0x080053B0, score 0.8462)
    .hword 0xB510  @ push {r4, lr}
    .hword 0xB081  @ sub sp, #4
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x2000  @ movs r0, #0
    .hword 0x70A0  @ strb r0, [r4, #2]
    .hword 0x70E0  @ strb r0, [r4, #3]
    .hword 0x9000  @ str r0, [sp]
    .hword 0x4809  @ ldr r0, [pc, #0x24]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x68C1  @ ldr r1, [r0, #0xc]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF96DF0BB  @ bl #0xbb2de
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x7922  @ ldrb r2, [r4, #4]
    .hword 0x0112  @ lsls r2, r2, #4
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x0440  @ lsls r0, r0, #0x11
    .hword 0x4302  @ orrs r2, r0
    .hword 0x4668  @ mov r0, sp
    .word 0xF842F0BB  @ bl #0xbb088
    .hword 0xB001  @ add sp, #4
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .incbin "rom/fe7eu.gba", 0x5560, 0x68

    .global Text_SetParams
    .type Text_SetParams, %function
    .thumb
    .thumb_func
Text_SetParams:  @ 0x080055C8 (jp 0x08005458, score 1.0)
    .hword 0x7081  @ strb r1, [r0, #2]
    .hword 0x70C2  @ strb r2, [r0, #3]
    .hword 0x4770  @ bx lr
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x55D0, 0x4E

    .global PutBlankText
    .type PutBlankText, %function
    .thumb
    .thumb_func
PutBlankText:  @ 0x0800561E (jp 0x080054B0, score 0.9286)
    .hword 0x7900  @ ldrb r0, [r0, #4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD009  @ beq #0x16
    .hword 0x2300  @ movs r3, #0
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x800B  @ strh r3, [r1]
    .hword 0x1C08  @ adds r0, r1, #0
    .hword 0x3040  @ adds r0, #0x40
    .hword 0x8003  @ strh r3, [r0]
    .hword 0x3102  @ adds r1, #2
    .hword 0x3A01  @ subs r2, #1
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xD1F7  @ bne #0xfffffff2
    .hword 0xBC01  @ pop {r0}

    .incbin "rom/fe7eu.gba", 0x563A, 0x2

    .global GetStringTextLen
    .type GetStringTextLen, %function
    .thumb
    .thumb_func
GetStringTextLen:  @ 0x0800563C (jp 0x080054CC, score 0.8276)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x2400  @ movs r4, #0
    .hword 0x4805  @ ldr r0, [pc, #0x14]
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x7D89  @ ldrb r1, [r1, #0x16]
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x2903  @ cmp r1, #3
    .hword 0xD01E  @ beq #0x40
    .hword 0x1C10  @ adds r0, r2, #0
    .word 0xFAF8F000  @ bl #0x5f4
    .hword 0xE01E  @ b #0x40
    .hword 0x0000  @ movs r0, r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x7813  @ ldrb r3, [r2]
    .hword 0x3201  @ adds r2, #1
    .hword 0x2B1F  @ cmp r3, #0x1f
    .hword 0xD913  @ bls #0x2a
    .hword 0x7810  @ ldrb r0, [r2]
    .hword 0x3201  @ adds r2, #1
    .hword 0x6829  @ ldr r1, [r5]
    .hword 0x6849  @ ldr r1, [r1, #4]
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x4901  @ ldr r1, [pc, #4]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0xE002  @ b #8
    .byte 0x00
    .byte 0xFF
    .word 0x6809FFFF  @ vtbl.8 d22, {d15}, d9
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD004  @ beq #0xc
    .hword 0x7908  @ ldrb r0, [r1, #4]
    .hword 0x4298  @ cmp r0, r3
    .hword 0xD1F9  @ bne #0xfffffff6
    .hword 0x7948  @ ldrb r0, [r1, #5]
    .hword 0x1824  @ adds r4, r4, r0
    .hword 0x7810  @ ldrb r0, [r2]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD8E4  @ bhi #0xffffffcc
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC02  @ pop {r1}

    .incbin "rom/fe7eu.gba", 0x5698, 0x58

    .global GetStringTextCenteredPos
    .type GetStringTextCenteredPos, %function
    .thumb
    .thumb_func
GetStringTextCenteredPos:  @ 0x080056F0 (jp 0x08005564, score 1.0)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C08  @ adds r0, r1, #0
    .word 0xFFA1F7FF  @ bl #0xffffff46
    .hword 0x1A24  @ subs r4, r4, r0
    .hword 0x0FE0  @ lsrs r0, r4, #0x1f
    .hword 0x1824  @ adds r4, r4, r0
    .hword 0x1064  @ asrs r4, r4, #1
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x0000  @ movs r0, r0

    .global GetStringTextBox
    .type GetStringTextBox, %function
    .thumb
    .thumb_func
GetStringTextBox:  @ 0x0800570C (jp 0x08005580, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x1C15  @ adds r5, r2, #0
    .hword 0x2000  @ movs r0, #0
    .hword 0x6030  @ str r0, [r6]
    .hword 0x6028  @ str r0, [r5]
    .word 0xFC20F00D  @ bl #0xd844
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0xE000  @ b #4
    .hword 0x3401  @ adds r4, #1
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD911  @ bls #0x26
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFF87F7FF  @ bl #0xffffff12
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x6830  @ ldr r0, [r6]
    .hword 0x4288  @ cmp r0, r1
    .hword 0xDA00  @ bge #4
    .hword 0x6031  @ str r1, [r6]
    .hword 0x6828  @ ldr r0, [r5]
    .hword 0x3010  @ adds r0, #0x10
    .hword 0x6028  @ str r0, [r5]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xF808F000  @ bl #0x14
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD1E9  @ bne #0xffffffd6
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .incbin "rom/fe7eu.gba", 0x5754, 0x13E

    .global GetStringLineEnd
    .type GetStringLineEnd, %function
    .thumb
    .thumb_func
GetStringLineEnd:  @ 0x08005892 (jp 0x080055C8, score 1.0)
    .hword 0xE002  @ b #8
    .byte 0x00
    .byte 0xFF
    .word 0x6809FFFF  @ vtbl.8 d22, {d15}, d9
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD106  @ bne #0x10
    .hword 0x2381  @ movs r3, #0x81
    .hword 0x22A7  @ movs r2, #0xa7
    .hword 0x4E01  @ ldr r6, [pc, #4]
    .hword 0xE7EE  @ b #0xffffffe0

    .incbin "rom/fe7eu.gba", 0x58A6, 0x3E

    .global GetColorLut
    .type GetColorLut, %function
    .thumb
    .thumb_func
GetColorLut:  @ 0x080058E4 (jp 0x08005764, score 1.0)
    .hword 0x4902  @ ldr r1, [pc, #8]
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x4770  @ bx lr
    .hword 0x0000  @ movs r0, r0
    .byte 0xF0
    .hword 0xC7F8  @ stm r7!, {r3, r4, r5, r6, r7}
    .byte 0x08

    .global DrawTextGlyph
    .type DrawTextGlyph, %function
    .thumb
    .thumb_func
DrawTextGlyph:  @ 0x080058F4 (jp 0x08005774, score 0.8125)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB460  @ push {r5, r6}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x4689  @ mov sb, r1
    .hword 0x480F  @ ldr r0, [pc, #0x3c]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x68C1  @ ldr r1, [r0, #0xc]
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFF88F0BA  @ bl #0xbaf14
    .hword 0x4680  @ mov r8, r0
    .hword 0x78A8  @ ldrb r0, [r5, #2]
    .hword 0x2407  @ movs r4, #7
    .hword 0x4004  @ ands r4, r0
    .hword 0x464E  @ mov r6, sb
    .hword 0x3608  @ adds r6, #8
    .hword 0x78E8  @ ldrb r0, [r5, #3]
    .word 0xFFE3F7FF  @ bl #0xffffffca
    .hword 0x4641  @ mov r1, r8
    .hword 0x1C32  @ adds r2, r6, #0
    .hword 0x1C23  @ adds r3, r4, #0
    .word 0xFD0EF7FE  @ bl #0xffffea20
    .hword 0x4649  @ mov r1, sb
    .hword 0x7948  @ ldrb r0, [r1, #5]
    .hword 0x78A9  @ ldrb r1, [r5, #2]
    .hword 0x1840  @ adds r0, r0, r1
    .hword 0x70A8  @ strb r0, [r5, #2]
    .hword 0xBC18  @ pop {r3, r4}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .global DrawTextGlyphNoClear
    .type DrawTextGlyphNoClear, %function
    .thumb
    .thumb_func
DrawTextGlyphNoClear:  @ 0x08005944 (jp 0x080057C4, score 0.7812)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB086  @ sub sp, #0x18
    .hword 0x9000  @ str r0, [sp]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x484A  @ ldr r0, [pc, #0x128]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x68C1  @ ldr r1, [r0, #0xc]
    .hword 0x9800  @ ldr r0, [sp]
    .word 0xFF5EF0BA  @ bl #0xbaec0
    .hword 0x9003  @ str r0, [sp, #0xc]
    .hword 0x9900  @ ldr r1, [sp]
    .hword 0x7888  @ ldrb r0, [r1, #2]
    .hword 0x2207  @ movs r2, #7
    .hword 0x4002  @ ands r2, r0
    .hword 0x9204  @ str r2, [sp, #0x10]
    .hword 0x9B01  @ ldr r3, [sp, #4]
    .hword 0x3308  @ adds r3, #8
    .hword 0x9305  @ str r3, [sp, #0x14]
    .hword 0x2009  @ movs r0, #9
    .word 0xFFB6F7FF  @ bl #0xffffff70
    .hword 0x4682  @ mov sl, r0
    .hword 0x9900  @ ldr r1, [sp]
    .hword 0x78C8  @ ldrb r0, [r1, #3]
    .word 0xFFB1F7FF  @ bl #0xffffff66
    .hword 0x4681  @ mov sb, r0
    .hword 0x220F  @ movs r2, #0xf
    .hword 0x9202  @ str r2, [sp, #8]
    .hword 0x9F03  @ ldr r7, [sp, #0xc]
    .hword 0x3740  @ adds r7, #0x40
    .hword 0x9B05  @ ldr r3, [sp, #0x14]
    .hword 0xCB01  @ ldm r3!, {r0}
    .hword 0x9305  @ str r3, [sp, #0x14]
    .hword 0x2100  @ movs r1, #0
    .hword 0x9B04  @ ldr r3, [sp, #0x10]
    .hword 0x005A  @ lsls r2, r3, #1
    .word 0xFF24F0BA  @ bl #0xbae4c
    .hword 0x26FF  @ movs r6, #0xff
    .hword 0x4006  @ ands r6, r0
    .hword 0x0076  @ lsls r6, r6, #1
    .hword 0x4653  @ mov r3, sl
    .hword 0x18F2  @ adds r2, r6, r3
    .hword 0x8812  @ ldrh r2, [r2]
    .hword 0x4690  @ mov r8, r2
    .hword 0x060D  @ lsls r5, r1, #0x18
    .hword 0x0A04  @ lsrs r4, r0, #8
    .hword 0x1C2A  @ adds r2, r5, #0
    .hword 0x4322  @ orrs r2, r4
    .hword 0x24FF  @ movs r4, #0xff
    .hword 0x4014  @ ands r4, r2
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x18E2  @ adds r2, r4, r3
    .hword 0x8812  @ ldrh r2, [r2]
    .hword 0x0412  @ lsls r2, r2, #0x10
    .hword 0x4643  @ mov r3, r8
    .hword 0x4313  @ orrs r3, r2
    .hword 0x9A03  @ ldr r2, [sp, #0xc]
    .hword 0x6815  @ ldr r5, [r2]
    .hword 0x401D  @ ands r5, r3
    .hword 0x6015  @ str r5, [r2]
    .hword 0x444E  @ add r6, sb
    .hword 0x8833  @ ldrh r3, [r6]
    .hword 0x444C  @ add r4, sb
    .hword 0x8822  @ ldrh r2, [r4]
    .hword 0x0412  @ lsls r2, r2, #0x10
    .hword 0x4313  @ orrs r3, r2
    .hword 0x431D  @ orrs r5, r3
    .hword 0x9B03  @ ldr r3, [sp, #0xc]
    .hword 0xC320  @ stm r3!, {r5}
    .hword 0x9303  @ str r3, [sp, #0xc]
    .hword 0x040D  @ lsls r5, r1, #0x10
    .hword 0x0C04  @ lsrs r4, r0, #0x10
    .hword 0x1C2A  @ adds r2, r5, #0
    .hword 0x4322  @ orrs r2, r4
    .hword 0x26FF  @ movs r6, #0xff
    .hword 0x4016  @ ands r6, r2
    .hword 0x0076  @ lsls r6, r6, #1
    .hword 0x4653  @ mov r3, sl
    .hword 0x18F2  @ adds r2, r6, r3
    .hword 0x8812  @ ldrh r2, [r2]
    .hword 0x4690  @ mov r8, r2
    .hword 0x020D  @ lsls r5, r1, #8
    .hword 0x0E04  @ lsrs r4, r0, #0x18
    .hword 0x1C2A  @ adds r2, r5, #0
    .hword 0x4322  @ orrs r2, r4
    .hword 0x24FF  @ movs r4, #0xff
    .hword 0x4014  @ ands r4, r2
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x18E2  @ adds r2, r4, r3
    .hword 0x8812  @ ldrh r2, [r2]
    .hword 0x0412  @ lsls r2, r2, #0x10
    .hword 0x4643  @ mov r3, r8
    .hword 0x4313  @ orrs r3, r2
    .hword 0x683D  @ ldr r5, [r7]
    .hword 0x401D  @ ands r5, r3
    .hword 0x444E  @ add r6, sb
    .hword 0x8833  @ ldrh r3, [r6]
    .hword 0x444C  @ add r4, sb
    .hword 0x8822  @ ldrh r2, [r4]
    .hword 0x0412  @ lsls r2, r2, #0x10
    .hword 0x4313  @ orrs r3, r2
    .hword 0x431D  @ orrs r5, r3
    .hword 0x603D  @ str r5, [r7]
    .hword 0x1C0A  @ adds r2, r1, #0
    .hword 0x24FF  @ movs r4, #0xff
    .hword 0x4014  @ ands r4, r2
    .hword 0x0064  @ lsls r4, r4, #1
    .hword 0x4653  @ mov r3, sl
    .hword 0x18E2  @ adds r2, r4, r3
    .hword 0x8815  @ ldrh r5, [r2]
    .hword 0x0A0A  @ lsrs r2, r1, #8
    .hword 0x21FF  @ movs r1, #0xff
    .hword 0x4011  @ ands r1, r2
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x4652  @ mov r2, sl
    .hword 0x1888  @ adds r0, r1, r2
    .hword 0x8800  @ ldrh r0, [r0]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4305  @ orrs r5, r0
    .hword 0x6C3B  @ ldr r3, [r7, #0x40]
    .hword 0x402B  @ ands r3, r5
    .hword 0x444C  @ add r4, sb
    .hword 0x8822  @ ldrh r2, [r4]
    .hword 0x4449  @ add r1, sb
    .hword 0x8808  @ ldrh r0, [r1]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4302  @ orrs r2, r0
    .hword 0x4313  @ orrs r3, r2
    .hword 0x643B  @ str r3, [r7, #0x40]
    .hword 0x3704  @ adds r7, #4
    .hword 0x9B02  @ ldr r3, [sp, #8]
    .hword 0x3B01  @ subs r3, #1
    .hword 0x9302  @ str r3, [sp, #8]
    .hword 0x2B00  @ cmp r3, #0
    .hword 0xDA95  @ bge #0xffffff2e
    .hword 0x9901  @ ldr r1, [sp, #4]
    .hword 0x7948  @ ldrb r0, [r1, #5]
    .hword 0x9A00  @ ldr r2, [sp]
    .hword 0x7892  @ ldrb r2, [r2, #2]
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x9B00  @ ldr r3, [sp]
    .hword 0x7098  @ strb r0, [r3, #2]
    .hword 0xB006  @ add sp, #0x18
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .incbin "rom/fe7eu.gba", 0x5A84, 0x94

    .global PutDrawText
    .type PutDrawText, %function
    .thumb
    .thumb_func
PutDrawText:  @ 0x08005B18 (jp 0x08005998, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0xB082  @ sub sp, #8
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C0F  @ adds r7, r1, #0
    .hword 0x1C16  @ adds r6, r2, #0
    .hword 0x1C1D  @ adds r5, r3, #0
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD104  @ bne #0xc
    .hword 0x466C  @ mov r4, sp
    .hword 0x4668  @ mov r0, sp
    .hword 0x9907  @ ldr r1, [sp, #0x1c]
    .word 0xFCC5F7FF  @ bl #0xfffff98e
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFD3DF7FF  @ bl #0xfffffa7e
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C31  @ adds r1, r6, #0
    .word 0xFD3FF7FF  @ bl #0xfffffa82
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x9908  @ ldr r1, [sp, #0x20]
    .word 0xFE0DF7FF  @ bl #0xfffffc1e
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C39  @ adds r1, r7, #0
    .word 0xFD3FF7FF  @ bl #0xfffffa82
    .hword 0xB002  @ add sp, #8
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global Text_InsertDrawString
    .type Text_InsertDrawString, %function
    .thumb
    .thumb_func
Text_InsertDrawString:  @ 0x08005B5C (jp 0x080059DC, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C15  @ adds r5, r2, #0
    .hword 0x1C1E  @ adds r6, r3, #0
    .word 0xFD26F7FF  @ bl #0xfffffa50
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFD28F7FF  @ bl #0xfffffa54
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C31  @ adds r1, r6, #0
    .word 0xFDF6F7FF  @ bl #0xfffffbf0
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global Text_InsertDrawNumberOrBlank
    .type Text_InsertDrawNumberOrBlank, %function
    .thumb
    .thumb_func
Text_InsertDrawNumberOrBlank:  @ 0x08005B80 (jp 0x08005A00, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C15  @ adds r5, r2, #0
    .hword 0x1C1E  @ adds r6, r3, #0
    .word 0xFD14F7FF  @ bl #0xfffffa2c
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C29  @ adds r1, r5, #0
    .word 0xFD16F7FF  @ bl #0xfffffa30
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C31  @ adds r1, r6, #0
    .word 0xFE42F7FF  @ bl #0xfffffc88
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0

    .global Text_DrawStringAscii
    .type Text_DrawStringAscii, %function
    .thumb
    .thumb_func
Text_DrawStringAscii:  @ 0x08005BA4 (jp 0x08005A24, score 0.7931)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0C  @ adds r4, r1, #0
    .hword 0xE010  @ b #0x24
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x6803  @ ldr r3, [r0]
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x685A  @ ldr r2, [r3, #4]
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x3401  @ adds r4, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD102  @ bne #8
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x30FC  @ adds r0, #0xfc
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x689A  @ ldr r2, [r3, #8]
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFE29F0BA  @ bl #0xbac56
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x2801  @ cmp r0, #1
    .hword 0xD8EB  @ bhi #0xffffffda
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .global Text_DrawCharacterAscii
    .type Text_DrawCharacterAscii, %function
    .thumb
    .thumb_func
Text_DrawCharacterAscii:  @ 0x08005BE0 (jp 0x08005A60, score 0.8)
    .hword 0xB530  @ push {r4, r5, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0C  @ adds r4, r1, #0
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x6803  @ ldr r3, [r0]
    .hword 0x7820  @ ldrb r0, [r4]
    .hword 0x685A  @ ldr r2, [r3, #4]
    .hword 0x0080  @ lsls r0, r0, #2
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x3401  @ adds r4, #1
    .hword 0x2900  @ cmp r1, #0
    .hword 0xD102  @ bne #8
    .hword 0x1C10  @ adds r0, r2, #0
    .hword 0x30FC  @ adds r0, #0xfc
    .hword 0x6801  @ ldr r1, [r0]
    .hword 0x689A  @ ldr r2, [r3, #8]
    .hword 0x1C28  @ adds r0, r5, #0
    .word 0xFE0CF0BA  @ bl #0xbac1c
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0xBC30  @ pop {r4, r5}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .incbin "rom/fe7eu.gba", 0x5C14, 0x64

    .global InitSpriteTextFont
    .type InitSpriteTextFont, %function
    .thumb
    .thumb_func
InitSpriteTextFont:  @ 0x08005C78 (jp 0x08005ACC, score 0.8571)
    .hword 0xB510  @ push {r4, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x6021  @ str r1, [r4]
    .hword 0x480B  @ ldr r0, [pc, #0x2c]
    .hword 0x60E0  @ str r0, [r4, #0xc]
    .hword 0x200F  @ movs r0, #0xf
    .hword 0x4002  @ ands r2, r0
    .hword 0x3210  @ adds r2, #0x10
    .hword 0x2000  @ movs r0, #0
    .hword 0x82A2  @ strh r2, [r4, #0x14]
    .hword 0x03C9  @ lsls r1, r1, #0xf
    .hword 0x0D09  @ lsrs r1, r1, #0x14
    .hword 0x8221  @ strh r1, [r4, #0x10]
    .hword 0x8260  @ strh r0, [r4, #0x12]
    .word 0xFBA2F7FF  @ bl #0xfffff748
    .hword 0x75A0  @ strb r0, [r4, #0x16]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFBFCF7FF  @ bl #0xfffff7fc
    .hword 0x4803  @ ldr r0, [pc, #0xc]
    .hword 0x60A0  @ str r0, [r4, #8]
    .hword 0xBC10  @ pop {r4}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x5D65  @ ldrb r5, [r4, r5]
    .hword 0x0800  @ lsrs r0, r0, #0x20
    .hword 0x5D85  @ ldrb r5, [r0, r6]
    .hword 0x0800  @ lsrs r0, r0, #0x20

    .global InitSpriteText
    .type InitSpriteText, %function
    .thumb
    .thumb_func
InitSpriteText:  @ 0x08005CB4 (jp 0x08005B08, score 0.8889)
    .hword 0x4907  @ ldr r1, [pc, #0x1c]
    .hword 0x680B  @ ldr r3, [r1]
    .hword 0x8A59  @ ldrh r1, [r3, #0x12]
    .hword 0x2200  @ movs r2, #0
    .hword 0x8001  @ strh r1, [r0]
    .hword 0x2120  @ movs r1, #0x20
    .hword 0x7101  @ strb r1, [r0, #4]
    .hword 0x7182  @ strb r2, [r0, #6]
    .hword 0x7142  @ strb r2, [r0, #5]
    .hword 0x71C2  @ strb r2, [r0, #7]
    .hword 0x8A59  @ ldrh r1, [r3, #0x12]
    .hword 0x3140  @ adds r1, #0x40
    .hword 0x8259  @ strh r1, [r3, #0x12]
    .hword 0x7082  @ strb r2, [r0, #2]
    .hword 0x70C2  @ strb r2, [r0, #3]
    .hword 0x4770  @ bx lr
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .global SpriteText_DrawBackground
    .type SpriteText_DrawBackground, %function
    .thumb
    .thumb_func
SpriteText_DrawBackground:  @ 0x08005CD8 (jp 0x08005B2C, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0xB082  @ sub sp, #8
    .hword 0x1C07  @ adds r7, r0, #0
    .hword 0x7938  @ ldrb r0, [r7, #4]
    .hword 0x2800  @ cmp r0, #0
    .hword 0xD01E  @ beq #0x40
    .hword 0x2000  @ movs r0, #0
    .hword 0x70B8  @ strb r0, [r7, #2]
    .hword 0x4C10  @ ldr r4, [pc, #0x40]
    .hword 0x9400  @ str r4, [sp]
    .hword 0x4D10  @ ldr r5, [pc, #0x40]
    .hword 0x6828  @ ldr r0, [r5]
    .hword 0x68C1  @ ldr r1, [r0, #0xc]
    .hword 0x1C38  @ adds r0, r7, #0
    .word 0xFD92F0BA  @ bl #0xbab28
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4E0E  @ ldr r6, [pc, #0x38]
    .hword 0x4668  @ mov r0, sp
    .hword 0x1C32  @ adds r2, r6, #0
    .word 0xFC6AF0BA  @ bl #0xba8d8
    .hword 0x9401  @ str r4, [sp, #4]
    .hword 0xAC01  @ add r4, sp, #4
    .hword 0x6828  @ ldr r0, [r5]
    .hword 0x68C1  @ ldr r1, [r0, #0xc]
    .hword 0x1C38  @ adds r0, r7, #0
    .word 0xFD85F0BA  @ bl #0xbab0e
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2080  @ movs r0, #0x80
    .hword 0x00C0  @ lsls r0, r0, #3
    .hword 0x1809  @ adds r1, r1, r0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x1C32  @ adds r2, r6, #0
    .word 0xFC5BF0BA  @ bl #0xba8ba
    .hword 0xB002  @ add sp, #8
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x4444  @ add r4, r8
    .hword 0x4444  @ add r4, r8
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x00D8  @ lsls r0, r3, #3
    .hword 0x0100  @ lsls r0, r0, #4

    .global SpriteText_DrawBackgroundExt
    .type SpriteText_DrawBackgroundExt, %function
    .thumb
    .thumb_func
SpriteText_DrawBackgroundExt:  @ 0x08005D38 (jp 0x08005B8C, score 0.9)
    .hword 0xB500  @ push {lr}
    .hword 0xB081  @ sub sp, #4
    .hword 0x2200  @ movs r2, #0
    .hword 0x7082  @ strb r2, [r0, #2]
    .hword 0x9100  @ str r1, [sp]
    .hword 0x4906  @ ldr r1, [pc, #0x18]
    .hword 0x6809  @ ldr r1, [r1]
    .hword 0x68C9  @ ldr r1, [r1, #0xc]
    .word 0xFD68F0BA  @ bl #0xbaad4
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x4A04  @ ldr r2, [pc, #0x10]
    .hword 0x4668  @ mov r0, sp
    .word 0xFC41F0BA  @ bl #0xba886
    .hword 0xB001  @ add sp, #4
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8
    .hword 0x0200  @ lsls r0, r0, #8
    .hword 0x0100  @ lsls r0, r0, #4

    .incbin "rom/fe7eu.gba", 0x5D64, 0x20

    .global DrawSpriteTextGlyph
    .type DrawSpriteTextGlyph, %function
    .thumb
    .thumb_func
DrawSpriteTextGlyph:  @ 0x08005D84 (jp 0x08005BDC, score 0.9062)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x4657  @ mov r7, sl
    .hword 0x464E  @ mov r6, sb
    .hword 0x4645  @ mov r5, r8
    .hword 0xB4E0  @ push {r5, r6, r7}
    .hword 0xB085  @ sub sp, #0x14
    .hword 0x9000  @ str r0, [sp]
    .hword 0x9101  @ str r1, [sp, #4]
    .hword 0x4866  @ ldr r0, [pc, #0x198]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x68C1  @ ldr r1, [r0, #0xc]
    .hword 0x9800  @ ldr r0, [sp]
    .word 0xFD3EF0BA  @ bl #0xbaa80
    .hword 0x1C07  @ adds r7, r0, #0
    .hword 0x9900  @ ldr r1, [sp]
    .hword 0x7888  @ ldrb r0, [r1, #2]
    .hword 0x2207  @ movs r2, #7
    .hword 0x4002  @ ands r2, r0
    .hword 0x9202  @ str r2, [sp, #8]
    .hword 0x9B01  @ ldr r3, [sp, #4]
    .hword 0x3308  @ adds r3, #8
    .hword 0x9303  @ str r3, [sp, #0xc]
    .hword 0x78C8  @ ldrb r0, [r1, #3]
    .word 0xFD96F7FF  @ bl #0xfffffb30
    .hword 0x4680  @ mov r8, r0
    .hword 0x20FF  @ movs r0, #0xff
    .hword 0x4681  @ mov sb, r0
    .hword 0x9902  @ ldr r1, [sp, #8]
    .hword 0x0049  @ lsls r1, r1, #1
    .hword 0x9104  @ str r1, [sp, #0x10]
    .hword 0x2207  @ movs r2, #7
    .hword 0x4692  @ mov sl, r2
    .hword 0x9B03  @ ldr r3, [sp, #0xc]
    .hword 0xCB01  @ ldm r3!, {r0}
    .hword 0x9303  @ str r3, [sp, #0xc]
    .hword 0x2100  @ movs r1, #0
    .hword 0x9B02  @ ldr r3, [sp, #8]
    .hword 0x005A  @ lsls r2, r3, #1
    .word 0xFD06F0BA  @ bl #0xbaa10
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x4648  @ mov r0, sb
    .hword 0x4028  @ ands r0, r5
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x4440  @ add r0, r8
    .hword 0x8804  @ ldrh r4, [r0]
    .hword 0x0633  @ lsls r3, r6, #0x18
    .hword 0x0A2A  @ lsrs r2, r5, #8
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x4310  @ orrs r0, r2
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8810  @ ldrh r0, [r2]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4304  @ orrs r4, r0
    .hword 0x6838  @ ldr r0, [r7]
    .hword 0x4320  @ orrs r0, r4
    .hword 0x6038  @ str r0, [r7]
    .hword 0x0433  @ lsls r3, r6, #0x10
    .hword 0x0C2A  @ lsrs r2, r5, #0x10
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x4310  @ orrs r0, r2
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8814  @ ldrh r4, [r2]
    .hword 0x0233  @ lsls r3, r6, #8
    .hword 0x0E2A  @ lsrs r2, r5, #0x18
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x4310  @ orrs r0, r2
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8810  @ ldrh r0, [r2]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4304  @ orrs r4, r0
    .hword 0x6A38  @ ldr r0, [r7, #0x20]
    .hword 0x4320  @ orrs r0, r4
    .hword 0x6238  @ str r0, [r7, #0x20]
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8813  @ ldrh r3, [r2]
    .hword 0x0A30  @ lsrs r0, r6, #8
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8810  @ ldrh r0, [r2]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4303  @ orrs r3, r0
    .hword 0x6C38  @ ldr r0, [r7, #0x40]
    .hword 0x4318  @ orrs r0, r3
    .hword 0x6438  @ str r0, [r7, #0x40]
    .hword 0x3704  @ adds r7, #4
    .hword 0x2001  @ movs r0, #1
    .hword 0x4240  @ rsbs r0, r0, #0
    .hword 0x4482  @ add sl, r0
    .hword 0x4651  @ mov r1, sl
    .hword 0x2900  @ cmp r1, #0
    .hword 0xDAB3  @ bge #0xffffff6a
    .hword 0x4833  @ ldr r0, [pc, #0xcc]
    .hword 0x6800  @ ldr r0, [r0]
    .hword 0x68C1  @ ldr r1, [r0, #0xc]
    .hword 0x9800  @ ldr r0, [sp]
    .word 0xFCD8F0BA  @ bl #0xba9b4
    .hword 0x2280  @ movs r2, #0x80
    .hword 0x00D2  @ lsls r2, r2, #3
    .hword 0x1887  @ adds r7, r0, r2
    .hword 0x23FF  @ movs r3, #0xff
    .hword 0x4699  @ mov sb, r3
    .hword 0x2007  @ movs r0, #7
    .hword 0x4682  @ mov sl, r0
    .hword 0x9A03  @ ldr r2, [sp, #0xc]
    .hword 0xCA01  @ ldm r2!, {r0}
    .hword 0x9203  @ str r2, [sp, #0xc]
    .hword 0x2100  @ movs r1, #0
    .hword 0x9A04  @ ldr r2, [sp, #0x10]
    .word 0xFCAEF0BA  @ bl #0xba960
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x4648  @ mov r0, sb
    .hword 0x4028  @ ands r0, r5
    .hword 0x0040  @ lsls r0, r0, #1
    .hword 0x4440  @ add r0, r8
    .hword 0x8804  @ ldrh r4, [r0]
    .hword 0x0633  @ lsls r3, r6, #0x18
    .hword 0x0A2A  @ lsrs r2, r5, #8
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x4310  @ orrs r0, r2
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8810  @ ldrh r0, [r2]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4304  @ orrs r4, r0
    .hword 0x6838  @ ldr r0, [r7]
    .hword 0x4320  @ orrs r0, r4
    .hword 0x6038  @ str r0, [r7]
    .hword 0x0433  @ lsls r3, r6, #0x10
    .hword 0x0C2A  @ lsrs r2, r5, #0x10
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x4310  @ orrs r0, r2
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8814  @ ldrh r4, [r2]
    .hword 0x0233  @ lsls r3, r6, #8
    .hword 0x0E2A  @ lsrs r2, r5, #0x18
    .hword 0x1C18  @ adds r0, r3, #0
    .hword 0x4310  @ orrs r0, r2
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8810  @ ldrh r0, [r2]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4304  @ orrs r4, r0
    .hword 0x6A38  @ ldr r0, [r7, #0x20]
    .hword 0x4320  @ orrs r0, r4
    .hword 0x6238  @ str r0, [r7, #0x20]
    .hword 0x1C30  @ adds r0, r6, #0
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8813  @ ldrh r3, [r2]
    .hword 0x0A30  @ lsrs r0, r6, #8
    .hword 0x464A  @ mov r2, sb
    .hword 0x4002  @ ands r2, r0
    .hword 0x0052  @ lsls r2, r2, #1
    .hword 0x4442  @ add r2, r8
    .hword 0x8810  @ ldrh r0, [r2]
    .hword 0x0400  @ lsls r0, r0, #0x10
    .hword 0x4303  @ orrs r3, r0
    .hword 0x6C38  @ ldr r0, [r7, #0x40]
    .hword 0x4318  @ orrs r0, r3
    .hword 0x6438  @ str r0, [r7, #0x40]
    .hword 0x3704  @ adds r7, #4
    .hword 0x2301  @ movs r3, #1
    .hword 0x425B  @ rsbs r3, r3, #0
    .hword 0x449A  @ add sl, r3
    .hword 0x4650  @ mov r0, sl
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDAB4  @ bge #0xffffff6c
    .hword 0x9901  @ ldr r1, [sp, #4]
    .hword 0x7948  @ ldrb r0, [r1, #5]
    .hword 0x9A00  @ ldr r2, [sp]
    .hword 0x7892  @ ldrb r2, [r2, #2]
    .hword 0x1880  @ adds r0, r0, r2
    .hword 0x9B00  @ ldr r3, [sp]
    .hword 0x7098  @ strb r0, [r3, #2]
    .hword 0xB005  @ add sp, #0x14
    .hword 0xBC38  @ pop {r3, r4, r5}
    .hword 0x4698  @ mov r8, r3
    .hword 0x46A1  @ mov sb, r4
    .hword 0x46AA  @ mov sl, r5
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0
    .hword 0x0000  @ movs r0, r0
    .hword 0x8D70  @ ldrh r0, [r6, #0x2a]
    .hword 0x0202  @ lsls r2, r0, #8

    .global sub_8005D8C
    .type sub_8005D8C, %function
    .thumb
    .thumb_func
sub_8005D8C:  @ 0x08005F34 (jp 0x08005D8C, score 1.0)
    .hword 0xB570  @ push {r4, r5, r6, lr}
    .hword 0x1C04  @ adds r4, r0, #0
    .hword 0x1C21  @ adds r1, r4, #0
    .hword 0x3135  @ adds r1, #0x35
    .hword 0x7808  @ ldrb r0, [r1]
    .hword 0x3801  @ subs r0, #1
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x2800  @ cmp r0, #0
    .hword 0xDC2C  @ bgt #0x5c
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3034  @ adds r0, #0x34
    .hword 0x7800  @ ldrb r0, [r0]
    .hword 0x7008  @ strb r0, [r1]
    .hword 0x2500  @ movs r5, #0
    .hword 0x1C20  @ adds r0, r4, #0
    .hword 0x3036  @ adds r0, #0x36
    .hword 0x2100  @ movs r1, #0
    .hword 0x5641  @ ldrsb r1, [r0, r1]
    .hword 0x1C06  @ adds r6, r0, #0
    .hword 0x428D  @ cmp r5, r1
    .hword 0xDA20  @ bge #0x44
    .hword 0x6B20  @ ldr r0, [r4, #0x30]
    .hword 0x7802  @ ldrb r2, [r0]
    .hword 0x1C01  @ adds r1, r0, #0
    .hword 0x2A00  @ cmp r2, #0
    .hword 0xDB12  @ blt #0x28
    .hword 0x2A01  @ cmp r2, #1
    .hword 0xDD02  @ ble #8
    .hword 0x2A04  @ cmp r2, #4
    .hword 0xD007  @ beq #0x12
    .hword 0xE00D  @ b #0x1e
    .hword 0x6AE1  @ ldr r1, [r4, #0x2c]
    .hword 0x2000  @ movs r0, #0
    .hword 0x71C8  @ strb r0, [r1, #7]
    .hword 0x1C20  @ adds r0, r4, #0
    .word 0xFB9CF7FE  @ bl #0xffffe73c
    .hword 0xE00F  @ b #0x22
    .hword 0x1C48  @ adds r0, r1, #1
    .hword 0x6320  @ str r0, [r4, #0x30]
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .hword 0x2106  @ movs r1, #6
    .word 0xFB15F7FF  @ bl #0xfffff62e
    .hword 0xE003  @ b #0xa
    .hword 0x6AE0  @ ldr r0, [r4, #0x2c]
    .word 0xFC63F7FF  @ bl #0xfffff8ca
    .hword 0x6320  @ str r0, [r4, #0x30]
    .hword 0x3501  @ adds r5, #1
    .hword 0x2000  @ movs r0, #0
    .hword 0x5630  @ ldrsb r0, [r6, r0]
    .hword 0x4285  @ cmp r5, r0
    .hword 0xDBDE  @ blt #0xffffffc0
    .hword 0xBC70  @ pop {r4, r5, r6}
    .hword 0xBC01  @ pop {r0}
    .hword 0x4700  @ bx r0

    .global sub_8005E00
    .type sub_8005E00, %function
    .thumb
    .thumb_func
sub_8005E00:  @ 0x08005FA8 (jp 0x08005E00, score 1.0)
    .hword 0xB5F0  @ push {r4, r5, r6, r7, lr}
    .hword 0x1C05  @ adds r5, r0, #0
    .hword 0x1C0E  @ adds r6, r1, #0
    .hword 0x1C17  @ adds r7, r2, #0
    .hword 0x1C1C  @ adds r4, r3, #0
    .hword 0x2F00  @ cmp r7, #0
    .hword 0xD101  @ bne #6
    .word 0xFBD5F7FF  @ bl #0xfffff7ae
    .hword 0x2C00  @ cmp r4, #0
    .hword 0xD100  @ bne #4
    .hword 0x2401  @ movs r4, #1
    .hword 0x480A  @ ldr r0, [pc, #0x28]
    .hword 0x2103  @ movs r1, #3
    .word 0xFA6CF7FE  @ bl #0xffffe4dc
    .hword 0x1C02  @ adds r2, r0, #0
    .hword 0x62D5  @ str r5, [r2, #0x2c]
    .hword 0x6316  @ str r6, [r2, #0x30]
    .hword 0x3036  @ adds r0, #0x36
    .hword 0x2100  @ movs r1, #0
    .hword 0x7004  @ strb r4, [r0]
    .hword 0x3802  @ subs r0, #2
    .hword 0x7007  @ strb r7, [r0]
    .hword 0x3001  @ adds r0, #1
    .hword 0x7001  @ strb r1, [r0]
    .hword 0x2001  @ movs r0, #1
    .hword 0x71E8  @ strb r0, [r5, #7]
    .hword 0x1C30  @ adds r0, r6, #0
    .word 0xFBB7F7FF  @ bl #0xfffff772
    .hword 0xBCF0  @ pop {r4, r5, r6, r7}
    .hword 0xBC02  @ pop {r1}
    .hword 0x4708  @ bx r1
    .byte 0x24
    .hword 0xC7F9  @ stm r7!, {r0, r3, r4, r5, r6, r7}
    .byte 0x08

    .global sub_8005E48
    .type sub_8005E48, %function
    .thumb
    .thumb_func
sub_8005E48:  @ 0x08005FF0 (jp 0x08005E48, score 1.0)
    .hword 0x79C0  @ ldrb r0, [r0, #7]
    .hword 0x0600  @ lsls r0, r0, #0x18
    .hword 0x1600  @ asrs r0, r0, #0x18
    .hword 0x4770  @ bx lr

